### ISSUE TITLE
App Center Distribute: not available for macOS [yet || ever] ?

### ISSUE THREAD

**Issue by robbiehanson** [Microsoft/AppCenter-SDK-Apple#1011]
I'm investigating migrating from HockeyApp to AppCenter. But I see that Distribute isn't available for macOS, with no indication why. And no indication as to whether it will ever be supported.

Do you plan on adding support for Distribute on macOS ?

Also, it would helpful if the README file clarified this. For example, it could be changed to say:
_*Not available for macOS **yet**._

**Comment by elamalani** [comment]
@robbiehanson Thanks for using App Center. We don't support Distribute module for in-app updates for macOS platform yet. It's in our roadmap but there is no ETA on when it would be supported. We'll keep this thread open and keep you posted once we plan to support it.

**Comment by ThanosSiopoudis** [comment]
Is the old sparkle feed URL from HockeyApp available in an AppCenter app?
(example: https://rink.hockeyapp.net/api/2/apps/cc985ecf97c14275a2af83101fed5a33)

**Comment by clpolet** [comment]
@ThanosSiopoudis Sparkle support for macOS beta distribution is also on the roadmap but we don't have any ETA yet. [Here is the feature parity roadmap](https://hockeyapp.net/transition/) for more details. Thanks for asking.

**Comment by tonyarnold** [comment]
Has any progress been made on this? We're considering using AppCenter for distribution, but the lack of Sparkle support makes that impossible right now.

**Comment by tonyarnold** [comment]
Wait:

> Sparkle support for macOS **beta** distribution

Emphasis mine. What about production distribution?

**Comment by clpolet** [comment]
@tonyarnold for a better visibility I would suggest you to create an issue about Sparkle support on the [App Center primary repository](https://github.com/Microsoft/appcenter/issues) as it's not just about the SDK itself. I would refocus this feature request on the support of the Distribute module for the macOS AppCenter SDK.

**Comment by shpakovski** [comment]
Hi @clpolet, just in case: @tonyarnold created a [thread](https://github.com/Microsoft/appcenter/issues/202) in the App Center. Thanks.

**Comment by lumaxis** [comment]
Let's close this and continue in https://github.com/Microsoft/appcenter/issues/202 🙂
