### ISSUE TITLE
XPC+MSCrashes = real user app featurebug

### ISSUE THREAD

**Issue by ianbytchek** [Microsoft/AppCenter-SDK-Apple#1024]
Hello friends! Ping @TroubleMakerBen! I came across an interesting case while using MSCrashes with an XPC service – after doing `MSAppCenter.start(…)` the service process becomes available via `NSRunningApplication` instance.

```swift
Swift.print(NSRunningApplication.current) // <NSRunningApplication: 0x608000111040 ((null) - -1)>
MSAppCenter.start(MSAppCenter.identifier, withServices: [MSCrashes.self])
Swift.print(NSRunningApplication.current) // <NSRunningApplication: 0x6040001049b0 (com.my.app.xpc - 52214)>
```

This is actually really cool and would be great if you can share details why or how this happens? I though it has something to do with PLCrashReporter or setting a mach handler, but after disabling it via config and delegate and some code-digging couldn't find the answer.

**Comment by ianbytchek** [comment]
This is also observed when changing application type via ApplicationServices api, empty `main.swift` file shows what happens. The same affect can be achieved with creating a copy of `NSApplication`, which does this internally.

```swift
import AppKit.NSRunningApplication
import ApplicationServices.HIServices

Swift.print(NSRunningApplication.current)
var psn: ProcessSerialNumber = .init(highLongOfPSN: 0, lowLongOfPSN: UInt32(kCurrentProcess))
TransformProcessType(&psn, UInt32(kProcessTransformToBackgroundApplication))
Swift.print(NSRunningApplication.current)
```

This isn't the case with AppCenter code or in PLCrashReporter – they don't appear to use this api. What's the secret?

**Comment by TroubleMakerBen** [comment]
Hi @ianbytchek,
this is interesting. We need to look at this more closely.
Any chance you can send us a full stacktrace through support(intercom, the blue button on the App Center portal)?

**Comment by ianbytchek** [comment]
There's no crash – if I understood you correctly about the stacktrace? What I'm saying is starting AppCenter with crashes changes the application type in some untraceable way. To check this behaviour simply create a console app and put this inside the `main.swift`:

```swift
Swift.print(NSRunningApplication.current) // <NSRunningApplication: 0x608000111040 ((null) - -1)>
MSAppCenter.start(MSAppCenter.identifier, withServices: [MSCrashes.self])
Swift.print(NSRunningApplication.current) // <NSRunningApplication: 0x6040001049b0 (com.my.app - 52214)>
```

I'd like to know how AppCenter does it without any obvious api calls.

**Comment by TroubleMakerBen** [comment]
Hi @ianbytchek,

sorry for the long wait. I've meant to investigate but just didn't find the time. I've created a bug for this and it we will triage it accordingly.

**Comment by bmourat** [comment]
Hey @ianbytchek 
I've played with this a little and it seems like it is not the crashes module. If you call `start` with Analytics module, and i presume any other module, it will happen also. The reason is that while sendind start service log, sdk tries to determine screen size [here.](https://github.com/Microsoft/AppCenter-SDK-Apple/blob/develop/AppCenter/AppCenter/Internals/Device/MSDeviceTracker.m#L371) And after this call `NSRunningApplication.current` is assigned a new object. You can reproduce this by inserting call to `NSScreen.main` between print statements, like this:

```
Swift.print(NSRunningApplication.current.processIdentifier)
NSScreen.main
Swift.print(NSRunningApplication.current.processIdentifier)
```

**Comment by ianbytchek** [comment]
Thanks for figuring this out! This is interesting! My curiosity is 💯 satisfied.
