### ISSUE TITLE
Custom properties stop showing up in audience rules dialog

### ISSUE THREAD

**Issue by paulthorsteinson** [Microsoft/AppCenter-SDK-Apple#1144]
### **Description**

I want to be able to send push notifications to certain groups of users. My first test was done using the code below to create a custom property for use in defining an audience:

```swift
                let properties = MSCustomProperties()
                properties.setString("Test", forKey: "ABC")
                MSAppCenter.setCustomProperties(properties)
```

After that, I went to appcenter and was able to see this custom property in the audience rule pick list which was exactly as I expected. After that test I updated the code to include values I actually wanted. I found that no matter what I add, these new properties never show up, just the initial test one.  Here is some code I tried after with no success:

```swift

            let properties = MSCustomProperties()
            properties.setBool(true, forKey: "TestBool")
            properties.setString("Test", forKey: "TestString")
            properties.setNumber(5, forKey: "TestNum")
            MSAppCenter.setCustomProperties(properties)
```

I also tried without the debugger attached to confirm it wasn't an issue related to the debugger being attached (like crash reporting which is skipped).

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Run the first block of code to create the initial property
2. Run the second block of code to attempt to create the other properties.

### **Details**

1. Which SDK version are you using? `1.9.0`
2. Which OS version did you experience the issue on? `iOS 12.0`
3. Which Cocoapods version are you using (run `pod --version`)? `1.5.3`
4. What device version did you see this error on?  `iPhone 6s physical device`
5. What language are you using? `Swift`
6. What third party libraries are you using? `None that should affect this`
7. Please enable verbose logging for your app using `done - It looks like it is making a call so perhaps it is a server side issue:`
```
2018-09-27 12:26:00.562338-0600 SomeApp[547:63964] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/278 Sending 1/1 log, group Id: AppCenter, batch Id: 7303954D-1096-4989-B4B4-658112792ABC, session Id: 09A86BB2-8400-42BE-8A60-E9CFF0EDA60D, payload:
{
  "sid" : "09A86BB2-8400-42BE-8A60-E9CFF0EDA60D",
  "timestamp" : "2018-09-27T18:25:57.494Z",
  "device" : {
    "screenSize" : "1334x750",
    "appBuild" : "3",
    "osName" : "iOS",
    "timeZoneOffset" : -360,
    "carrierCountry" : "ca",
    "osVersion" : "12.0",
    "carrierName" : "Bell",
    "locale" : "en_CA",
    "appNamespace" : "com.someapp",
    "osBuild" : "16A366",
    "sdkName" : "appcenter.ios",
    "oemName" : "Apple",
    "model" : "iPhone8,1",
    "sdkVersion" : "1.9.0",
    "appVersion" : "1.2.33"
  },
  "type" : "customProperties",
  "properties" : [
    {
      "type" : "string",
      "value" : "Test",
      "name" : "TestString"
    },
    {
      "type" : "number",
      "value" : 5,
      "name" : "TestNum"
    },
    {
      "type" : "boolean",
      "value" : true,
      "name" : "TestBool"
    }
  ]
}
2018-09-27 12:26:00.564038-0600 SomeApp[547:63964] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:appSecret:]/94 URL: https://in.appcenter.ms/logs?api-version=1.0.0
2018-09-27 12:26:00.564319-0600 SomeApp[547:63964] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:appSecret:]/96 Headers: Install-ID = 918D6053-95E2-4BF4-8108-4332F41AD3B5, App-Secret = ****************************43c43a38, Content-Type = application/json
2018-09-27 12:26:00.819675-0600 SomeApp[547:63964] [AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/302 HTTP response received with status code=200 and payload=CorrelationId: ca7951d4-556c-4596-9cf4-ba9dd41a52b6  ReasonCode: Success
2018-09-27 12:26:00.820151-0600 SomeApp[547:63964] [AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/359 Removed call id:7303954D-1096-4989-B4B4-658112792ABC from pending calls:{
}
```

**Comment by jwallra** [comment]
@paulthorsteinson You're right, the SDK is successfully sending the log to the backend, and the JSON is correct.  This is likely a backend issue.

Please open a ticket on Intercom by using the blue button in the lower right corner of AppCenter. Someone will get in contact with you there soon!

**Comment by paulthorsteinson** [comment]
@jwallra Thats what I figured and am just waiting on a response in intercom.  Thanks!

**Comment by SudeepSingh1502** [comment]
@paulthorsteinson  Hey buddy is this issue is fixed?

**Comment by achocron** [comment]
@SudeepSingh1502 Yes, the behavior works today.

**Comment by SudeepSingh1502** [comment]
@achocron how can I verify if this working 
CustomProperties prop = new CustomProperties();
Prop.set(“username”, “sudeep”).set(“favFood”, “pasta”);
AppCenter.SetCustomProperties(prop);
My question is where can I see this prop being set in appcenter under which event or will this be reflecting on overiview dashboard. Can anyone help me out with this.

**Comment by achocron** [comment]
`SetCustomProperties` is for creating push notification audiences (read about it [here](
https://docs.microsoft.com/en-us/appcenter/push/send-notification#audiences)). If you are trying to send Analytics events with properties attached, you must use the API described [here](
https://docs.microsoft.com/en-us/appcenter/sdk/analytics/ios#custom-events). Those event properties are visible under the event info in the portal. Let me know if that helps (or doesn't)!

**Comment by achocron** [comment]
@SudeepSingh1502 Also, are you using the Xamarin SDK? There is a [different repository](https://github.com/Microsoft/AppCenter-SDK-DotNet) for the .NET SDKs. In general, I recommend posting questions about the .NET SDKs on that repository (but we can just keep this conversation here).

**Comment by SudeepSingh1502** [comment]
Hey Zander, It’s clear now I was just wandering what this customeproperties
does as I was not able to see any changes under event in  appcenter. I am
aware of trackevent properties  :)

Thanks,
Sudeep
