### ISSUE TITLE
Couldn't install AppCenter from Cocoapods

### ISSUE THREAD

**Issue by avjiang** [Microsoft/AppCenter-SDK-Apple#1219]
### **Description**

Couldn't install the SDK from Cocoapods. Following error upon installation attempt: 

    [!] Error installing AppCenter
    [!] /usr/bin/curl -f -L -o /var/folders/h7/q6p65sg5169dtmgps_yky7ph0000gn/T/d20181114-2380-1r8nri5/file.zip https://github.com/microsoft/AppCenter-SDK-Apple/releases/download/1.10.0/AppCenter-SDK-Apple-1.10.0.zip --create-dirs --netrc-optional

    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
    100   620    0   620    0     0    590      0 --:--:--  0:00:01 --:--:--   590
     14 19.1M   14 2889k    0     0   4411      0  1:16:01  0:11:10  1:04:51     0
    curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Pod init to the project 
2. Type pod 'AppCenter'

### **Details**

1. Which SDK version are you using?
    - Trying to install 1.1.0
2. Which OS version did you experience the issue on?
    - Mojave 10.14.1
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.4.0
5. What language are you using?
    - Swift

**Comment by jaelim-ms** [comment]
Can you update your local pod repo by running `pod repo update` and try it again?

**Comment by jaelim-ms** [comment]
Your issue doesn't look like it is caused by the SDK. Please check your pod repo is up-to-date and network connection on your machine. Please reopen this GitHub issue if you still have the issue.

**Comment by parthya** [comment]
@avjiang Did you manage to solve it? I am getting this issue only for this package.

**Comment by annakocheshkova** [comment]
Hi @parthya, did you try @jaelim-ms's solution? Did it work?

**Comment by parthya** [comment]
@annakocheshkova Yes, I have tried repo update. Didn’t help.

I must mention the other package I face the same issue is HockeyApp SDK, which coincidentally transitioning to AppCenter as well.

Network connection (general or even with GitHub) doesn’t seem to be the problem, as everything else works at the same time.

**Comment by parthya** [comment]
@annakocheshkova Thanks, I confirm this worked.

**Comment by justinairbase** [comment]
> @parthya I tried reproducing your issue and it seems to be working for me, both on `1.4.0` and `1.6.0`.
> You can try as well:
> 
> ```
> pod repo remove master
> pod setup
> ```
> 
> This doesn't seem to be an SDK issue, but if you send me your Podfile I might be able to help.

This did not work for me

**Comment by justinairbase** [comment]
I got it to work by removing appcenter with `yarn remove appcenter` then doing `pod install` and again installing appcenter with `yarn add appcenter` and then again doing `pod install`
