### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by justin** [microsoft/appcenter-sdk-apple#1226]
### **Description**

The prebuilt frameworks attached to each release are unable to be installed on a device because they are missing the info.plist in the embedded framework. 

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Follow instructions here to install the binary frameworks (aka not Cocoapods): https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios
2. Try to run your app and you'll see an error similar to the following:

> Failed to load Info.plist from bundle at path /Users/justin/Library/Developer/CoreSimulator/Devices/DD2C35D7-B6EC-448E-A9C0-A60606BE45E4/data/Library/Caches/com.apple.mobile.installd.staging/temp.l7LmDp/extracted/TED-Dev.app/Frameworks/AppCenterCrashes.framework

If you look in the framework download's contents, its missing an Info.plist file which is a requirement for a dynamic framework to be installed and executed. 

### **Details**

1. Which SDK version are you using?
    - 1.11.0, but I also checked the release before and the same issue exists. 
2. Which OS version did you experience the issue on?
    - All
3. Which Cocoapods version are you using (run `pod --version`)?
    - We don't use Cocoapods. We rely on Carthage or manual install for dependencies. 
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Any and all 
5. What language are you using?
    - NA
6. What third party libraries are you using?
    - NA

**Comment by achocron** [comment]
The App Center frameworks are actually static frameworks, not dynamic frameworks. I'll try reproducing and send an update after- sounds like a documentation issue.

**Comment by justin** [comment]
Thanks. If that's the case, it'll be a deal breaker in terms of us successfully migrating from Hockey to AppCenter.

**Comment by lumaxis** [comment]
@justin I'm assuming you're building the dynamic frameworks for HockeySDK yourself via Carthage? Because the distributed binaries of the HockeySDK are also static libraries.

**Comment by justin** [comment]
I downloaded these from the Releases tag since #188 says Carthage isn't supported yet.  
https://github.com/Microsoft/AppCenter-SDK-Apple/releases/tag/1.11.0

**Comment by lumaxis** [comment]
@justin Gotcha. Carthage support has been climbing our priority list lately so it's pretty likely it's going to happen rather sooner than later.
Do you definitely want to use dynamic frameworks or would e.g. Carthage support with a static library also be a viable option for your use case?

**Comment by justin** [comment]
so . . . i didn't know static frameworks were a thing as of Xcode 9. Must have missed that WWDC session! Apologies for misunderstanding. https://gph.is/29MsGZT

Wrt Carthage, we'd prefer it for managing our dependencies, but it's not like it's hard to manually update them and we have a few that we already do. If anything, just seeing a Console log posting that we are using an outdated SDK is useful as a reminder. We do try to keep as mainline as possible.

**Comment by kunal30xi** [comment]
👍 for Carthage support. We are looking to migrate from HockeyApp to AppCenter as well and are in a similar bind.

**Comment by fabiankr** [comment]
Probably related to #1270 which would make Carthage support simpler I assume.

**Comment by chickdan** [comment]
Carthage is always my preference so I can have more control over the project than with CocoaPods.

**Comment by adamayoung** [comment]
+1 for me

**Comment by samkhawase** [comment]
Is there any progress on this? I installed AppCenter*.frameworks manually from the release .zip file and I got the error saying this info.plist is missing. I checked the framework's download contents, and saw that its missing an Info.plist file. 

I would really love to use this as a dependecy using Carthage, but this is a bummer for us 😞

**Comment by elamalani** [comment]
Hey everyone,

Carthage support is definitely on our [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap#hockeyapp). We publish [Iteration plans](https://github.com/Microsoft/appcenter/wiki/Iteration-plans) each month, please check them out to see the features that are currently in works and are planned to be shipped for that month.

We will also keep this thread posted once our team starts to work on Carthage support. 

Thanks,
Ela

**Comment by shpakovski** [comment]
It may be too late actually. And if you haven’t yet started with Carthage, please consider a leap forward. Swift Package Manager is becoming a standard. I created #1653 because it wasn’t discussed in this repo yet.

**Comment by AlexRablau** [comment]
+1 Are you ever going to do this?

**Comment by nchase** [comment]
@AlexRablau this is in their Iteration Plan for September: https://github.com/microsoft/appcenter/issues/970

**Comment by jaelim-ms** [comment]
Hello all, I'm glad to announce that App Center now supports Carthage.
Please checkout [App Center SDK September release](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/2.4.0).

**Comment by shpakovski** [comment]
@jaelim-ms Thanks a lot for closing such an important issue! Could you please add a README section or a Wiki page with instructions to install it? Also, what’s a difference between Releases `AppCenter-SDK-Apple-2.4.0.carthage.framework.zip` and AppCenter-SDK-Apple-2.4.0.framework.zip? Thanks in advance!

**Comment by MatkovIvan** [comment]
Hi @shpakovski,

The docs are already there: see https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios#32-integration-via-carthage

Regarding diff between `AppCenter-SDK-Apple-2.4.0.carthage.framework.zip` and `AppCenter-SDK-Apple-2.4.0.zip` it's only about `AppCenterDistributeResources.bundle` and naming. Carthage has some requirements and limitation about this so `*.carthage.framework.zip` is for Carthage integration and second one is still here for existing users to avoid any breaking changes.

Thanks,
Ivan

**Comment by shpakovski** [comment]
@MatkovIvan Thanks a lot for the heads up! Perfect 🙌
