### ISSUE TITLE
Verify no buildSettings shell script isn't escaping paths

### ISSUE THREAD

**Issue by ksuther** [Microsoft/AppCenter-SDK-Apple#1269]
### **Description**

The `Verify no buildSettings` shell scripts fail when the project is in a path that requires escaping (such as spaces in directory names).

The variables in the shell scripts need to be quoted:

`${SRCROOT}/../Scripts/VerifyNoBuildSettings.swift ${PROJECT_NAME}.xcodeproj/project.pbxproj`

Should be something like:

`"${SRCROOT}"/../Scripts/VerifyNoBuildSettings.swift "${PROJECT_NAME}.xcodeproj/project.pbxproj"`

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Clone repository to a path with a space in one of the directories
2. Try to build

### **Details**

Cloned at 449bc09406974a7a7e45bd8007ad38dbe6144a42

**Comment by guperrot** [comment]
This was fixed in version [1.13.0](https://github.com/Microsoft/AppCenter-SDK-Apple/releases/tag/1.13.0).
