### ISSUE TITLE
MSDBStorage has no checks for empty array

### ISSUE THREAD

**Issue by nekrich** [Microsoft/AppCenter-SDK-Apple#1296]
### **Description**

AppCenter framework crashes.
Reason: `SIGABRT: *** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array`
Backtrace:
```
CoreFoundation
__exceptionPreprocess
libobjc.A.dylib
objc_exception_throw
CoreFoundation
-[__NSArrayM objectAtIndex:]
+[MSDBStorage getMaxPageCountInOpenedDatabase:] MSDBStorage.m:302
-[MSLogDBStorage saveLog:withGroupId:flags:] MSLogDBStorage.m:71
-[MSDBStorage executeQueryUsingBlock:] MSDBStorage.m:56
-[MSLogDBStorage saveLog:withGroupId:flags:] MSLogDBStorage.m:69
-[MSChannelUnitDefault enqueueItem:flags:] MSChannelUnitDefault.m:170
libdispatch.dylib
_dispatch_call_block_and_release
libdispatch.dylib
_dispatch_client_callout
libdispatch.dylib
_dispatch_queue_serial_drain
libdispatch.dylib
_dispatch_queue_invoke
libdispatch.dylib
_dispatch_queue_override_invoke
libdispatch.dylib
_dispatch_root_queue_drain
libdispatch.dylib
_dispatch_worker_thread3
libsystem_pthread.dylib
_pthread_wqthread
libsystem_pthread.dylib
start_wqthread
```

### **Repro Steps**
Got report in the Diagnostics ¯\\\_(ツ)\_/¯

### **Details**

1. Which SDK version are you using?
    - 1.13.0
2. Which OS version did you experience the issue on?
    - macOS 10.12.6
3. Which Cocoapods version are you using (run `pod --version`)?
    - none
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - MacBook Pro 13" (Retina, Mid-2017)
5. What language are you using?
    - [ ] Objective C
    - [x] Swift

I think that `getPageSizeInOpenedDatabase` & `getPageCountInOpenedDatabase` are affected too, cause of the same code: `[(NSNumber *)rows[0][0] longValue]`

**Comment by annakocheshkova** [comment]
@nekrich thanks for reporting that!
We are fixing this and will keep you updated on the progress.
