### ISSUE TITLE
1.13.1 possible crash

### ISSUE THREAD

**Issue by drewtwo** [Microsoft/AppCenter-SDK-Apple#1315]
Please list the steps used to reproduce your issue.

1. Open the app from the background.

Expected: App should open.

Actual: App Crash

### **Details**

1. Which SDK version are you using?
    - 1.13.1
2. Which OS version did you experience the issue on?
    - iOS 12
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.5.3
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone X physical device
5. What language are you using?
    - Swift
6. What third party libraries are you using?
    - Alamofire, SDWebImage, SwiftKeychainWrapper, AppCenter, AppCenter/Distribute, LicensePlist
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

Log from console during crash...
2019-02-19 17:03:52.406173-0700 XXXXXXXXX[12791:3001760] [AppCenterDistribute] ERROR: -[MSDistribute checkLatestRelease:distributionGroupId:releaseHash:]_block_invoke/444 Response:
{
  "message" : "Error: App Version not found",
  "code" : "not_found"
}
[crashlog.txt](https://github.com/Microsoft/AppCenter-SDK-Apple/files/2882510/crashlog.txt)

**Comment by jaelim-ms** [comment]
Thanks for getting it back to us. This is a known issue in version 1.13.1 and we are about to release hotfix for the issue. Please wait a couple of days to get a new version for the fix.
I apologize for your inconvenience.

**Comment by drewtwo** [comment]
Thanks for the quick response!

**Comment by jaelim-ms** [comment]
We've just released a new version, [1.13.2](https://github.com/Microsoft/AppCenter-SDK-Apple/releases/tag/1.13.2), which contains the fix for your issue. Please try the new version and reopen this issue if it doesn't resolve the issue. Thanks for reporting the issue!
