### ISSUE TITLE
1.13.2 Release Zip Containts Repo Source, Not The .Framework Files

### ISSUE THREAD

**Issue by RyanThomas73** [Microsoft/AppCenter-SDK-Apple#1349]
### **Description**

The `1.13.2` release zip file does not contain the .framework binaries. It contains the source files (e.g. .xcodeproj / .xcworkspace) files.

### **Repro Steps**

Download the `1.13.2` release zip file from the release tab.

**Expected Behavior**: It contains the AppCenter-SDK-Apple/ios/ folder with the relevant `.framework` files. The `1.13.1` release zip file has the correct file structure.

**Actual Behavior**: The zip contents contains the contents of the AppCenter-SDK-Apple repo, not the build output.

### **Details**

1. Which SDK version are you using?
  `1.13.2`
2. Which OS version did you experience the issue on?
   `any`
3. Which Cocoapods version are you using (run `pod --version`)?
  `N\A`
4. What device version did you see this error on?  Were you using an emulator or a physical device?
  `N\A`
5. What language are you using?
  `N\A`
6. What third party libraries are you using?
  `N\A`
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
  `N\A`

**Comment by achocron** [comment]
Is it possible you accidentally downloaded the wrong zip file from the release? I just tried it myself and it looked correct. The frameworks are in the iOS folder of the download root.


<img width="837" alt="screen shot 2019-03-05 at 10 33 20 am" src="https://user-images.githubusercontent.com/5619585/53828330-344eb980-3f32-11e9-8e0c-b069510ae58d.png">

**Comment by RyanThomas73** [comment]
Yes that is possible. I'll try downloading the binaries .zip again.
