### ISSUE TITLE
AppCenterDistribute: "In App Updates Disabled"

### ISSUE THREAD

**Issue by drewtwo** [Microsoft/AppCenter-SDK-Apple#1374]
### **Description**

Getting "In-app updates disabled" message on 4 different applications. App was not side loaded and browsers are not in private mode. Tested on multiple devices. Of the below things the only thing I can think of that materially changed recently was updating to cocoapods 1.6.1.

### **Repro Steps**

1. Install application from app center(http://install.appcenter.com/org/appname)
2. Open application.
3. Select "Continue" for "App" Wants to User "appcenter.ms" to Sign In
4. Browser opens and closes quickly with error "In-app updates disabled" (will also include screenshot)
![IMG_2429](https://user-images.githubusercontent.com/1162660/54140262-d534ed00-43e8-11e9-8393-bb95657e470b.PNG)

### **Details**

1. Which SDK version are you using?
    - 1.13.2 (also saw issue on 1.13.0)
2. Which OS version did you experience the issue on?
    - iOS 12.1.4, 12.1.2
3. Which Cocoapods version are you using (run `pod --version`)?
    - e.g. 1.6.1
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone X physical device, iPhone 8 plus, iPhone 6s plus, iPhone 6
5. What language are you using?
    - Swift

**Comment by annakocheshkova** [comment]
Hi @drewtwo, this is a known issue, but not with SDK. People on the team are working on it. I'll keep you updated on the progress.

**Comment by drewtwo** [comment]
Thanks for the response, I also heard back from them and it looks like it has been addressed.
