### ISSUE TITLE
Method of sending user comments alongside a crash?

### ISSUE THREAD

**Issue by tonyarnold** [Microsoft/AppCenter-SDK-Apple#1393]
### **Description**

I've reviewed the documentation, and I can't see a logical way to do this - I could use some help. I'm presenting an NSAlert, into which I've inserted an NSTextField for collecting some basic reproduction information or comments from our users, and I can get to that fine. 

What I can't find is a way to push these comments alongside an existing error report (notably not from the user confirmation handler, which is where I'd expect this functionality to work).

**Comment by annakocheshkova** [comment]
Hi @tonyarnold!
Text attachments can be useful here. [This is how to use them](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/ios#add-attachments-to-a-crash-report).
You can just save user response into a text file and then attach it inside a callback, before the crash gets sent.

**Comment by tonyarnold** [comment]
Thanks for that info, @annakocheshkova - that's helpful!
