### ISSUE TITLE
Getting Error while compiling The Code 

### ISSUE THREAD

**Issue by alex5733** [Microsoft/AppCenter-SDK-Apple#1394]
### **Description**

Please describe the issue you are facing or a feature you would like to be added to the SDK.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Add Framework , Called MSAppCenter.start in App Delegate , Press Run Button on Xcode .
**Running on Device** : Error : App installation failed, Could not inspect the application package.
**Running on Simulator Error** : 
This app could not be installed at this time.
Failed to load Info.plist from bundle at path /Users/aanil/Library/Developer/CoreSimulator/Devices/CDB14C06-6EBB-440C-AA1D-48ED4C41C8D6/data/Library/Caches/com.apple.mobile.installd.staging/temp.iLV6OU/extracted/Insite Mobile.app/Frameworks/AppCenterCrashes.framework

### **Details**

1. Which SDK version are you using?
    - e.g. 12.1
2. Which OS version did you experience the issue on?
    - e.g. iOS 12.1
3. Which Cocoapods version are you using (run `pod --version`)?
    -  N/a 
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone X physical device, iPhone XS Max Simulator 
5. What language are you using?
    - 
    -  Swift 4.2
6. What third party libraries are you using?
 - App Centre and AppCenterCrashes
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by AnastasiaKubova** [comment]
Hi, @alex5733 . Unfortunately I could not reproduce it. Please, try one of next steps:
- Check if you have non-latin letters or spaces in your project path?
- Try Product > Clean build folder.
- Try copying the .plist file from one of the working apps, into your project.
- Try to reset or replace your simulator (On the right-top corner of Simulator, click ‘Reset Content and Settings’).

Please, send verbose logs from point 7.

**Comment by annakocheshkova** [comment]
Hi @alex5733, just a friendly ping, did you manage to resolve the issue?

**Comment by dtrabo** [comment]
Hey @alex5733! 
We haven’t heard from you in a while, do you have any more questions? If so, please let us know.  

Thanks for using App Center!
