### ISSUE TITLE
AppInsights export: event property names are changed to camelCase

### ISSUE THREAD

**Issue by davestjohn** [Microsoft/AppCenter-SDK-Apple#1493]
### **Description**

I create a NSDictionary with the following values:
record being submitted: {
    CallingApplication = TextEdit;
    ClientOSLang = "en-US";
    DriverPort = lpd;
    DriverVersion = "4.23.0";
    NumberCopies = 342;
    NumberPages = 1;
    ProductModel = "Xerox VersaLink C7030";
}

The keys are all first letter uppercase and when viewed on the Application Insights dashboard, the record looks like this:
properties: {
    callingApplication = TextEdit;
    clientOSLang = "en-US";
    driverPort = lpd;
    driverVersion = "4.23.0";
    numberCopies = 342;
    numberPages = 1;
    productModel = "Xerox VersaLink C7030";
}

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a dictionary with uppercase first letter names for the keys
2. Use the AppCenter SDK to submit the trackEvent using the dictionary as the properties.

### **Details**

1. Which SDK version are you using?
    - 1.14.0
2. Which OS version did you experience the issue on?
    - macOS 10.14.4
3. Which Cocoapods version are you using (run `pod --version`)?
    - n/a
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - MacPro physical device
5. What language are you using?
    Objective C
6. What third party libraries are you using?
    N/A
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

[system_logs.logarchive.zip](https://github.com/Microsoft/AppCenter-SDK-Apple/files/3065569/system_logs.logarchive.zip)

**Comment by guperrot** [comment]
Hi, can you confirm only export is affected and not the event pages of https://appcenter.ms?

**Comment by davestjohn** [comment]
According to this bug, it's on the event pages as well.
https://github.com/Microsoft/appcenter/issues/94

**Comment by davestjohn** [comment]
Closing issue, same issue as https://github.com/Microsoft/appcenter/issues/94
