### ISSUE TITLE
AppCenter-SDK-Apple-2.0.0.zip is missing from 2.0.0 release

### ISSUE THREAD

**Issue by nwhetsell** [Microsoft/AppCenter-SDK-Apple#1589]
### Description

AppCenter-SDK-Apple-2.0.0.zip is missing from the [corresponding release](https://github.com/Microsoft/AppCenter-SDK-Apple/releases/tag/2.0.0).

**Comment by clpolet** [comment]
Hi @nwhetsell. We identified an issue with v2.0.0 so we promptly unpublished the binaries. Stay tuned, we will release a new version soon. Thanks.

**Comment by clpolet** [comment]
[AppCenter Apple SDK v2.0.1](https://github.com/Microsoft/AppCenter-SDK-Apple/releases/tag/2.0.1) now available.
