### ISSUE TITLE
In-App Updates for public distribution groups

### ISSUE THREAD

**Issue by florianbuerger** [microsoft/AppCenter-SDK-Apple#1597]
### **Description**

I have an app that uses public distribution groups. I've configured distribution and in-app updates are working if I am logged into my account. 

On tester devices, the app opens appcenter.ms and asks them to log in. I don't want them to create an App Center account which is why I am using public groups in the first place. According to https://github.com/Microsoft/AppCenter-SDK-Apple/issues/721 this should be possible?

**Comment by lumaxis** [comment]
Related to https://github.com/microsoft/appcenter/issues/182

**Comment by dhei** [comment]
Hello @florianbuerger,

Just double checking, did you turn on "Allow public access" when you create the distribution group on App Center portal? 

Can you share the `install.appcenter.ms` URL from the in-app updates of public distribution groups?

**Comment by florianbuerger** [comment]
Sure, no problem. I am certain the group is public. Is has a _Public_ badge and installation works fine for people without an App Center account. 

<img width="178" alt="Screen Shot 2019-05-08 at 6 12 38 PM" src="https://user-images.githubusercontent.com/119219/57390590-04839280-71bd-11e9-9eb0-5a2ceb85a497.png">

Here is the link: https://install.appcenter.ms/users/florianbuerger/apps/sharing/distribution_groups/external

**Comment by guperrot** [comment]
But your users have to use the public url (that does not require login) to install the application, that sets a cookie.
If the cookie is missing, then it will ask for login.

**Comment by florianbuerger** [comment]
@guperrot Thanks for the explanation. When testing it now everything seems to work just fine and I can't reproduce the issue I described above anymore.
