### ISSUE TITLE
Not able to see the test Crash in App Center portal

### ISSUE THREAD

**Issue by shyamjimishra1993** [microsoft/AppCenter-SDK-Apple#1608]
### **Not able to see the test Crash in App Center portal**

Hi,

I recently integrated the App center SDK in my project.

 On App launch, I am doing.
[MSAppCenter start:@"My App's Secret Key" withServices:@[[MSCrashes class]]];

and Trying to Test with
[MSCrashes generateTestCrash].

After Crash, When I relaunch the app, I see the network request, It says 200(Success). See attached screenshot. But I am not able to see any Crash in the App Center Portal for the app.

Is it necessary to upload DSYM file for the crash to be visible in the portal?

1. Which SDK version are you using?
    2.0.1
2. Which OS version did you experience the issue on?
     iOS 11.4
3. Which Cocoapods version are you using (run `pod --version`)?
    Added .framework manually. Cocoa Pod version  1.4.0
4. What device version did you see this error on?  Were you using an emulator or a physical device?
     iPhone 8(11.4) simulator
5. What language are you using?
     Objective C
6. What third party libraries are you using?
    NA
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here: 

Attaching Network call Request/response

<img width="1579" alt="Screenshot 2019-05-13 at 2 28 49 PM" src="https://user-images.githubusercontent.com/20599875/57608965-9ad40180-758b-11e9-8094-94b4cf354976.png">

**Comment by annakocheshkova** [comment]
Hi @shyamjimishra1993! 
First of all yes, you will need to upload dSYM files in order to see the crash. Before that, it should show up in an Unsymbolicated crashes tab: 
![image](https://user-images.githubusercontent.com/34677812/57612077-d0bdb980-757c-11e9-8261-fc2a7cb5cf9a.png)
Thanks for providing the screenshot, but it doesn't help us much. The log that you see is must likely just a session start log, not the crash log. We will need you to collect full verbose logs from the console to help you. 
Would that be possible? Do you have access to them?

**Comment by shyamjimishra1993** [comment]
Hi @annakocheshkova ,

Thanks for the quick reply.

I could see the crash in the Unsymbolicated tab. And after uploading the dSYM files, I could see it in the crashes tab. Looks good for now.

Just one quick question here. 

Is there any other alternative in App center for uploading custom crashes similar to HockeyApp: https://support.hockeyapp.net/kb/api/api-crashes#post-custom-crashes.
Or the only way is to use AppCenter-SDK-Apple for uploading the crash reports for now?

Thanks and Regards
Shyam Ji Mishra

**Comment by annakocheshkova** [comment]
@shyamjimishra1993 no, unfortunately there's no official external API in App Center to do that.

**Comment by guperrot** [comment]
Hi, you can track the feature request at https://github.com/Microsoft/appcenter/issues/31.

**Comment by shyamjimishra1993** [comment]
Thanks @annakocheshkova  @guperrot .
