### ISSUE TITLE
Automatically upload dSYMs to AppCenter

### ISSUE THREAD

**Issue by shyamjimishra1993** [microsoft/appcenter-sdk-apple#1611]
Hi,

Thanks for your support on my previous ticket.

I have done the App Center SDK integration for Crash reporting and I am able to see the crashes in Unsymbolicated tab. When I upload the required dsym file manually in the portal, I could see the crash getting symbolicated.

Is there a way to upload the dsym files automatically during the build process or so?
Looked into the documentation and didn't see it there. KIndly help me with this. 

I do see an API to upload symbol files. https://openapi.appcenter.ms/#/crash/symbolUploads_create.

I will really appreciate your help on this.

Thanks and Regards
Shyam Ji Mishra

**Comment by annakocheshkova** [comment]
Hi @shyamjimishra1993 this is indeed a good suggestion. I believe we already had such a feature request.

**Comment by annakocheshkova** [comment]
Yep, there it is: https://github.com/microsoft/appcenter/issues/169
You can track progress there if you're interested.

**Comment by shyamjimishra1993** [comment]
Thanks @annakocheshkova
