### ISSUE TITLE
Add ability to manually record non-fatal errors

### ISSUE THREAD

**Issue by sindresorhus** [microsoft/appcenter-sdk-apple#1628]
Crashlytics has the ability to [manually record errors](https://docs.fabric.io/apple/crashlytics/logged-errors.html). Those errors are then shown in the UI as "non-fatal". Would be great if AppCenter could support that too. I use it a lot in my apps. This is the only thing preventing me to move from Crashlytics.

**Comment by annakocheshkova** [comment]
@sindresorhus this is very valuable feature indeed. We already have a feature request for it. Please follow up [this thread](https://github.com/microsoft/appcenter/issues/192). Don't hesitate to upvote it - more votes means this feature request will have higher priority!
