### ISSUE TITLE
Namespace NSUserDefaults keys

### ISSUE THREAD

**Issue by sindresorhus** [microsoft/appcenter-sdk-apple#1635]
### **Description**

The SDK uses some NSUserDefault keys to store various information. This is fine, but some of the keys used are not namespaced, which makes it harder to filter them out and you also risk the keys being accidentally overwritten by apps. Since this is an SDK, it's your responsibility to be as resilient as possible.

The following keys and what they should be renamed to:

- `pastDevicesKey` => `MSPastDevicesKey`
- `SessionIdHistory` => `MSSessionIdHistory`
- `UserIdHistory` => `MSUserIdHistory`

Ideally, you should make it even more resilient by using the the prefix `MSAppCenter`, for example, `MSAppCenterPastDevicesKey`.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Add the SDK to an app
2. Run it
3. Then look at the NSUserDefaults

### **Details**

1. Which SDK version are you using?
   2.0.1
2. Which OS version did you experience the issue on?
   macOS 10.14.5
3. Which Cocoapods version are you using (run `pod --version`)?
   None
4. What device version did you see this error on?  Were you using an emulator or a physical device?
   N/A
5. What language are you using?
    - [ ] Objective C
    - [x] Swift
6. What third party libraries are you using?
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

N/A

**Comment by jayMcBee** [comment]
This goes against all guidelines for macOS/iOS - please fix!

**Comment by MatkovIvan** [comment]
Hey!
We've included the fix for this in [the latest SDK release](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/3.2.0).
