### ISSUE TITLE
2.2.0 code doesn't compile in Xcode 11.0 due to (real) error

### ISSUE THREAD

**Issue by tewha** [microsoft/appcenter-sdk-apple#1701]
This code doesn't work in the Xcode beta:

https://github.com/microsoft/appcenter-sdk-apple/blob/20769ade087fb68abd77a1743ae6d20435c2a720/AppCenter/AppCenter/Internals/HttpClient/MSHttpCall.m#L66

I believe this should be `Call attempt #%u` as `retryCount` is an `int`, but please check that.

**Comment by russelarms** [comment]
@tewha, thank you for sharing it.
I've created a PR on this issue: https://github.com/microsoft/appcenter-sdk-apple/pull/1703
