### ISSUE TITLE
SwiftUI renderer crashes when using Analytics

### ISSUE THREAD

**Issue by MikeCodesDotNET** [microsoft/appcenter-sdk-apple#1715]
### **Description**

Xcodes new SwiftUI Renderer crashes if I initialise Analytics, which appears to be related to ms_viewWillAppear. 

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   ContentView.2.preview-thunk.dylib	0x000000011b1f3086 -[UIViewController(PageViewLogging) ms_viewWillAppear:]

```
### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create new SwiftUI proiect in Xcode 11
2. Add App Center SDKs & start Analytics & Crash
3. Renderer will crash 
4. Remove Analytics, keeping only Crash
5. Renderer will start working again. 

### **Details**

1. Which SDK version are you using?
    - 2.2.0
2. Which OS version did you experience the issue on?
    Mac OS X 10.15
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.7.5
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Xcode
5. What language are you using?
    -  Swift

**Comment by michaelsmitha** [comment]
Thanks @MikeCodesDotNET! We are tracking this and will look in to the scope of the issue.

**Comment by MatkovIvan** [comment]
Hey!
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.
