### ISSUE TITLE
Change behavior of when MSDistribute asks user to update

### ISSUE THREAD

**Issue by joonmanji** [microsoft/appcenter-sdk-apple#1724]
### **Description**

In HockeyApp builds, the app checked and notified the user of an update every time the app launched. It seems like in MSDistribute, you can only get the app to ask once every day due to this `postponedTimestamp` and storage of said timestamp in `kMSPostponedTimestampKey`.

Is there any way to default the behavior to more of the old HockeyApp style?

### **Repro Steps**

1. Get MSDistribute up and running on build
2. set MSDistribute to a custom delegate `MSDistribute.setDelegate...`
3. Notice that when you call `MSDistribute.notify(.postpone)` on a custom `func distribute(_ distribute: MSDistribute!, releaseAvailableWith details: MSReleaseDetails!) -> Bool {` function in the custom `MSDistributeDelegate`

### **Details**

1. Which SDK version are you using? 2.1.0
2. Which OS version did you experience the issue on? iOS 12
3. Which Cocoapods version are you using (run `pod --version`)? 1.7.2
4. What device version did you see this error on?  Were you using an emulator or a physical device? all devices
5. What language are you using? Swift
6. What third party libraries are you using? N/A
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here: N/A

**Comment by Jamminroot** [comment]
Hey, @frankenthumbs, thanks for getting in touch. 
You are correct about the `postponedTimestamp` stored with `kMSPostponedTimestampKey` key. Only thing I can add here - one can only postpone non-mandatory updates; Mandatory updates won't have `Remind me in a day` button, thus It can't be postponed.
I'll let our PM look at your request, and we'll keep you updated in this thread.

**Comment by johnmckerrell** [comment]
It seems like it only checks when the app first runs too, whereas HockeyApp would check every time the app became active. This can mean that if you know there's an update available, but you've been running the app recently, you don't get the dialog unless you kill and restart the app. Possibly it would be better as a separate issue but as it's related I thought I'd comment here.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
