### ISSUE TITLE
MSErrorReport string representation

### ISSUE THREAD

**Issue by marciniwanicki** [microsoft/appcenter-sdk-apple#1741]
### **Description**

`MSErrorReport` is a very clean and nice data class but it's not easily representable by `NSString`. Would be great if there is a method or utils class that helps to convert it to string. 

A member method

```
- (NSString *)description;
```

should be a good candidate, but other options like `- (NSString *)toString;` would also work.

The method could leverage `PLCrashReporter` API:

```
[MSPLCrashReportTextFormatter stringValueForCrashReport:report withTextFormat:PLCrashReportTextFormatiOS];
```

Happy to create a PR if you think this idea is worth pushing forward.

### **Details**

1. Which SDK version are you using? 2.3.0

**Comment by Jamminroot** [comment]
Hey, @marciniwanicki, thanks for getting in touch. Ill let our PM team look at your request.

**Comment by hamswan** [comment]
Thanks @marciniwanicki we have added this to our feature request

**Comment by hypherion2** [comment]
Duplicate of #1720

**Comment by Harrioson** [comment]
Microsoft window is an operating system, 
which is needed to be loaded in a computer after purchasing it.
https://www.techsovibe.com/microsoft-windows/

**Comment by AnastasiaKubova** [comment]
Yes, this is a duplicate of issue #1720 . Let's track it there.
