### ISSUE TITLE
MSData change notifications

### ISSUE THREAD

**Issue by richardpineo** [microsoft/appcenter-sdk-apple#1743]
### **Description**

As a client of the sdk, I will need to detect when the underlying data changes. Currently, I don't believe it is possible to do so automatically with MSData. What would be most useful here would be a signal or callback that is triggered when new data is replicated from the server.

One other request is more documentation regarding when and how the data is refreshed along with some controls on that scheme. For example, it would be fantastic to use background loading of the data which I do not think is available currently. Is the data only updated when read by the user or is there a thread that polls or some other technique? How often does it poll? Is the only way to trigger a refresh to try to read the data directly? That is heavy-handed for large data.

In an ideal world for our use case, MSData would pull down data in the background using the [background load](https://developer.apple.com/documentation/foundation/url_loading_system/downloading_files_in_the_background) functionality of iOS and send notifications whenever the data has changed, handling offline mode gracefully as well.

**Comment by Jamminroot** [comment]
Hey, @richardpineo, thanks for getting in touch. Currently we don't have any of mentioned capabilities.
The best you can do at this point is as with regular local database - comparing stored data fingerprint to the one you get.
I'll let our PMs team look at your request.

**Comment by Zakeelm** [comment]
Hey there! Thanks for the request. 

This is actually something we're actively exploring. We're doing some investigatory work around real-time updates, which I believe will solve the points you mentioned. I can keep you in the loop on our planning. Currently, we're looking at implementing a hybrid solution that uses push notification and websockets to listen to changes in both foreground and background scenarios.

**Comment by richardpineo** [comment]
Nice! Thanks Zakeelm :) 

I think that this feature likely isn't all that much effort but it's also one that requires a good design to avoid poor performance and battery drain. The hardest part (IMO) is the background loading since (I believe) the secure file system is blocked until the user unlocks the device. 

This would be a big win for our team though since ideally we'd like the data to 'magically appear' for the user without a load time while the data updates after the application is started.

**Comment by Harrioson** [comment]
What is Microsoft OneDrive? Microsoft One drive is a place for everything (hardware)
https://www.techsovibe.com/one-drive/

**Comment by Jamminroot** [comment]
Since data module is now retired and will no longer be maintained\updated\supported, I'm closing this feature request issue.
