### ISSUE TITLE
Crashes do not upload if app is launched in background

### ISSUE THREAD

**Issue by Fluzzarn** [microsoft/appcenter-sdk-apple#1749]
### **Description**

As described in #1737 , If the application manages to start in the background and starts App Center, no crashes get uploaded and are removed from the device. Unlike #1737, even having the app relaunch itself due to being a VOIP app causes crashes to not get uploaded. Making 

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Integrate the App Center SDK into a VOIP app that is allowed to relaunch when closed
2. Crash the application.
3. (Automatic) Re-launch the app in the background and start App Center

### **Details**

1. Which SDK version are you using?
    - e.g. 2.3.0
2. Which OS version did you experience the issue on?
    - e.g. iOS 12
3. Which Cocoapods version are you using (run `pod --version`)?
    - e.g. 1.7.5
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. iPhone 8 Physical iOS 12.3
5. What language are you using?
    - [X] Swift
6. What third party libraries are you using?
    - Too many to list

7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

Due to the nature of this issue, and VOIP relaunching only available on release builds, we're unable to provide logs. We are able to confirm that If the app relaunches in the background, but have App Center start when the app is in the foreground, the crash uploads

**Comment by MatkovIvan** [comment]
Changing label to "bug" with meaning "SDK should send crashes on next resume anyway".

See https://github.com/microsoft/appcenter-sdk-apple/issues/1737#issuecomment-545379921

**Comment by Harrioson** [comment]
Microsoft has an impact on a lot of things to the life of every human being.
https://www.techsovibe.com/microsoft/

**Comment by charmian01** [comment]
Hey!
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.
