### ISSUE TITLE
Xcode cannot archive an app with pre-built frameworks

### ISSUE THREAD

**Issue by shpakovski** [microsoft/appcenter-sdk-apple#1789]
### **Description**

Pre-built frameworks cannot be used to build an app in a Release mode. This issue stops a Xcode bot from archiving an app because a dSYM cannot be generated.

### **Repro Steps**

1. Download the latest version from the Releases page and extract an archive.
2. Drop all static frameworks into your Xcode project with a Mac app.
3. Build a Product for Profiling i.e. in the Release mode.
4. Console has got a lot of warnings:

> Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.

### **Details**

1. Which SDK version are you using?
    - 2.4.0
2. Which OS version did you experience the issue on?
    - macOS 10.15
3. What device version did you see this error on?
    - MacBook Pro 15"

**Comment by annakocheshkova** [comment]
Hi @shpakovski! 
What XCode produces this warning? Is this a warning or an error - so far looks like a warning to me, but I can not reproduce this on my app.

**Comment by shpakovski** [comment]
Hi @annakocheshkova, it’s Xcode 11 from the Mac App Store. It looks like a warning, but the missed dSYM does not allow to make an Archive of the app.

**Comment by annakocheshkova** [comment]
This is strange. Does your project have some specific configuration I should know about? Do you have an `.xcconfig` or something?

**Comment by akaraul** [comment]
@annakocheshkova I have the same problem. Xcode 11, sdk version 2.4.0

**Comment by shpakovski** [comment]
@annakocheshkova Thanks for idea. I’m dissecting my Xcode workspace and trying different flags and configurations. Current status: a new Xcode project with an App Center SDK compiles as expected, but after adding lots of Swift code it doesn’t. My codebase is quite big so I need more time to figure out where it breaks. Please stay tuned…

**Comment by shpakovski** [comment]
[Warning.zip](https://github.com/microsoft/appcenter-sdk-apple/files/3652862/Warning.zip)

1. Launch `Warning.xcodeproj` from the archive
1. Build for Profiling e.g. using Command-Shuft-I

Good luck!

**Comment by annakocheshkova** [comment]
@shpakovski thanks! Although this doesn't reproduce but I'm thinking maybe it's because by mac is 10.14. I will update the OS tonight and try again.

**Comment by shpakovski** [comment]
@annakocheshkova Perfect!

@akaraul Are you on macOS 10.15 by chance? Could you please try to reproduce an issue?

**Comment by annakocheshkova** [comment]
@shpakovski asked my teammate to reproduce this on new macos - all successful. Anything else environment-related maybe?

**Comment by shpakovski** [comment]
@annakocheshkova What a shame 😄 Not sure, I had a lot of Xcode’s incl. all Betas, and it’s on macOS 10.15 Beta (19A573a). This is a full stack trace, maybe you’ll find it useful:

```log
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/Foundation-3CHX341P345SK.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/Foundation-3CHX341P345SK.pcm
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/AppKit-3LDFM4ST6FYYK.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/AppKit-3LDFM4ST6FYYK.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/ObjectiveC-1Y3G4S9BY83MF.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/ObjectiveC-1Y3G4S9BY83MF.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/Dispatch-1F1V7L6DRCHIF.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/Dispatch-1F1V7L6DRCHIF.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/IOKit-3T18SAMFD10VR.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/IOKit-3T18SAMFD10VR.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/Darwin-QU2215416B0G.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/Darwin-QU2215416B0G.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/CoreFoundation-2WFA1EITGYJ7J.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/CoreFoundation-2WFA1EITGYJ7J.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/SystemConfiguration-1XKBGOPI9KIH7.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/SystemConfiguration-1XKBGOPI9KIH7.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/CommonCrypto-379H8CGCYUV50.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/CommonCrypto-379H8CGCYUV50.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/CoreServices-R1ROV4XSKFLH.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/CoreServices-R1ROV4XSKFLH.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/CoreGraphics-1ZZ7J4P4C5A8B.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/CoreGraphics-1ZZ7J4P4C5A8B.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/Security-2O4ZGM8V6TNOZ.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/Security-2O4ZGM8V6TNOZ.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/SQLite3-QU2215416B0G.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/SQLite3-QU2215416B0G.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/zlib-QU2215416B0G.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/zlib-QU2215416B0G.pcm
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/MachO-KTUBWIPJFBHK.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/3JBSO02HNG7WR/MachO-KTUBWIPJFBHK.pcm
warning: Timestamp mismatch for /Users/vadim/Library/Caches/XCSBuilder/Bots/1b227e992e95e702e5e720c650087c97/DerivedData/Build/Intermediates.noindex/NativeUI.build/Release/NativeUI.build/Objects-normal/x86_64/NativeUI.swiftmodule: 2019-09-25 17:15:04.188477887 and 2019-09-25 16:26:55.000000000
```

**Comment by annakocheshkova** [comment]
So I have some of these errors ("No such file or directory"), but not the one you mentioned: "Linking a static library that was built with -gmodules ..."

**Comment by annakocheshkova** [comment]
@shpakovski success! This particular error was hidden under "Archive" logs, not under general Logs panel (strange Xcode behavior indeed). I am creating a bug for this.

**Comment by shpakovski** [comment]
You should probably add `CLANG_ENABLE_MODULE_DEBUGGING = YES` while building frameworks.

**Comment by annakocheshkova** [comment]
Yeah that's what we thought as well. Thanks for the suggestion!

**Comment by shpakovski** [comment]
@annakocheshkova Any workaround for us while you are resolving this issue? 😇

**Comment by annakocheshkova** [comment]
@shpakovski well, contributions are welcome :)
For now, I would suggest you to simply build the frameworks from our repo with the above-mentioned fix and use them. Simply choose **All iOS Frameworks** target, build it, and find the frameworks under **AppCenter-SDK-Apple** folder.

**Comment by shpakovski** [comment]
@annakocheshkova Alright, this works. Thanks for help!

<img width="457" alt="image" src="https://user-images.githubusercontent.com/163410/65619496-ea5e1b80-dfc8-11e9-91ef-512ef30d9d57.png">

**Comment by vg-identance** [comment]
@annakocheshkova Any estimation about releasing new version with fix?

**Comment by shpakovski** [comment]
@annakocheshkova I have checked the latest 2.5.0, and the problem is still there. Any plans to address this? Thanks.

**Comment by annakocheshkova** [comment]
@shpakovski This is definitely in our radar, we cannot commit an ETA, I will keep you posted as soon as we prioritize this. Thanks for your understanding!

**Comment by Harrioson** [comment]
Microsoft account is employed all around the world for businesses, 
causation and receiving of messages.
https://www.techsovibe.com/microsoft-account/

**Comment by annakocheshkova** [comment]
Hi there! This issue has been fixed. Please upgrade App Center to the newest version.

**Comment by shpakovski** [comment]
Confirmed, thanks!
