### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException'

### ISSUE THREAD

**Issue by mithun-grmtech** [microsoft/appcenter-sdk-apple#1797]
### *Bug*
I've got an error while compiling (Release/Debug)
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryM cordovaSettingForKey:]: unrecognized selector sent to instance 0x600003ea6ae0'

### **Description**
After build successfully myProject. I was open my project in Xcode and click the run button on Xcode. the project build successfully and display the lunch screen in simulator device. After that stuff I get an error in main.m, and this is what I see in console:

![Screenshot 2019-09-27 at 12 14 13 PM](https://user-images.githubusercontent.com/15921165/65747990-7767b880-e120-11e9-8909-904fbbc75e68.png)

tion/0F95316F-E9AD-4B3A-906E-D7552F5CBD0D/Library/Cookies/com.savantcare.provider-assistant.binarycookies
2019-09-27 11:19:56.276835+0530 myApp[1648:15477] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
2019-09-27 11:19:56.280864+0530 myApp[1648:15477] Apache Cordova native platform version 5.0.1 is starting.
2019-09-27 11:19:56.281056+0530 myApp[1648:15477] Multi-tasking -> Device: YES, App: YES
2019-09-27 11:19:56.298621+0530 myApp[1648:15477] -[__NSDictionaryM cordovaSettingForKey:]: unrecognized selector sent to instance 0x600003ea6ae0
2019-09-27 11:19:56.317885+0530 myApp[1648:15477] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryM cordovaSettingForKey:]: unrecognized selector sent to instance 0x600003ea6ae0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23bb9704 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23b9d7bc ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23b9f6c8 _CF_forwarding_prep_0 + 120
	5   myApp                  0x000000010ea2c9f3 -[CDVViewController viewDidLoad] + 227
	6   myApp                  0x000000010e9db463 -[MainViewController viewDidLoad] + 51
	7   UIKitCore                           0x00007fff46af87c2 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 83
	8   UIKitCore                           0x00007fff46afd6d3 -[UIViewController loadViewIfRequired] + 1084
	9   UIKitCore                           0x00007fff46afdaf0 -[UIViewController view] + 27
	10  UIKitCore                           0x00007fff47199b55 -[UIWindow addRootViewControllerViewIfPossible] + 150
	11  UIKitCore                           0x00007fff4719920b -[UIWindow _updateLayerOrderingAndSetLayerHidden:actionBlock:] + 232
	12  UIKitCore                           0x00007fff4719a2c9 -[UIWindow _setHidden:forced:] + 362
	13  UIKitCore                           0x00007fff471ad46d -[UIWindow _mainQueue_makeKeyAndVisible] + 42
	14  myApp                  0x000000010ea2337f -[CDVAppDelegate application:didFinishLaunchingWithOptions:] + 703
	15  myApp                  0x000000010e9db1db -[AppDelegate application:didFinishLaunchingWithOptions:] + 187
	16  myApp                  0x000000010e9ec408 -[AppDelegate(MCPlugin) application:customDidFinishLaunchingWithOptions:] + 120
	17  UIKitCore                           0x00007fff4715994f -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 232
	18  UIKitCore                           0x00007fff4715b2e7 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 3980
	19  UIKitCore                           0x00007fff47160c05 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1281
	20  UIKitCore                           0x00007fff468b58b1 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 122
	21  UIKitCore                           0x00007fff46d96cd5 _UIScenePerformActionsWithLifecycleActionMask + 83
	22  UIKitCore                           0x00007fff468b63c3 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 198
	23  UIKitCore                           0x00007fff468b5e84 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 474
	24  UIKitCore                           0x00007fff468b61f3 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 821
	25  UIKitCore                           0x00007fff468b5a85 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 345
	26  UIKitCore                           0x00007fff468b9e70 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke_2 + 159
	27  UIKitCore                           0x00007fff46cbdf8b +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] + 865
	28  UIKitCore                           0x00007fff46db51cf _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 240
	29  UIKitCore                           0x00007fff468b9b9e __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 153
	30  UIKitCore                           0x00007fff46db50d2 _UISceneSettingsDiffActionPerformActionsWithDelayForTransitionContext + 84
	31  UIKitCore                           0x00007fff468b9a0c -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 381
	32  UIKitCore                           0x00007fff46717c96 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 657
	33  UIKitCore                           0x00007fff4671681b -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 248
	34  UIKitCore                           0x00007fff467179c0 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 210
	35  UIKitCore                           0x00007fff4715f262 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 535
	36  UIKitCore                           0x00007fff46cdf774 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
	37  FrontBoardServices                  0x00007fff362e1d43 -[FBSSceneImpl _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 442
	38  FrontBoardServices                  0x00007fff3630a00c __86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke.154 + 102
	39  FrontBoardServices                  0x00007fff362ecd21 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 220
	40  FrontBoardServices                  0x00007fff36309c9d __86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke + 355
	41  libdispatch.dylib                   0x000000010ef3bd64 _dispatch_client_callout + 8
	42  libdispatch.dylib                   0x000000010ef3ecd5 _dispatch_block_invoke_direct + 300
	43  FrontBoardServices                  0x00007fff3633108a __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	44  FrontBoardServices                  0x00007fff36330d78 -[FBSSerialQueue _queue_performNextIfPossible] + 441
	45  FrontBoardServices                  0x00007fff36331287 -[FBSSerialQueue _performNextFromRunLoopSource] + 22
	46  CoreFoundation                      0x00007fff23afbac1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	47  CoreFoundation                      0x00007fff23afb9ec __CFRunLoopDoSource0 + 76
	48  CoreFoundation                      0x00007fff23afb1c4 __CFRunLoopDoSources0 + 180
	49  CoreFoundation                      0x00007fff23af5ecf __CFRunLoopRun + 1263
	50  CoreFoundation                      0x00007fff23af56b6 CFRunLoopRunSpecific + 438
	51  GraphicsServices                    0x00007fff3815cbb0 GSEventRunModal + 65
	52  UIKitCore                           0x00007fff47162a67 UIApplicationMain + 1621
	53  myApp                  0x000000010e9db101 main + 65
	54  libdyld.dylib                       0x00007fff5123bcf5 start + 1
	55  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

### **Repro Steps**
1. RUN `ionic cordova build ios`
2. Open project in Xcode
3. Run the project from Xcode

### **Details**

**Ionic:**

   Ionic CLI          : 5.4.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 2.0.0-rc.4
   @ionic/app-scripts : 3.2.4

**Cordova:**

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.2, (and 11 other plugins)

**Utility:**

   cordova-res : not installed
   native-run  : not installed

**System:**

   ios-sim : 8.0.2
   NodeJS  : v10.16.3 (/usr/local/bin/node)
   npm     : 6.11.3
   OS      : macOS Mojave
   Xcode   : Xcode 11.0 Build version 11A420a

**Comment by annakocheshkova** [comment]
Hi there @mithun-grmtech, I have a few questions. 

First, I don't quite get why this is issue in in Apple repository. Looks like a cordova one.

Second, I'm afraid I don't completely understand your use case and why exactly it is related to App Center. Are you adding cordova and App Center to the existing iOS project? The issue seems to be that **Cordova.framework** [is not added](https://cordova.apache.org/docs/en/9.x/guide/platforms/ios/webview.html#1-add-cordovaframework-to-the-xcode-project-using-carthage) but I may be wrong depending on your use case.

Might also be an issue with ionic build flags/settings, can dig in more once I get more details.

The error itself says that **CordovaPreferences** category isn't loaded which should be present iside **CordovaLib** so nothing specific to App Center here, it's just happen so that we use **CordovaPreferences** in our SDK.

Let me know if I can help more, thanks!

**Comment by medalawi** [comment]
```
2022-07-06 15:07:45.862189+0300 Runner[1469:14601] Metal API Validation Enabled
>> FAN Plugin register
FAN > BannerAdFactory > Factory register
NativeAd > Factory register
NativeBannerAd > Factory register
FANPluginFactory > init
FacebookAudienceNetworkInterstitialAdPlugin > init > end
FacebookAudienceNetworkInterstitialAdPlugin > init
FacebookAudienceNetworkInterstitialAdPlugin > init > end
2022-07-06 15:07:46.499878+0300 Runner[1469:14805] flutter: The Dart VM service is listening on http://127.0.0.1:49256/KS3qzTU6A=/
2022-07-06 15:07:47.431215+0300 Runner[1469:14785] [boringssl] boringssl_metrics_log_metric_block_invoke(153) Failed to log metrics
2022-07-06 15:07:47.365085+0300 Runner[1469:14779] 9.2.0 - [FirebaseMessaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
2022-07-06 15:07:47.489838+0300 Runner[1469:14779] 9.2.0 - [FirebaseMessaging][I-FCM002023] The object <Runner.AppDelegate: 0x600003275da0> does not respond to -messaging:didReceiveRegistrationToken:. Please implement -messaging:didReceiveRegistrationToken: to be provided with an FCM token.
2022-07-06 15:07:47.746856+0300 Runner[1469:14601] remote notifications are not supported in the simulator
2022-07-06 15:07:47.917791+0300 Runner[1469:14781] 9.2.0 - [FirebaseMessaging][I-FCM012002] Error in application:didFailToRegisterForRemoteNotificationsWithError: remote notifications are not supported in the simulator
2022-07-06 15:07:47.918949+0300 Runner[1469:14781] 9.2.0 - [FirebaseAnalytics][I-ACS023007] Analytics v.9.2.0 started
2022-07-06 15:07:47.919934+0300 Runner[1469:14781] 9.2.0 - [FirebaseAnalytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2022-07-06 15:07:47.920936+0300 Runner[1469:14781] 9.2.0 - [FirebaseAnalytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
FANPluginFactory > iOSAdvertiserTrackingEnabled: true
FANPluginFactory > init
2022-07-06 15:07:48.450304+0300 Runner[1469:14601] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'No sdk specified'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20405604 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff201a4a45 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff204054e2 -[NSException initWithCoder:] + 0
	3   Runner                              0x000000010a0131e5 -[MAInterstitialAd initWithAdUnitIdentifier:sdk:] + 333
	4   Runner                              0x0000000109e0200b -[AppLovinMAX retrieveInterstitialForAdUnitIdentifier:] + 203
	5   Runner                              0x0000000109dfec51 -[AppLovinMAX loadInterstitialForAdUnitIdentifier:] + 65
	6   Runner                              0x0000000109e069fd -[AppLovinMAX handleMethodCall:result:] + 7709
	7   Flutter                             0x000000010de30f81 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	8   Flutter                             0x000000010d86fef2 ___ZN7flutter25PlatformMessageHandlerIos21HandlePlatformMessageENSt3__110unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE_block_invoke + 86
	9   libdispatch.dylib                   0x000000010ae95816 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x000000010ae96a5b _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x000000010aea5325 _dispatch_main_queue_drain + 1169
	12  libdispatch.dylib                   0x000000010aea4e86 _dispatch_main_queue_callback_4CF + 31
	13  CoreFoundation                      0x00007fff20371ed5 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x00007fff2036c6ca __CFRunLoopRun + 2761
	15  CoreFoundation                      0x00007fff2036b704 CFRunLoopRunSpecific + 562
	16  GraphicsServices                    0x00007fff2cba9c8e GSEventRunModal + 139
	17  UIKitCore                           0x00007fff2509e65a -[UIApplication _run] + 928
	18  UIKitCore                           0x00007fff250a32b5 UIApplicationMain + 101
	19  Runner                              0x0000000109d441cf main + 63
	20  dyld                                0x000000010ae0bf21 start_sim + 10
	21  ???                                 0x00000001109c14fe 0x0 + 4573631742
)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLD_LIBRARY_PATH=/Users/mac/Library/Developer/Xcode/DerivedData/Runner-haplbxlojcewbscnrzgshqovlzqc/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib DYLD_FRAMEWORK_PATH=/Users/mac/Library/Developer/Xcode/DerivedData/Runner-haplbxlojcewbscnrzgshqovlzqc/Build/Products/Debug-iphonesimulator
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'No sdk specified'
terminating with uncaught exception of type NSException
CoreSimulator 802.6.1 - Device: iPhone 8 (3DE64384-CA4E-49AA-8A1B-A5DD75E12C25) - Runtime: iOS 15.5 (19F70) - DeviceType: iPhone 8
```
