### ISSUE TITLE
Raw translation keys visible in update dialog

### ISSUE THREAD

**Issue by JanGorman** [microsoft/appcenter-sdk-apple#1805]
### **Description**

We integrated App Center and App Center Distribute through Carthage. The strings files seem to be missing because it shows the dialog with raw translation keys:

![IMG_CEB89F5611F8-1](https://user-images.githubusercontent.com/138166/66033286-3fd58380-e507-11e9-8262-786a428a12b0.jpeg)

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Integrate according App Center Distribute according to https://docs.microsoft.com/en-us/appcenter/sdk/distribute/ios
2. Release a version and install that version
3. Release a new version and open the app. Wait for the update prompt to appear

### **Details**

1. Which SDK version are you using?
    - 2.4.0
2. Which OS version did you experience the issue on?
    - e.g. iOS 11
3. Which Cocoapods version are you using (run `pod --version`)?
    - -na-
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone 8 physical device
5. What language are you using?
    - [ ] Objective C
    - [x] Swift

**Comment by jaelim-ms** [comment]
@JanGorman, Did you add resource bundle to your Xcode project? Please checkout a section 4 in this [link](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/ios#integration-via-carthage)

**Comment by JanGorman** [comment]
I did not, managed to read over that part 🤦‍♂ – it's a public holiday today but I will give it a try tomorrow.
