### ISSUE TITLE
Unexpected Xcode Warnings 

### ISSUE THREAD

**Issue by phoney** [microsoft/appcenter-sdk-apple#1817]
### **Description**

I'm currently seeing a number of warnings when the appcenter cocoapod is included in my swift iOS Xcode project. I believe that these warnings started recently but I'm not sure the exact version. 

I'm using Appcenter 2.4.0.

Similar warnings were mentioned in issue #1789 but I don't think I'm being prevented from archiving my apps.

These appear in the GenerateDSYMFile step.
warning: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/1B76CAT92BTRK/Foundation-OIS75AKBYQKF.pcm: No such file or directory
note: while processing /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/org.llvm.clang.vsts/ModuleCache/1B76CAT92BTRK/Foundation-OIS75AKBYQKF.pcm
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.

There are about 15 more "No such file or directory" warnings that are very similar.

### **Repro Steps**

My podfile simply says

    pod 'AppCenter'

among the other pods I use. 

### **Details**

1. Which SDK version are you using?
    - 2.4.0
2. Which OS version did you experience the issue on?
    - iOS 11, macOS 10.14.6
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.8.1 but I think it was in 1.7.x aso
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    na
5. What language are you using?
    - Swift

This is a compile time issue. I'm using Xcode 11.0.

I'm guessing those files that can't be found are in the ModuleCache on your build server and are somehow referenced from the pre-built library.

**Comment by Jamminroot** [comment]
Hey, @phoney! Thanks for bringing this to our attention.
Please give us some time to investigate the issue you are facing.

**Comment by alexcosmin** [comment]
I'm also seeing this.

SDK version: 2.4.0
OS version where issue is experienced: iOS 13.1.2
Cocoapods version: 1.8.3
Language used: Swift
Seeing this on both the iOS simulator and a physical device (iPhone XR)
Compiling with Xcode 11.0 on macOS 10.14.6

<img width="1388" alt="Screen Shot 2019-10-07 at 23 26 52" src="https://user-images.githubusercontent.com/5630100/66349966-5c841800-e95a-11e9-9945-0d1e928e2762.png">

**Comment by phoney** [comment]
This forum post discusses this issue https://forums.developer.apple.com/thread/17921

**Comment by alexcosmin** [comment]
I tried SDK version 2.3.0 and noticed that these warnings are not present in that version.

**Comment by PatrickGaissert** [comment]
We are also experiencing the warning in Xcode 10.3. We are sticking with 2.3.0 for now, would be great if you could fix this.

**Comment by rmaloney3** [comment]
We are seeing the same warnings when using 2.4.0 and 2.5.0.

**Comment by MatkovIvan** [comment]
@RobertSasak it doesn't look related

@rmaloney3 a fix isn't ready yet and it wasn't shipped as part as 2.5.0

**Comment by PatrickGaissert** [comment]
Thank you for the update @MatkovIvan, looking forward to a fix in the near future.

**Comment by JonathanEsposito** [comment]
We get the exact same .pcm warnings using Carthage..

**Comment by grzegorzkrukowski** [comment]
We are getting exactly same warnings:
- using carthage
- using Xcode 11.1
- using Objective-C

**Comment by inPhilly** [comment]
When will this update where this is fixed be published? Time is of the essence...

**Comment by AnastasiaKubova** [comment]
Hi @inPhilly ! The fix has been [released](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/2.5.1). Please update App Center SDK to the last version and let me know about results.

**Comment by yvbeek** [comment]
@AnastasiaKubova When I try to install 2.5.1 using yarn, it wants me to pick 2.5.0

**Comment by MatkovIvan** [comment]
@yvbeek React-Native wrapper will be released soon.

It's expected that the last release fixed this issue, so I'm closing this issue.
Feel free to comment or reopen if you're still facing with it.

**Comment by el-lsan** [comment]
Facing this error!
any solution ?

**Comment by MatkovIvan** [comment]
@el-lsan update to the latest version, clean build cache.

If it still the case for you, please add more details about repro steps, environment, versions, etc
