### ISSUE TITLE
Error message for In-app update 

### ISSUE THREAD

**Issue by lexcellence** [microsoft/appcenter-sdk-apple#1818]
Im trying to use the in-app update service for my iPad app. However, i got some error message. I think i have followed every step of the following link.
https://docs.microsoft.com/en-us/appcenter/sdk/distribute/ios
If I still miss anything?
Thanks for any suggestion

[AppCenter] ERROR: -[MSChannelUnitDefault sendLogContainer:withAuthTokenFromArray:atIndex:]_block_invoke/264 Log(s) sent with failure, batch Id:A6E465A8-E6EA-4529-A090-5525124D51A5, status code:401

The sample code is shown as below:

 func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
 setupUI()
        MSAppCenter.start("{a7b6b1ea-xxxx-xxxx-xxxx-73ac87556c2d}", withServices: [MSAnalytics.self, MSCrashes.self, MSDistribute.self])
return true
}

MAC OS Version:10.14.6
iPad Version: 12.4.1
Swift 5

**Comment by MatkovIvan** [comment]
Hi @lexcellence,

It's caused by wrong app secret string format. Please remove `{` and `}` from there.

Best,
Ivan
