### ISSUE TITLE
Does app center SDK supports integration with app extensions?

### ISSUE THREAD

**Issue by shyamjimishra1993** [microsoft/appcenter-sdk-apple#1819]
Hi Team,

Good Day! 

**Wanted to enquire if app center SDK is supported for integration with app extensions?**
So currently, We have the following two extensions in our app and we want to collect Crash logs for the extensions as well along with regular app crashes.

1) Notification Service (iOS) 
2) Call Directory (iOS)

Could you point me to some link which you think will be helpful for integrating the app center SDK to extensions?

Thanks and Regards
Shyam Ji Mishra

**Comment by Jamminroot** [comment]
Hey, @shyamjimishra1993.
Let me update with PMs team first.
Currently you can see that this is planned [here](https://github.com/microsoft/appcenter/issues/970)

**Comment by Jamminroot** [comment]
Extension support will be included to next release, and docs will be updated with the new release.
For now, you can check out [the PR with extension's changes](https://github.com/microsoft/appcenter-sdk-apple/pull/1787).

**Comment by Jamminroot** [comment]
I'm closing the issue. Feel free to reopen though, if there's anything else I can do for you :)

**Comment by shyamjimishra1993** [comment]
Hi @Jamminroot ,

Thanks for the information.

I am currently using the AppCenter SDK Version: 2.4.0

Could you please point me to which SDK version it will be available and estimated release date?


Thanks and regards
Shyam Ji Mishra

**Comment by Jamminroot** [comment]
As for the ETA - we should be starting new release on the third week of october.
