### ISSUE TITLE
Fetching documents withType returns incorrect document types

### ISSUE THREAD

**Issue by MikeCodesDotNET** [microsoft/appcenter-sdk-apple#1845]
### **Description**

I wish to have a mixture of types stored in App Center Data. An example of this might be that I might have ObjectA and ObjectB. These need to be available to all users so they'll be in the 'Read-Only' partition. They're both similar in that they have a few similar properties, for example, they both have:

-  **PropertyA**: String
- **PropertyB**: String

But ObjectB also contains a unique property: 

- **PropertyC**: [Int]

---
I want to fetch a list of all of the ObjectA objects. 

```
MSData.listDocuments(withType: ObjectA.self, partition: kMSDataAppDocumentsPartition, completionHandler: { documents in
            for document in documents.currentPage().items {
}
```

Reading through the documentation, it read to me like the SDK should be using the withType parameter to filter the results. In reality, It seems my understanding was wrong. 

Instead what happens is **all** the documents in the _read-only_ partition are converted with varying success to type provided for the withType parameter. This does not allow me to easily store two different data models in the same partition and easy convert them to their class. 

Initially I thought about trying to put each document type into its own partition but that doesn't seem possible with the way that partitions have been implemented. This led me to then look at including a ClassType property in my documents. I'd like to avoid this and hopefully have the SDK take responsibility for it. 

**Could you confirm if this is my stupidity or if there is a problem here?** 

### **Repro Steps**

1. Create two similar but different classes that conform to NSObject, MSSerializableDocument as per the App Center Data documentation. 
2. Put some dummy data into Cosmos for the app to download. 
3. Notice that withType doesn't appear to help. 

### **Details**

1. Which SDK version are you using?
    - 2.4.0
2. Which OS version did you experience the issue on?
    - iOS 13
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.7.5
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Simulator 
5. What language are you using?
    - [ ] Objective C
    - [X] Swift
6. What third party libraries are you using?
    - KingFisher

**Comment by annakocheshkova** [comment]
Hey @MikeCodesDotNET! It's how it currently works: the provided type is the type documents are converted to. 
What you're suggesting though is a valid use case so I'll definitely mark this as a feature request.

**Comment by MikeCodesDotNET** [comment]
Thanks for getting back to me! 

I've had a look through the code and would like to suggest the ideal fix for this, but it'll introduce a breaking change.

It'd involve adding a _**type**_ property to the MSDocumentWrapper class. This could be set through document creation by using the **_document_** object as shown below: 

` MSData.create(withDocumentID: objectA.Id, document: objectA.self,
                              partition: kMSDataUserDocumentsPartition,
                              completionHandler: { }`

Saving the document type property to the documents MSDocumentWrapper allows for easily mixing object types within either the user or app partition.

When fetching a list of objects, the **_withType_** parameter can then be used as part of a SQL query to only return the documents where the wrapper type value is equal to the withType parameter.  

Currently developers will need to pull the entire contents of a partition to device to filter the results, which not only costs in terms of Azure consumption, but it adds an unnecessary inefficiency to the process. 

---
Alternatively, it'd be very useful if it would be possible to use custom partitions, with partitions working a little like SQL tables, in that its expected a Partition will only contain just a single object type. This would help mitigate the 10GB partition limit which I've heard grumbles about. 

I don't believe this approach wouldn't require a breaking change on the SDK as the partition can be provided a string value.

**Comment by MikeCodesDotNET** [comment]
Any movement on this issue? 

Would be interested to discuss it with the stake holders as its a rather critical issue for real-world adoption of the SDK. 

Would it be better if I moved the conversation to an internal tool?

**Comment by Harrioson** [comment]
What is Microsoft OneDrive? Microsoft One drive is a place for everything (hardware)
https://www.techsovibe.com/one-drive/

**Comment by ahdbilal** [comment]
@MikeCodesDotNET Thanks for the feedback and request. This is not on our timeline and I don't see this feature being rolled out in the short to medium term. Feel free to move the conversation internally and I will be happy to provide more details on it. Thanks
