### ISSUE TITLE
Is dirty app termination detection supported ?

### ISSUE THREAD

**Issue by KD76** [microsoft/appcenter-sdk-apple#1848]
### **Description**

I'm migrating a project from HockeyApp SDK to AppCenter SDK. A previous feature, `enableAppNotTerminatingCleanlyDetection` was enabled and I can not find any equivalence in AppCenter SDK. This attribute is not described in AppCenter documentation.

I would like to know if this feature is supported, and if yes, how to enable it ?

Seems to be linked with https://github.com/microsoft/appcenter/issues/103

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install AppCenter SDK pod
2. Try to set `[MSCrashes setEnableAppNotTerminatingCleanlyDetection:YES]`, no signature found.

### **Details**

1. Which SDK version are you using?
    - 2.5.0
2. Which OS version did you experience the issue on?
    - iOS 13
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.7.1
5. What language are you using?
    - [x] Objective C
    - [x] Swift

Please note this attribute is quoted in the following header: https://github.com/microsoft/appcenter-sdk-apple/blob/b181dfabecabc6908810d7bb0264724ae72f0ba7/AppCenterCrashes/AppCenterCrashes/Model/MSErrorReport.h#L55-L75

**Comment by MatkovIvan** [comment]
Hi @KD76 ,

No, this feature is not supported yet.

Thanks for bringing our attention to this header, we'll fix this comment to avoid confusions.

Let's track the feature status in https://github.com/microsoft/appcenter/issues/103
