### ISSUE TITLE
iOS: Diagnostics and Analytics not reported when using iPhone test device.

### ISSUE THREAD

**Issue by aagarw33** [microsoft/appcenter-sdk-apple#1859]
Hello,

My App Diagnostics and Analytics are not working when using iOS device. They work when I am testing it on iOS Simulator. It is very confusing. 
I have transitioned my apps from Hockey to App Center.

After installing the released version on my test iOS device
- Analytics does not identify installation of the released version.
- After doing a force crash, crash is not reported either.

However, By using Charles I was able to confirm that device is making successful network request to App Center.

Can someone please help?

**Comment by guperrot** [comment]
Can you enable verbose logging as explained in https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/ios#adjust-the-log-level before `[MSAppCenter start...]` then share console logs having AppCenter with us?

For crash, make sure xcode debugger is not attached when crashing (we can't capture crash when xcode debugging), and please include logs from both the run that crashed and the restart run (logs are available using the Console app on Mac OS when not using XCode debugger).

**Comment by AnastasiaKubova** [comment]
We will keep communication in Intercom.
