### ISSUE TITLE
Update PLCrashReporter

### ISSUE THREAD

**Issue by Hoderu** [microsoft/appcenter-sdk-apple#1869]
Hello, in out app there were a lot of crashes caused by SIGSEGV signal in **libCrashReporter.a**
And in last update they use [set_reading(bool enable)](https://github.com/microsoft/plcrashreporter/commit/48e516013a897438a0699261ca070b0c2da72510#diff-0a4ad6df823ab782edcc93fc782331f0R859) in async_list and it solved multiple thread access problem.
Would you like to update your version of the static **libCrashReporter.a**?

**Comment by dhei** [comment]
Hi @Hoderu,

Thanks for getting in touch.

We would like to do that, but I don't have an ETA for that. We will share more information as soon as we have a plan for it.

**Comment by MatkovIvan** [comment]
Hi @Hoderu,

The commit that you are referencing was made to revert unreleased 1.3 changes (see details in https://github.com/microsoft/plcrashreporter/issues/23). App Center SDK uses version based on 1.2 and doesn't have this (before revert) change.

Related PR: #1841

**Comment by Harrioson** [comment]
Microsoft window is an operating system, 
which is needed to be loaded in a computer after purchasing it.
https://www.techsovibe.com/microsoft-windows/

**Comment by annakocheshkova** [comment]
Hi there! We have update **PLCrashReporter** in the [3.0.0 release](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/3.0.0). Please check it and reopen in case there are any issues.
