### ISSUE TITLE
Infinite Loop on "In App Updates Disabled"

### ISSUE THREAD

**Issue by tonacy** [microsoft/appcenter-sdk-apple#1871]
### **Description**

When first downloaded an app through App Center, I am lead through an infinite loop if I follow the initial pop-up. 

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. After first opening app downloaded through AppCenter, tap Continue on the pop-up that reads: "<MY-APP> Wants to Use "appcenter.ms" to Sign In"
2. After a couple of redirects, tap 'Reinstall app' on the next pop-up which reads: In-app updates disabled. This release was either side-loaded or downloaded using a browser in private mode.

Odd that the pop-up says the above, since it wasn't side-loaded or downloaded in private mode. 

3. I then receive an identical pop up to step 1. After hitting continue on that, I'm redirected to my app's page on App Center, where I can then re-install the current app. 
4. After re-installing and re-launching the app, I am presented with the same pop-up in step 1, and the process starts all over again.

1. Which SDK version are you using?
    2.1.0
2. Which OS version did you experience the issue on?
   iOS 12.3.1
3. Which Cocoapods version are you using (run `pod --version`)?
    1.7.2
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    Physical devices: iPad Pro 11" and iPod touch
5. What language are you using?
    Swift
6. What third party libraries are you using? none
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by dhei** [comment]
Hi @tonacy, 

I noticed you are on v2.1.0 of App Center Apple SDK. Could you upgrade to the latest v2.5.1 to see if you still reproduce this issue?

If you still reproduce this issue on the latest version, please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` and share the logs with us so that we can investigate.

Thank you.

**Comment by tonacy** [comment]
I was able to debug the issue with verbose logs. Turns out it was that my plist's URL types was misconfigured.

Thanks for the support!
