### ISSUE TITLE
App extension's crashes are not reported in app Center portal

### ISSUE THREAD

**Issue by shyamjimishra1993** [microsoft/appcenter-sdk-apple#1872]
Hi Team,

We are using the Notification Service app extension in our app.
Along with general app crashes, we are also interested in gathering crashes for our app extensions.

As per my last communication with AppCenter Team, The extension crash reporting is supported by AppCenter SDK 2.5.0.

I am using the SDK version 2.5.0 only, but unfortunately, I am not seeing any crash for notification extension.

Below is what I am trying-

I am starting crash reporting as follows in my extension.

[MSAppCenter start:<MyApp'sKey> withServices:@[[MSCrashes class]]];
 [MSAppCenter setLogLevel:MSLogLevelVerbose];

And then while receiving a notification, I am trying to force crash the app using force crash API provided by AppCenter.

#pragma mark - UNNotificationServiceExtension callback
- (void)didReceiveNotificationRequest:(UNNotificationRequest *)request
                   withContentHandler:(void (^)(UNNotificationContent * _Nonnull))contentHandler
{
   [MSCrashes generateTestCrash];
}

I have added the log in the above method and i could see that the "[MSCrashes generateTestCrash];" is being called but still, I don't see any crash available in the AppCenter portal.

AppCenter integration for the regular app has been done and we are able to see all the crashes for the main app. The problem is seen only for extensions. 

Could you please help me if I am doing something?
Also, please provide me any doc link which provides steps for enabling crash reporting for app extensions.

Thanks in advance.
Shyam Ji Mishra

**Comment by Jamminroot** [comment]
Hey, @shyamjimishra1993, thanks for getting in touch.

General documentation about crash reporting in extensions is here: https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios-extensions

Also, I was wondering whether you are using the same appSecret for extension, or a different appSecret (aka separate app on appcenter.ms portal)?

And, finally, having App Center verbose logs from the moment when you receive push notification would really help us troubleshoot the problem. To be able to gather verbose logs you have to call
```swift
MSAppCenter.setLogLevel(.verbose)
```
Before `MSAppCenter.start(...`

**Comment by shyamjimishra1993** [comment]
Hi @Jamminroot ,

Thanks for your support on this. 
There was a UI issue in the App Center portal due to which it was not loading all the crashes in unsymbolicated tab.

Once I deleted the browser cache, the UI issue got resolved and I could see the log there in the portal.
So the crash logs are being uploaded for notification Extension. You could close this ticket.
Many thanks for your support.

Thanks and Regards
Shyam Ji Mishra
