### ISSUE TITLE
Allow specifying UserID for crash report

### ISSUE THREAD

**Issue by hypherion2** [microsoft/appcenter-sdk-apple#1876]
The HockeyApp SDK for Mac allowed specifying a user ID to go along with the crash reports. This was very useful to us as we could correlate the crashes seen on the dashboard with users creating support tickets. 

The User ID field is currently supported by the AppCenter portal and the various crash upload API's you've made available, but not in the SDK.

The MSCrashesDelegate should allow the app to specify such a user ID with a callback similar or even as an argument of the existing attachmentsWithCrashes method.

**Comment by MatkovIvan** [comment]
Hi @hypherion2 ,

The SDK supports setting user id, please use `[MSAppCenter setUserId:@"your-user-id"]` API for that.
See our docs for details - https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/ios#identify-users

**Comment by hypherion2** [comment]
Thanks, I was only looking at the MSCrashes interface.
