### ISSUE TITLE
Support CLI/non-UI applications

### ISSUE THREAD

**Issue by sschilli** [microsoft/appcenter-sdk-apple#1878]
**Is your feature request related to a problem? Please describe.**
The instructions for initializing the SDK say to call `MSAppCenter.start` in `applicationDidFinishLaunching` of the `AppDelegate`. Obviously this does not exist for a standard CLI application, and attempting to initialize in a CLI application fails, meaning analytics features are not available in such apps.

**Describe the solution you'd like**
The ability to use AppCenter and its analytics without requiring UI/an `AppDelegate`. This way we could use analytics in a CLI application.

**Describe alternatives you've considered**
No other libraries I've found seem to support analytics with pure CLI apps either.

**Additional context**
N/A

**Comment by Jamminroot** [comment]
Hey, @sschilli, thanks for bringing this to our sight.
I'll notify our PMs team so that they can prioritize this request.

**Comment by jwallra** [comment]
Hi @sschilli - We don't officially support CLI applications at this time.  I'll leave this issue open so we can come back to this if it's something that more people want.

**Comment by Harrioson** [comment]
Microsoft’s OneDrive service gives you access to store 
your files on the cloud and retrieve them whenever you need them.
https://www.techsovibe.com/how-to-access-onedrive/

**Comment by mikewoodworth** [comment]
+1, in our case we ship a number of xpc processes that I'd like to add crash reporting to.

**Comment by kaspesla** [comment]
same. How can we get crash reports for our app's XPC processes?

**Comment by olmisa** [comment]
Hi @kaspesla ,
as described here https://github.com/microsoft/appcenter/wiki/Roadmap through mid-2021 work on new features significantly reduced. We come back to this feature request later.
Thanks

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
