### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by florianbuerger** [Microsoft/AppCenter-SDK-Apple#188]
Hi, 

any plans on adding support for Carthage?

**Comment by TroubleMakerBen** [comment]
Hey Flo,

on the list, no promises for an ETA, hopefully this year ;)

**Comment by TroubleMakerBen** [comment]
Quick update: it's on our radar but we have to postpone Carthage for now. I can't provide an ETA but believe me: it's something I really really want to do.

**Comment by scottfister** [comment]
+1 would love this

**Comment by erichoracek** [comment]
Carthage ([0.19](https://github.com/Carthage/Carthage/releases/tag/0.19.0) and above) has added support for binary downloads, by uploading a JSON file with references to the prebuilt binaries by version number e.g.:

```
binary "https://my.domain.com/release/MyFramework.json"
```

See the JSON file spec [here](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-project-specification).

Is this something that could work here?

**Comment by TroubleMakerBen** [comment]
Hi guys, because of the 0.19 release of carthage, I'm actually looking at this =) – I just got "interrupted" by other things.

Stay tuned!

**Comment by twodayslate** [comment]
Support has been added as far as I am aware. Close this?

**Comment by TroubleMakerBen** [comment]
Hey all,
@twodayslate Carthage support has been added to MC's build-feature but the SDKs cannot be integrated using Carthage at the moment.
Unfortunately, we have to delay shipping Carthage support for the SDKs to fall. We're spread a little thin right now on resources and iOS 11 is coming up faaast. It's unfortunate, as I wanted to ship this real soon, but we need to focus right now.

Please bear with us and thanks a ton for your patience.*

Benny

* We happily review and accept any PRs ;)

**Comment by twodayslate** [comment]
Ah. I was confusing Carthage support for mobile center in general. My apologies.

**Comment by 7sharp9** [comment]
Is it possible to use this repo as a carthage dependency?  I trues and only one framework was produced rather than the three required?

**Comment by TroubleMakerBen** [comment]
Hey @7sharp9,

Our SDK is currently not carthage compatible. Support/compatibility for Carthage is on the list but I still can't give you an ETA for it.

Best,
Benjamin

**Comment by 7sharp9** [comment]
@TroubleMakerBen Thanks for the reply, what work is required to make this repo carthage compatible?

**Comment by Cosmo** [comment]
I'm about to start a new project and was wondering, if this is still an open issue. 
And if so, are there any workarounds?

Thanks!

**Comment by TroubleMakerBen** [comment]
@Cosmo yes, this is still an issue that we haven't found the time to work on and I can't give you an ETA when we'll be able to add support for integration via Carthage.

@7sharp9 
Last time I looked into it – which was earlier this year and things were very much still in flux – the issue was related to the fact that the different modules, e.g. `AppCenterAnalytics` depend on the `AppCenter` module that contains the shared code which gave carthage some trouble.
Feel free to give it a shot and we'd happily accept PRs.

**Comment by Cosmo** [comment]
@TroubleMakerBen Thanks!
I found out, that adding the frameworks for AppCenter manually was quite easy. I won't automatically know when to update -- but still better than using Cocoapods :)

**Comment by andrewebling** [comment]
What's the latest on this please? Really would strongly prefer not to have to switch my project to Cocoapods - in fact I'd be more likely to not use the SDK until Carthage is supported.

**Comment by TroubleMakerBen** [comment]
It's still on our backlog but no ETA for this.

**Comment by hixfield** [comment]
+1 for getting Carthage support

**Comment by jwallra** [comment]
Closing this thread as a duplicate of one with more recent comments: https://github.com/Microsoft/AppCenter-SDK-Apple/issues/1226

Please use that issue to provide further feedback :)
