### ISSUE TITLE
App crash with MSCrashesUncaughtCXXTerminateHandler

### ISSUE THREAD

**Issue by SunnyGit** [microsoft/appcenter-sdk-apple#1882]
Description

Thread 1 Crashed:
0 libsystem_kernel.dylib 0x000000019e86febc 0x19e84b000 + 151228
1 libsystem_pthread.dylib 0x000000019e78fc20 0x19e789000 + 27680
2 libsystem_c.dylib 0x000000019e6e0844 0x19e66d000 + 473156
3 EDD 0x0000000101e22158 -[MSPLCrashReporter generateLiveReportWithThread:] + 0
4 CoreFoundation 0x000000019ea77580 0x19e94c000 + 1226112
5 libobjc.A.dylib 0x000000019e7a034c 0x19e79a000 + 25420
6 EDD 0x0000000101e1492c MSCrashesUncaughtCXXTerminateHandler() + 14862636 (MSCrashesCXXExceptionHandler.mm:163)
7 libc++abi.dylib 0x000000019e845304 0x19e837000 + 58116
8 libc++abi.dylib 0x000000019e84529c 0x19e837000 + 58012
9 libdispatch.dylib 0x000000019e7451e0 0x19e6ea000 + 373216
10 libdispatch.dylib 0x000000019e71ef3c 0x19e6ea000 + 216892
11 libdispatch.dylib 0x000000019e71e6b0 0x19e6ea000 + 214704
12 libdispatch.dylib 0x000000019e72b194 0x19e6ea000 + 266644
13 libdispatch.dylib 0x000000019e72b934 0x19e6ea000 + 268596
14 libsystem_pthread.dylib 0x000000019e794f68 0x19e789000 + 49000
15 libsystem_pthread.dylib 0x000000019e797ae4 0x19e789000 + 60132

Repro Steps

Please list the steps used to reproduce your issue.

Leave the app in idle and open it
Details

Which SDK version are you using?
2.3.0
Which OS version did you experience the issue on?
iOS-13
Which Cocoapods version are you using (run pod --version)?
1.6.1
What device version did you see this error on? Were you using an emulator or a physical device?
-iPhone 8
What language are you using?
  Objective C
  Swift
What third party libraries are you using?
Please enable verbose logging for your app using MSAppCenter.setLogLevel(.verbose) before your call to MSAppCenter.start(...) for Swift, or [MSAppCenter setLogLevel:MSLogLevelVerbose] before [MSAppCenter start: ...] for Objective C and include the logs here:

**Comment by SunnyGit** [comment]
Here is the reference of the old ticket. 

https://github.com/microsoft/appcenter-sdk-apple/issues/1867#issue-519562252

**Comment by russelarms** [comment]
I've reopened an old ticket as it has more context.
I'm closing this one as a duplicate.
