### ISSUE TITLE
Build warnings in 2.5.2

### ISSUE THREAD

**Issue by demensdeum** [microsoft/appcenter-sdk-apple#1887]
### **Description**

We migrated from HockeyApp SDK to AppCenter 2.5.1. And right now I see 300+ warnings from AppCenter SDK on GenerateDSYMFile state.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Add AppCenter SDK Libraries manually to Link Binary With Libraries group
2. Build

### **Details**

1. Which SDK version are you using?
    2.5.1
    Xcode 11.2.1 (11B53)
2. Which OS version did you experience the issue on?
    macOS 10.15.1
3. Which Cocoapods version are you using (run `pod --version`)?
    -None- manual install
4. What device version did you see this error on?  Were you using an emulator or a physical device?
   My macBook 2015
5. What language are you using?
    - [ x ] Objective C
    - [ x ] Swift
6. What third party libraries are you using?
A lot.
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
- No need -

Part of warnings:

> warning: (x86_64) /Users/runner/runners/2.159.2/work/1/s/AppCenterAuth/MSAL/microsoft-authentication-library-for-objc/MSAL/IdentityCore/IdentityCore/build/IdentityCore.build/Release-iphonesimulator/IdentityCore iOS.build/Objects-normal/x86_64/MSIDAdfsAuthorityResolver.o unable to open object file: No such file or directory
> warning: (x86_64) /Users/runner/runners/2.159.2/work/1/s/AppCenterAuth/MSAL/microsoft-authentication-library-for-objc/MSAL/IdentityCore/IdentityCore/build/IdentityCore.build/Release-iphonesimulator/IdentityCore iOS.build/Objects-normal/x86_64/MSIDAADV1IdTokenClaims.o unable to open object file: No such file or directory
> warning: (x86_64) /Users/runner/runners/2.159.2/work/1/s/AppCenterAuth/MSAL/microsoft-authentication-library-for-objc/MSAL/IdentityCore/IdentityCore/build/IdentityCore.build/Release-iphonesimulator/IdentityCore iOS.build/Objects-normal/x86_64/MSIDConfiguration.o unable to open object file: No such file or directory

**Comment by russelarms** [comment]
Hi @demensdeum, thanks for pointing this out.
I reproduced them on my local project.
We'll take a look at these warnings.

**Comment by Harrioson** [comment]
The Microsoft office account is an existing user account on Microsoft account.
https://www.techsovibe.com/microsoft-office-account/

**Comment by charmian01** [comment]
Hey!
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.

**Comment by demensdeum** [comment]
**Repro Steps**
1. Download and unpack
https://github.com/microsoft/appcenter-sdk-apple/releases/download/2.5.2/AppCenter-SDK-Apple-2.5.2.zip
2. Add to project
3. Build for simulator or device

**Details**
I see warnings
> warning: (x86_64) /Users/runner/runners/2.160.1/work/1/s/AppCenterAuth/MSAL/microsoft-authentication-library-for-objc/MSAL/build/MSAL.build/Release-iphonesimulator/MSAL (iOS Static Library).build/Objects-normal/x86_64/MSALLegacySharedAccountsProvider.o unable to open object file: No such file or directory
> warning: (x86_64) /Users/runner/runners/2.160.1/work/1/s/AppCenterAuth/MSAL/microsoft-authentication-library-for-objc/MSAL/build/MSAL.build/Release-iphonesimulator/MSAL (iOS Static Library).build/Objects-normal/x86_64/MSALExtraQueryParameters.o unable to open object file: No such file or directory
> warning: (x86_64) /Users/runner/runners/2.160.1/work/1/s/AppCenterAuth/MSAL/microsoft-authentication-library-for-objc/MSAL/build/MSAL.build/Release-iphonesimulator/MSAL (iOS Static Library).build/Objects-normal/x86_64/MSALSerializedADALCacheProvider.o unable to open object file: No such file or directory
> warning: (x86_64) /Users/runner/runners/2.160.1/work/1/s/AppCenterAuth/MSAL/microsoft-authentication-library-for-objc/MSAL/build/MSAL.build/Release-iphonesimulator/MSAL (iOS Static Library).build/Objects-normal/x86_64/MSALPublicClientApplicationConfig.o unable to open object file: No such file or directory
> warning: (x86_64) /Users/runner/runners/2.160.1/work/1/s/AppCenterAuth/MSAL/microsoft-authentication-library-for-objc/MSAL/build/MSAL.build/Release-iphonesimulator/MSAL (iOS Static Library).build/Objects-normal/x86_64/MSALLegacySharedAccount.o unable to open object file: No such file or directory
> warning: (x86_64) /Users/runner/runners/2.160.1/work/1/s/AppCenterAuth/MSAL/microsoft-authentication-library-for-objc/MSAL/build/MSAL.build/Release-iphonesimulator/MSAL (iOS Static Library).build/Objects-normal/x86_64/MSALADFSOauth2Provider.o unable to open object file: No such file or directory

**Comment by demensdeum** [comment]
@charmian01 I guess I can't reopen this issue for some reason

**Comment by annakocheshkova** [comment]
Hey, we decided to retire the App Center Auth service, so in the new version of the sdk you will not see this error. You can read more about it [here](https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/).
