### ISSUE TITLE
Only able to see the test Crash in App Center portal 

### ISSUE THREAD

**Issue by ankur7hcl** [microsoft/appcenter-sdk-apple#1893]
Hi,

I recently integrated the App center SDK in my project.

On App launch, I am doing.
 MSAppCenter.start("SecretKey", withServices:[
            MSAnalytics.self,
            MSCrashes.self
        ])

Its working fine with default code : MSCrashes.generateTestCrash()

However crash is not reported on App Center when we crash the app other than default test crash

Which SDK version are you using?
2.5.1
Which OS version did you experience the issue on?
iOS 13.1
Which Cocoapods version are you using (run pod --version)?
1.6.1
What device version did you see this error on? Were you using an emulator or a physical device?
Both
What language are you using?
Swift
What third party libraries are you using?
NA
Please enable verbose logging for your app using MSAppCenter.setLogLevel(.verbose) before your call to MSAppCenter.start(...) for Swift, or [MSAppCenter setLogLevel:MSLogLevelVerbose] before [MSAppCenter start: ...] for Objective C and include the logs here:
	[AppCenter] VERBOSE: -[MSAppCenter startServices:withAppSecret:transmissionTargetToken:fromApplication:]/318 Start services MSCrashes, MSAnalytics from an application
	[AppCenterCrashes] DEBUG: -[MSCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/624 EnableUncaughtExceptionHandler is set to YES
	[AppCenterCrashes] VERBOSE: -[MSCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/634 Enabled Mach exception handler.
		[AppCenterCrashes] DEBUG: -[MSCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/666 Exception handler successfully initialized.
		[AppCenterCrashes] INFO: -[MSCrashes applyEnabledState:]/375 Crashes service has been enabled.
		[AppCenterCrashes] VERBOSE: -[MSCrashes startWithChannelGroup:appSecret:transmissionTargetToken:fromApplication:]/420 Started crash service.
		[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/497 Storing a log to Crashes Buffer: (sid: 848E3267-13B9-4F68-94A2-2E05A03EC023, type: startSession)
		[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/508 Found an empty buffer position.
	[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/497 Storing a log to Crashes Buffer: (sid: (null), type: startService)	[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/520 Remembering index 0 for oldest timestamp 1574854871.531897.
	[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/508 Found an empty buffer position.
	[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didCompleteEnqueueingLog:internalId:]/550 Deleting a log from buffer with id B60A20E3-2D9D-4F71-BE99-9ED32E323EE3
	[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didCompleteEnqueueingLog:internalId:]/550 Deleting a log from buffer with id 3E18BEDD-DDD0-437D-995A-23EAC21F64A4
	[AppCenter] DEBUG: -[MSChannelUnitDefault sendLogContainer:withAuthTokenFromArray:atIndex:]/224 Sending 1/1 log, group Id: AppCenter, batch Id: 0E6B0111-EBFC-41EF-BC1F-AE336FB857C4, session Id: (null), payload:
{
  "device" : {
    "screenSize" : "2732x2048",
    "appBuild" : "5",
    "osName" : "iOS",
    "timeZoneOffset" : 330,
    "carrierCountry" : "us",
    "osVersion" : "13.1",
    "carrierName" : "iPad",
    "locale" : "en_IN",
    "appNamespace" : "com.app.ios”,
    "osBuild" : "17A5821e",
    "sdkName" : "appcenter.ios",
    "oemName" : "Apple",
    "model" : "iPad7,2",
    "sdkVersion" : "2.5.1",
    "appVersion" : "6.9.12"
  },
  "timestamp" : "2019-11-27T11:41:11.532Z",
  "type" : "startService",
  "services" : [
    "Crashes",
    "Analytics"
  ]
}

**Comment by MatkovIvan** [comment]
Hi @ankur7hcl ,

> when we crash the app other than default test crash

Could you please specify exact repro steps? What crash isn't reported?

**Comment by ankur7hcl** [comment]
Hi Matkovlavn 
Hope you are doing well, By crashes, i mean the crashes which we are doing in our code at run time but that are not reported/Visible in AppCenter

**Comment by MatkovIvan** [comment]
@ankur7hcl yes, that's clear. I'm asking about exact crashes because it's not clear what crash exactly doesn't work. It has been tested with various crashes like memory corruption, stackoverflow, exceptions, signals (SIGBUS, SIGILL, SIGSEGV, ...), etc.
Please share the crash details that wasn't reported and full device log (usually it has much more lines that the one above)

**Comment by ankur7hcl** [comment]
Hi Matkovlavn

i have able to view the crash (indexoutofrange). The crash which is not getting reported is : 

* Assertion failure in -[.TestCollectionView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3899.13.13/UICollectionView.m:5824

Attaching the log file also 


[logs.zip](https://github.com/microsoft/appcenter-sdk-apple/files/3904077/logs.zip)

**Comment by MatkovIvan** [comment]
I managed to crash the app with exact same assert, but it's reported well:
![image](https://user-images.githubusercontent.com/1836384/69874038-13ea3a80-12cb-11ea-9b95-0b3f270111bc.png)

Probably it's some setup issue. Does it reproduced in empty project? If so, could you please share this reproduction sample?

Also please note that the SDK will not forward any crash log if you are attached to the debugger. Make sure the debugger is not attached when you crash the app.

PS related troubleshooting doc: 
https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/ios#crashes-dont-show-up-in-the-portal

**Comment by annakocheshkova** [comment]
Hi @ankur7hcl we haven't heard from you in a while. If you have any more updates, feel free to re-open this issue. Thanks!
