### ISSUE TITLE
Country data not captured by SDK

### ISSUE THREAD

**Issue by vineetchoudhary** [Microsoft/AppCenter-SDK-Apple#190]
I've 6 session on two different device but country data not available on Mobile Center Portal.

![screen shot 2016-11-24 at 5 39 34 pm](https://cloud.githubusercontent.com/assets/8479436/20598074/51d00ec2-b26d-11e6-8355-d180c541f143.png)

**Comment by guperrot** [comment]
Hi, country is currently available only on mobile device with a carrier. For wifi only devices the country is not yet supported.

**Comment by vineetchoudhary** [comment]
Thanks for the information.

**Comment by tonyarnold** [comment]
Are there plans to add support for WiFi only devices, such as Macs? This is a dealbreaker for our use of the analytics.

**Comment by elamalani** [comment]
@tonyarnol As of now, we don't plan to support "Country" for WiFi only devices. This might change in the future, I will keep this issue open for visibility and we will let you know once we decide to support it.

**Comment by tonyarnold** [comment]
Ok, thanks for the update. I'll look for another analytics solution.

**Comment by tonyarnold** [comment]
If I started to poke our own country data at the API sourced through our own means, would it show up in the analytics dashboard for a macOS app?

**Comment by tonyarnold** [comment]
Actually, further to this - would you accept a PR that allowed consumers of the library (such as myself)  to add their own `carrierCountry` data for presentation?

**Comment by dhei** [comment]
Hey @tonyarnold,

Absolutely, we welcome PR on this. 

Note that we've already provide this API `SetCountryCode(string countryCode)` on App Center DotNet SDK at https://github.com/Microsoft/AppCenter-SDK-DotNet/blob/master/SDK/AppCenter/Microsoft.AppCenter.UWP/AppCenterPart.cs#L14-L26. 

You may add a similar API to `MSAppCenter` so that it can be called like this:
```objective-c
[MSAppCenter setCountryCode:countryCode]
```

**Comment by tonyarnold** [comment]
Excellent, thanks for the confirmation @dhei. I'll have a look at this early next week!
