### ISSUE TITLE
Cocoapod issue with Azure Pipelines builds

### ISSUE THREAD

**Issue by anabayan** [microsoft/appcenter-sdk-apple#1918]
### **Description**

Hi, I'm trying to build my iOS app in DevOps pipeline that uses AppCenter. The npm package that I use, uses cocoapods to download the latest appcenter-apple sdk.
But the build fails because according to cocoapods the latest release is 2.5.2 which returns a not found error in github : https://github.com/microsoft/appcenter-sdk-apple/releases/download/2.5.2/AppCenter-SDK-Apple-2.5.2.zip

he same link for 2.5.1 returns the zip download just fine. But our builds are stuck until 2.5.2 zip gets updated or the cocoapod for appcenter-apple-sdk points to 2.5.1?

### **Details**

Installing pods...
Analyzing dependencies
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
Downloading dependencies
Installing AppCenter (2.5.2)

[!] Error installing AppCenter
[!] /usr/local/opt/curl/bin/curl -f -L -o /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20191212-745-8lvlvi/file.zip https://github.com/microsoft/appcenter-sdk-apple/releases/download/2.5.2/AppCenter-SDK-Apple-2.5.2.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

**Comment by barrcodes** [comment]
Same issue. Was working earlier today. Looks like release 2.5.2 was archived?
https://github.com/microsoft/appcenter-sdk-apple/releases/

I'm going to rollback to 2.5.1 for the time being.

**Comment by MysterDru** [comment]
same issue, this worked about an hour ago and suddenly stopped working.

**Comment by anabayan** [comment]
Yes. It worked for me earlier today as well. Stopped working now.

**Comment by Poncholay** [comment]
Stopped working, tried rolling back to 2.5.1 but it doesn't work either

**Comment by barrcodes** [comment]
I'd be very surprised if rolling back didn't work. However, my issue is that I'm building an app with capacitor cli, and `npx cap sync` is nuking any rollback I try to do manually.

If anyone has my specific ionic / capacitor issue, you can follow along here:
https://github.com/ionic-team/capacitor/issues/2242

**Comment by MatkovIvan** [comment]
Hi there,

We've found a critical issue in that release, so we had to remove this binary from GitHub releases page. We're working on a hotfix now, please use 2.5.1 before hotfix release.

Sorry for the inconvenience.

**Comment by anabayan** [comment]
Hi Matkovlvan,

Thank you! Is it possible to revert the CocoaPods version to 2.5.1 as well? CocoaPods currently shows version 2.5.2.

The package I am dependent on uses the latest CocoaPod version and I'm unable to change that.

**Comment by barrcodes** [comment]
For most iOS users, just rollback your podfile or podspec versions to 2.5.1 explicitly instead of >=2.5.0 or ~>2.5.0

For anyone with my ionic / cordova / capacitor issue, you need to:

Track your podfiles in git (git diff):
```
-# Cordova plugins for Capacitor
-capacitor-cordova-ios-plugins
-
+!App/Podfile.lock
+capacitor-cordova-ios-plugins/*
+!capacitor-cordova-ios-plugins/CordovaPlugins.podspec
+!capacitor-cordova-ios-plugins/CordovaPluginsResources.podspec
+!capacitor-cordova-ios-plugins/CordovaPluginsStatic.podspec
```

Use `npx cap sync --deployment` in your build script per [ionic/capacitor#222](https://github.com/ionic-team/capacitor/pull/2222) and [ionic/capacitor#2200](https://github.com/ionic-team/capacitor/issues/2200)

**Comment by barrcodes** [comment]
I don't think anyone is planning to, but please don't close this issue until the hotfix is released so we can revert our podfile to ~>2.5.0

**Comment by anabayan** [comment]
Thank you All. The CocoaPod version has been reverted to 2.5.1. That enables me to continue with our automated builds.

**Comment by MatkovIvan** [comment]
@anabayan yes, that version was deleted from pods.

"latest" rule should work now

**Comment by MatkovIvan** [comment]
App Center SDK 2.5.3 with the hotfix has been released.

**Comment by barrcodes** [comment]
`pod update --repo-update --project-directory=[path/to/Podfile]`

**Comment by jeanlambert17** [comment]
Is this issue somehow related? 

`
##[error]The process '/usr/local/lib/ruby/gems/2.6.0/bin/pod' failed with exit code 1
##[error]The 'pod' command failed with error: The process '/usr/local/lib/ruby/gems/2.6.0/bin/pod' failed with exit code 1
`

**Comment by lernamanto** [comment]
I got exactly the same error, worked fine then suddenly same error as jeanlambert17

**Comment by Jamminroot** [comment]
Not sure which exactly problem you are facing (can't see any messages posted by jeanlambert17 in this thread), can you elaborate?

**Comment by lernamanto** [comment]
LOL
I swear the message was there yesterday 😂

Anyway basically I've got a pipeline with a pod install task, and it was working fine until suddenly, without any change to the code, this happened:

![error](https://user-images.githubusercontent.com/4980901/93997117-f0790a80-fd8a-11ea-8390-efffa8d972cf.png)

the message from jeanlambert17 had the exact same error...

**Comment by MatkovIvan** [comment]
@lernamanto this is probably related to https://github.com/CocoaPods/CocoaPods/issues/10078

**Comment by lernamanto** [comment]
@MatkovIvan yep, that's seems exactly it, thank you for pointing this out 🙂
Cheers
