### ISSUE TITLE
macOS frameworks are broken in release archives

### ISSUE THREAD

**Issue by antons** [microsoft/appcenter-sdk-apple#1925]
### **Description**

macOS frameworks are broken in release archives: files and directories are copied instead of being symlinked.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Download an archive from Releases page.
2. Attempt to integrate it into a macOS app.
3. Xcode will be unable to sign the frameworks, because their structure is broken. Top-level folders must be symlinked, instead they’re copied. 

### **Screenshots**

Directory structure when frameworks are built from source:

<img width="219" alt="Screen Shot 2019-12-16 at 15 54 57" src="https://user-images.githubusercontent.com/129705/70912402-89207400-201c-11ea-9132-00b3a8df72ca.png">

Directory structure from the release archives:

<img width="214" alt="Screen Shot 2019-12-16 at 15 54 51" src="https://user-images.githubusercontent.com/129705/70912475-b2410480-201c-11ea-8ce6-8f94e11386d4.png">

**Comment by Jamminroot** [comment]
Hey, @antons, that seems to be related to [this issue](https://github.com/microsoft/appcenter/issues/1296).
We have a backlog item for dynamic framework linking, but there aren't any ETAs I can provide yet.

**Comment by Jamminroot** [comment]
I'm closing this issue. Follow the issue I've linked in previous message for updates.

**Comment by antons** [comment]
Thank you for the info.
