### ISSUE TITLE
AppCenter SDK fails to successfully upload crash reports when device's time is 'in future'

### ISSUE THREAD

**Issue by Lievesley** [microsoft/appcenter-sdk-apple#1989]
### **Description**

AppCenter SDK fails to upload crash reports on an iPhone 11 Pro Max. However, it does work on an iPhone 6s+.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a test app that generates a crash with crash reporting enabled
2. Deploy on a iPhone 11 Pro Max

### **Details**

1. Which SDK version are you using?
    3.0.0

2. Which OS version did you experience the issue on?
    iOS 13.3.1

3. Which Cocoapods version are you using (run `pod --version`)?
    1.7.4

4. What device version did you see this error on?  Were you using an emulator or a physical device?
    iPhone 11 Pro Max

5. What language are you using?
    Objective C

6. What third party libraries are you using?
    None, just created a test app

7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

[iPhone11ProMax-failed-to-send-crash-report.txt](https://github.com/microsoft/appcenter-sdk-apple/files/4249931/iPhone11ProMax-failed-to-send-crash-report.txt)

**Comment by Jamminroot** [comment]
Hello, thanks for bringing this to our sight.
Can It be reproduced on a clean project?
Also, can you share a small code snippet with implementation?

**Comment by Jamminroot** [comment]
The issue seem to be with the device date\time - logs older than 25 days in past and 3 days 'in future' are discarded. This is what backend notified you about; You can see it in your logs:
```
2020-03-05 13:01:43.990926+0100 TestAppCenter[5785:6174277] [AppCenter] VERBOSE: -[MSHttpIngestion printResponse:body:error:]/217 HTTP response received with status code: 400, payload:
{
  "status" : "NoValidLogsFoundInLogContainer",
```
And the timestamp is in future.
I'm closing the issue, but feel free to reopen it, face you the problem again.

**Comment by Lievesley** [comment]
This issue doesn't have anything todo with the time setting on the device. If the backend rejected crash reports because the time was incorrect on the device that would not be acceptable either since we still would want to know about those crashes as well.

I have repeated the same test with an iPhone 6S+ with the time in the future and its able to send the crash reports just fine. Please see attached log.

[iPhone6S+sent-crash-report.txt](https://github.com/microsoft/appcenter-sdk-apple/files/4254850/iPhone6S%2Bsent-crash-report.txt)

**Comment by Jamminroot** [comment]
Ok, I'll reopen the issue and let our PMs look at it.

**Comment by russelarms** [comment]
I renamed the issue as it is related to the device's time, not to the iPhone model.
>This issue doesn't have anything todo with the time setting on the device.

From the logs: `Discarded a log older than 25 days or more than 3 in the future`

**Comment by Jamminroot** [comment]
We don't plan to change those limitations, instead we are going to document those changes. I'm closing this issue.
