### ISSUE TITLE
Please reopen AppCenter SDK fails to successfully upload crash reports on iPhone 11 Pro Max #1989

### ISSUE THREAD

**Issue by Lievesley** [microsoft/appcenter-sdk-apple#1991]
I'm not able to re-open a bug report that was closed with my permissions:

AppCenter SDK fails to successfully upload crash reports on iPhone 11 Pro Max #1989

Please take a look at my last comment and reopen the ticket.

**Comment by Jamminroot** [comment]
I've reopened initial issue; Closing this as duplicate.
