### ISSUE TITLE
Add `MSCrashes.hasCrashed` property

### ISSUE THREAD

**Issue by sindresorhus** [microsoft/appcenter-sdk-apple#2005]
**Is your feature request related to a problem? Please describe.**

I would like to ensure that I don't show a App Store review prompt in my app if my app has ever crashed for the user, so not to encourage users to show their frustration in a App Store review, because reviews are not a (fully) two-way communication, so it's harder to debug issues that way. I have a separate feedback button for bugs.

**Describe the solution you'd like**

I imagine it could be a simple `MSCrashes.hasCrashed` property that is true if the app has ever crashed.

There's `MSCrashes.hasCrashedInLastSession()`, but it only applies to the last session. The review prompt might be displayed some sessions after the crash.

**Describe alternatives you've considered**

I could manually track this myself, but it would be much easier if AppCenter provided this property.

**Additional context**

N/A

**Comment by annakocheshkova** [comment]
Hi there, thank you for the feature request, we will track it.
In the meantime, may I ask why it's so important to have this in the SDK?
While we track all the feature requests, the backlog is pretty large, so I can't give any ETA's on when this is going to be addressed.

To unblock the development, much easier in your case would be to just create an extension, for example like this:

**MSCrashesExtension.swift**
```
import AppCenterCrashes

extension MSCrashes {
    static func hasCrashed() -> Bool {
        var hasCrashed = UserDefaults.standard.bool(forKey: "hasCrashed")
        if !hasCrashed && MSCrashes.hasCrashedInLastSession() {
            hasCrashed = true
            UserDefaults.standard.set(hasCrashed, forKey: "hasCrashed")
        }
        return hasCrashed
    }
}
```

**Comment by sindresorhus** [comment]
I have something like that already in my codebase. I just thought it would be nice if AppCenter could provide it, since it seems like something that could be useful to many users.

**Comment by DmitriyKirakosyan** [comment]
Hi @sindresorhus , I'm going to close this feature request since the described case is very specific and we haven't had similar feature requests. Moreover, you can implement this behaviour using the [workaround](https://github.com/microsoft/appcenter-sdk-apple/issues/2005#issuecomment-597507145).
