### ISSUE TITLE
MSCrashesUncaughtCXXTerminateHandler Crash

### ISSUE THREAD

**Issue by sivasankar519** [microsoft/appcenter-sdk-apple#2015]
Description

libsystem_kernel.dylib
__pthread_kill
libsystem_c.dylib
abort
libc++abi.dylib
abort_message
libc++abi.dylib
demangling_terminate_handler()
libobjc.A.dylib
_objc_terminate()
xXx
MSCrashesUncaughtCXXTerminateHandler() MSCrashesCXXExceptionHandler.mm:160
libc++abi.dylib
std::__terminate(void (*)())
libc++abi.dylib
std::terminate()
libdispatch.dylib
_dispatch_client_callout
libdispatch.dylib
_dispatch_main_queue_callback_4CF
CoreFoundation
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
CoreFoundation
__CFRunLoopRun
CoreFoundation
CFRunLoopRunSpecific
GraphicsServices
GSEventRunModal
UIKitCore
UIApplicationMain
Xxx
main main.swift:15
libdyld.dylib
start

Repro Steps

Please list the steps used to reproduce your issue.

Crash on app start up

Which SDK version are you using?
2.5.*
Which OS version did you experience the issue on?
iOS-13 and above 
Which Cocoapods version are you using (run pod --version)?
1.7.5
What device version did you see this error on? Were you using an emulator or a physical device?
-all devices
What language are you using?
Swift

**Comment by AnastasiaKubova** [comment]
Hi, @sivasankar519 ! Thanks for getting in touch with us!
Could you please update App Center to the last [version](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/3.1.0) and try to reproduce this issue and let me know about the results. Also, have you a chance to enable [verbose]( https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/ios#adjust-the-log-level?) logging and provide output logs?

**Comment by russelarms** [comment]
We haven't heard from you in a while and provided information isn't enough for the future investigation, so I'm closing this issue. Please reopen/comment if you have more details or have any other questions.
Thanks.
