### ISSUE TITLE
No more analytics with HockeySDK

### ISSUE THREAD

**Issue by juliensechaud** [microsoft/appcenter-sdk-apple#2016]
### **Description**

We do not have any more analytics in AppCenter since yesterday

### **Repro Steps**

Use HockeySDK

### **Details**

1. Which SDK version are you using?
    - HockeySDK
2. Which OS version did you experience the issue on?
    - ALL
3. Which Cocoapods version are you using (run `pod --version`)?
    - NC
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - ALL
5. What language are you using?
    - [ ] Swift
6. What third party libraries are you using?
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by dhei** [comment]
Hey @juliensechaud,

Thanks for getting in touch. 

Can you share with us your application url, like the `https://appcenter.ms/orgs/{orgname}/apps/{appname}` format?

**Comment by dhei** [comment]
Hey @juliensechaud,

Sorry for the inconvenience.
The problem should be fixed by now. Please give it a try and let us know if it is still not working.

**Comment by juliensechaud** [comment]
Hey @dhei,

Everything returned to normal. Thanks
Just to know. What happened ? And do we have a final date to migrate from Hockey to AppCenter ?

Thanks again

**Comment by lumaxis** [comment]
@juliensechaud This was due to a DNS configuration issue that has since been fixed and we're taking steps to prevent similar issues from happening again.

The HockeyApp service has been shut down in February. We're keeping the APIs functional for backwards compatibility for a while but recommend customers to upgrade to the App Center SDKs as soon as they can.

**Comment by dhei** [comment]
Closing as the issue has been resolved.
