### ISSUE TITLE
sqlite3 dependency breaks SQLCipher

### ISSUE THREAD

**Issue by anivaros** [microsoft/appcenter-sdk-apple#2024]
### **Description**

sqlite3 dependency forces to use system sqlite3 lib instead of sqcipher.

### **Repro Steps**

1. Add pod 'SQLCipher' and pod 'AppCenter'
2. Try to encrypt DB

### **Details**

https://www.zetetic.net/sqlcipher/ios-tutorial/ says:
> If libsqlite3.dylib or another SQLite framework is listed in your Link Binary With Libraries list be sure to remove it!

**Comment by MatkovIvan** [comment]
Hi @anivaros ,

App Center SDK is distributed as static framework and can be linked with non-system SQLite library that you choose. However, CocoaPods distribution requires specify all dependencies of SDK including the SQLite one.
If you want to use custom SQLite library you can integrate App Center SDK **not** via CocoaPods or manually edit linker option in generated Pods project.

**Comment by anivaros** [comment]
Hi @MatkovIvan! 
With first variant I'll loose ability to keep framework up to date, second - will break CI process.
For workaround I forked project and fixed podspec, but it would be nice to have more native variant, like additional subspec without sqlite, or something like that.

**Comment by MatkovIvan** [comment]
Glad you resolved this problem. I'm closing this issue for now, let's see if we'll have more requests for it.
