### ISSUE TITLE
Error: no such module 'AppCenter'

### ISSUE THREAD

**Issue by yoojinTab** [microsoft/appcenter-sdk-apple#2044]
### **Description**

Please forgive me, as I don't use Carthage a lot. 

I really appreciate the work you're doing with this.

Our CI server periodically experiences the following error:
`no such module 'AppCenter'`

When this happened we would clear the following cache directories and rerun the build and it seemed to `fix` things:
~/Library/Caches/org.carthage.CarthageKit
~/Library/Caches/Rome
./DerivedData
./Carthage

However, today it didn't seem to help.

One thing I noticed is the cached file:
`~/Library/Caches/org.carthage.CarthageKit/binaries/appcenter-sdk-apple/2.5.1/ID<Asset>(rawValue: 16011777)-AppCenter-SDK-Apple-2.5.1.carthage.framework.zip`

has the following folder structure:
`AppCenter-SDK-Apple/iOS`

Other Carthage libs we use have the following folder:
`Carthage/Build/iOS`

So I re-archived AppCenter-SDK-Apple-2.5.1.carthage.framework.zip with the folder structure:
Carthage/Build/iOS

and ran the steps below with success.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. carthage bootstrap --platform iOS --cache-builds

2. xcodebuild -showBuildSettings -workspace ./xxx.xcworkspace -scheme xxx

Note:
`./Carthage/Build/iOS` does not show any of the AppCenter frameworks.

3. error: `no such module 'AppCenter'`

### **Details**

1. Which SDK version are you using?
2.5.1

2. carthage version: 
0.34.0

3. What language are you using?
    - [ x] Objective C
    - [ x] Swift

4. MacOS Mojave 10.14.6

5. Framework Search Paths:
```
$(inherited)
$(PROJECT_DIR)/Carthage/Build/iOS
$(PROJECT_DIR)
```

**Comment by AnastasiaKubova** [comment]
Hi, @yoojinTab ! Thanks for getting in touch with us!
Please try to add definition in the Framework Search Paths a path to a folder that contains the frameworks with App Center.

**Comment by yoojinTab** [comment]
Framework Search Paths:
```
$(inherited)
$(PROJECT_DIR)/Carthage/Build/iOS
$(PROJECT_DIR)
```

btw. Not sure if the following is helpful or not
1. None of our other Carthage frameworks such as RxSwift have this issue
.
2. That day I saw in one of the build logs the following error, other builds that failed didn't have this error:

```
*** Skipped downloading appcenter-sdk-apple.framework binary due to the error:
[13:47:12]: ▸ "API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"
```

3. We also use Rome, but I tried building manually with and without Rome from the CI server
I cleared the local DerivedData and Carthage directories each time.

**Comment by AnastasiaKubova** [comment]
@yoojinTab, thanks for clarification! I tried to test it on an empty project and App Center was added to `./Carthage/Build/iOS` as is expected.
Could you please confirm that you follow this [guide](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios#32-integration-via-carthage) about adding App Center via Carthage?

**Comment by AnastasiaKubova** [comment]
We haven't heard from you in a while so I'm closing this issue.
Feel free to reopen this issue if it isn't resolved or you have additional questions.
