### ISSUE TITLE
App Center does not link CoreTelephony when targeting Mac Catalyst platform

### ISSUE THREAD

**Issue by a2** [microsoft/appcenter-sdk-apple#2054]
### **Description**

I was unable to successfully build a Mac Catalyst app using AppCenterCrashes until I manually linked against the CoreTelephony framework.

CoreTelephony is automatically linked but only when the platform is iOS (see [`Package.swift`](https://github.com/microsoft/appcenter-sdk-apple/blob/b881be9a20851dcd9002d4413fc3f9d3e9a60a26/Package.swift#L48)).

### **Repro Steps**

1. Add the App Center SDK to a project using SPM.
2. Try to compile a Mac Catalyst project.

**Expected result:**

It should compile because all relevant dependencies are listed in the `Package.swift` file.

**Observed result:**

The project doesn't compile until CoreTelephony is linked manually for Mac.

### **Details**

1. Which SDK version are you using?

b881be9a20851dcd9002d4413fc3f9d3e9a60a26 with https://github.com/microsoft/plcrashreporter/pull/77/commits/d8ee7c02c0b735cf2f6262ac5787d80365e61244

2. Which OS version did you experience the issue on?

N/A, build error.

3. Which CocoaPods version are you using (run `pod --version`)?

N/A, using SPM.

4. What device version did you see this error on?  Were you using an emulator or a physical device?

N/A, build error.

5. What language are you using?
    - [ ] Objective C
    - [x] Swift

6. What third party libraries are you using?

None

7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

N/A, build error.

**Comment by russelarms** [comment]
Hi @a2, thanks for reaching out!
We don't officially support Mac Catalyst yet, but it's in our [Iteration Plan for May 2020](https://github.com/microsoft/appcenter/issues/1837).

**Comment by a2** [comment]
@russelarms Hi Ruslan, yeah I noticed that but I just wanted to post this as a heads up :)

**Comment by MatkovIvan** [comment]
@a2 linking `CoreTelephony` is not only one thing that required to support Mac Catalyst. As @russelarms mentioned above, the SDK does not support it yet. Please wait a bit to use it, this won't work correctly at the current state.

Let's monitor status of it in the feature request thread - https://github.com/microsoft/appcenter/issues/1578
