### ISSUE TITLE
Application hangs on crash

### ISSUE THREAD

**Issue by blork** [microsoft/appcenter-sdk-apple#2082]
# **Description**

I am testing the AppCenter SDK in my application. I am encountering an issue that, when the SDK is started and a crash occurs, the application does not exist to Springboard as expected, but instead the application becomes unresponsive and seems to consume 100% of CPU, both on the Simulator and on a real device. I have left the app for upwards of 5 minutes and nothing happens.

iOS remains responsive, and I can swipe the app away from multitasking. When I start the app again, no crash is uploaded to App Center.

If I remove the call to `MSAppCenter.start(...)`, then the app crashes to springboard as expected.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Initialise the AppCenter SDK:

```
 MSAppCenter.start("<my-secret>", withServices: [
    MSAnalytics.self,
    MSCrashes.self
])
```

2. Crash the application on button tap:
```
override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    var test: String? = nil
    print(test!)
}
```

3. Observe that the app has become unresponsive.

### **Details**

1. Which SDK version are you using?
    - 3.2.0
2. Which OS version did you experience the issue on?
    - iOS 13
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.9.1
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone X physical device, iPhone 11 emulator
5. What language are you using?
    - [x] Swift
    - [x] Objective-C
It is a mixed-source project but the calls to the SDK are made in Swift.
6. What third party libraries are you using?
```
pod 'KZPropertyMapper'
pod 'ReachabilitySwift'
pod 'BugfenderSDK'
pod 'AppCenter'
```
Bugfender is used but its automatic crash logging is disabled to prevent conflicts with AppCenter.

7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

I am unable to capture these logs because I am running without the debugger attached.

**Comment by olmisa** [comment]
Hello @blork ,
I was not able to reproduce this issue. 
Please, share the logs if possible, collect them from Xcode, for example (uncheck 'Debug executable' in the scheme). 
Also, AppCenter doesn't support work with other Crash frameworks. Is it possible to remove 'BugfenderSDK' from the project and after that reproduce the issue? 
Thanks

**Comment by blork** [comment]
I didn't know that tip about unblocking debug executable. Handy!
Here's what happens - I get the following lines repeated over and over, constantly being printed to the log. There's some type on infinite loop happening.

```
[PLCrashReport] plcrash_write_report:159: Could not open the crashlog output file: No such file or directory
[PLCrashReport] mach_exception_callback:297: Failed to write live report: 6
```

I get this even when removing the Bugfender SDK.

**Comment by olmisa** [comment]
Thanks, as I understand, the folder where the report should be saved is not exist.
We are looking at the problem. 
Is it possible to share the sample project with the reproduction code? I am still not able to reproduce the issue.
Thanks.

**Comment by blork** [comment]
Unfortunately I cannot share my project with you. I will attempt to create a sample that reproduces the issue.

Looking at the app's documents directory (simulator), this is what I see inside the `com.microsoft.appcenter ` folder:

```
samoakley@Sams-MBP com.microsoft.appcenter % pwd     
/Users/samoakley/Library/Developer/CoreSimulator/Devices/6109BADD-6768-49F9-8514-34786734FA4E/data/Containers/Data/Application/8F695312-9EE4-45F3-BC41-9CB32A215289/Library/Application Support/com.microsoft.appcenter
samoakley@Sams-MBP com.microsoft.appcenter % ls -lhSR
total 40
-rw-r--r--   1 samoakley  staff    20K 28 May 13:54 Logs.sqlite
drwxr-xr-x@ 63 samoakley  staff   2.0K 28 May 13:54 crasheslogbuffer
drwxr-xr-x@  2 samoakley  staff    64B 28 May 09:33 crashes

./crasheslogbuffer:
total 0
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 0.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 1.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 10.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 11.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 12.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 13.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 14.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 15.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 16.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 17.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 18.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 19.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 2.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 20.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 21.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 22.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 23.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 24.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 25.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 26.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 27.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 28.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 29.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 3.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 30.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 31.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 32.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 33.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 34.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 35.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 36.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 37.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 38.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 39.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 4.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 40.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 41.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 42.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 43.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 44.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 45.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 46.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 47.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 48.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 49.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 5.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 50.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 51.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 52.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 53.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 54.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 55.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 56.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 57.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 58.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 59.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 6.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 7.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 8.mscrasheslogbuffer
-rw-r--r--  1 samoakley  staff     0B 28 May 13:54 9.mscrasheslogbuffer

./crashes:
```
Is it expected that there are so many 0 byte `mscrasheslogbuffer` files?

**Comment by MatkovIvan** [comment]
> Is it expected that there are so many 0 byte mscrasheslogbuffer files?

Yes. It's used in case of crash to snapshot analytics data that is not written to sqlite yet. Corner case.

**Comment by blork** [comment]
I have discovered the cause of the issue.

The application I am adding this to has a method that runs on application launch which moves files from the app's cache's directory into a more suitable place (upgrade path stuff). This function was also moving the folder `com.plausiblelabs.crashreporter.data`, as it had not been excluded. 

My bad! This explains why crashes would not be uploaded, as this directory would be created and then on the next launch after a crash it would be immediately moved. 

But this code only does something on launch, and only if the dir exists. The dir doesn't exist on first launch (it seems to be created when the app launches again), and the code doesn't run on crash, so why does the library fail to create the directory when this code is there?

**Comment by annakocheshkova** [comment]
Hi @blork! What you mean is on the first start in an empty app, when the app crashes and the abovementioned method has not yet been executed, the app still hangs right? Are the error messages you get from the Console the same in this case?

**Comment by blork** [comment]
The method is executed but doesn't actually touch the AppCenter folder because it doesn't exist yet. It loops though the caches dir and moves anything it finds, but since the app hasn't crashed yet the `com.plausiblelabs.crashreporter.data` folder doesn't exist. It's very strange.

Anyway I'm happy to close this now since it's clear it's my own fault for messing with cache directories that don't belong to me (😅) and excluding the folder fixes the issue.
