### ISSUE TITLE
XCFramework download does not preserve symlinks

### ISSUE THREAD

**Issue by tbartelmess** [microsoft/appcenter-sdk-apple#2083]
### **Description**

The `XCFramework` download has duplicate resources rather than symlinks.

When downloading the current release as XCFramework from https://github.com/microsoft/appcenter-sdk-apple/releases/download/3.2.0/AppCenter-SDK-Apple-XCFramework-3.2.0.zip
the extracted `.zip` the archive does not symlinks inside the framework to point to the current version.

E.g. `AppCenter-SDK-Apple-xc/AppCenter.xcframework/macos-x86_64/AppCenter.framework/AppCenter` should be a symlink to `AppCenter-SDK-Apple-xc/AppCenter.xcframework/macos-x86_64/AppCenter.framework/Versions/A/AppCenter`
and 
`AppCenter-SDK-Apple-xc/AppCenter.xcframework/macos-x86_64/AppCenter.framework/Versions/Current/AppCenter`
should be a symlink to `AppCenter-SDK-Apple-xc/AppCenter.xcframework/macos-x86_64/AppCenter.framework/Versions/A/AppCenter`

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Download `https://github.com/microsoft/appcenter-sdk-apple/releases/download/3.2.0/AppCenter-SDK-Apple-XCFramework-3.2.0.zip`
2. Unzip
3. Inspect using `ls -lah AppCenter.xcframework/macos-x86_64/AppCenter.framework`
4. Check that `AppCenter.xcframework/macos-x86_64/AppCenter.framework/AppCenter` is not a symlink to `Versions/Current/AppCenter`

**Comment by MatkovIvan** [comment]
Hi @tbartelmess, thanks for pointing this out.
 
I confirm that this is a bug, but actually it was already fixed during work on Mac Catalyst support. The archive for the next release should be fine. I'm leaving this issue open until that. Thanks.

**Comment by ConnorQi** [comment]
Hey!
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.
