### ISSUE TITLE
Clean up before closeApp in MSDistribute

### ISSUE THREAD

**Issue by prkuruva** [microsoft/appcenter-sdk-apple#2093]
### **Description**

AppCenter SDK (MSDistribute module) when performing an in-app update, performs an- exit(0); operation. This immediately kills the application and isn't recommended by Apple. We need to provide Applications with a clean up facility before calling the exit(0).

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install App through AppCenter portal
2. Rerelease new version
3. Reboot installed application and perform in-app update using MSDistribute
4. On triggering in-app update MSDistribute performs exit(0) operation on the application

### **Details**

1. Which SDK version are you using?
    Issue on all versions (code path has no change)- https://github.com/microsoft/appcenter-sdk-apple/blob/455de8f0c8b53c8c82e3035562d6caccefa36762/AppCenterDistribute/AppCenterDistribute/MSDistribute.m#L1100 
2. Which OS version did you experience the issue on?
    Independent of OS Version
3. Which Cocoapods version are you using (run `pod --version`)?
    N/A
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    N/A
5. What language are you using?
    Objective C
6. What third party libraries are you using?
N/A

**Comment by prkuruva** [comment]
This is actually a FEATURE REQUEST, is there a way to change label?

**Comment by annakocheshkova** [comment]
Hi there! This is indeed, not recommended by Apple. Basically because `exit()` is treated like a crash and we have to give the user an ability to see what's wrong and quit themselves. Also, as you correctly mentioned, it is necessary to clean up the application. 

This would not work in our case, however, and the app must be quit to perform an update which user has just agreed to by pressing "Update Now". 

Any cleanup can be done in a [custom dialog](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/ios#2-customize-the-update-dialog), before `MSDistribute.notify(.update)` call (so right after the user has chosen to update the app).

**Comment by prkuruva** [comment]
Thanks for reaching out Anna. I understand it is a necessary evil, however there are alternatives to cleaning up code resting in Custom Dialog. I am just putting out a review in a bit for the same, it is the approach we used to not count these as crashes as part of our monitoring

**Comment by Marvae** [comment]
> Any cleanup can be done in a custom dialog, before MSDistribute.notify(.update) call (so right after the user has chosen to update the app).

This is based on a strong assumption. Assume that the update will be executed correctly and the app will be killed. Once it's not executed (for [example](https://github.com/microsoft/appcenter-sdk-apple/blob/develop/AppCenterDistribute/AppCenterDistribute/MSDistribute.m#L214): return before calling `exit(0)`), the app that has already cleaned up will get into trouble.

**Comment by sfuqua** [comment]
this issue is causing my team a large amount of crash report noise - we have native libraries that don't have an opportunity to cleanup because App Center kills the app, which then bubbles up as a crash as the destructors explode :/

**Comment by ConnorQi** [comment]
Hey!
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.
