### ISSUE TITLE
FormatStackFrame in MSErrorLogFormatter does not always work

### ISSUE THREAD

**Issue by izackp** [microsoft/appcenter-sdk-apple#2105]
### **Description**

FormatStackFrame in MSErrorLogFormatter does not always work. Seemlying for high address spaces.

In the app center crash report a lot of frames have the address but don't have the accompanying code. They will appear as '0x + 0'. This is because the binary image isn't found even though it definitely is there.

I believe plreport imageForAddress does not normalize addressed in the same way as appcenter

As a side note, I also believe the baseAddress and pcOffset need to be normalized before building the symbol string. I'm currently doing this and app center seems to resolve symbols just fine.

### **Repro Steps**

1. Recreate / submit a crash on an iOS app 
2. Notice missing frame information in reports despite having the address

### **Details**

1. Which SDK version are you using?
    - Dev Branch - 3.2.0 - June 16th
2. Which OS version did you experience the issue on?
    - iOS Simulator
3. Which Cocoapods version are you using (run `pod --version`)?
    - None
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPad Sim 12.9in 3rd gen 13.3 sek
5. What language are you using?
    - [x ] Objective C
    - [x ] Swift

**Comment by izackp** [comment]
A solution I hacked together that works for me:
`
+ (NSString *)formatStackFrame:(PLCrashReportStackFrameInfo *)frameInfo report:(PLCrashReport *)report {

  /*
   * Base image address containing instrumentation pointer, offset of the IP
   * from that base address, and the associated image name.
   */
  uint64_t baseAddress = 0x0;
  uint64_t pcOffset = 0x0;
  NSString *symbolString = nil;

  uint64_t instructionPointer = frameInfo.instructionPointer;
  uint64_t normalizedPointer = [MSErrorLogFormatter normalizeAddress:instructionPointer is64bit:YES];
  
  PLCrashReportBinaryImageInfo *imageInfo = [report imageForAddress:normalizedPointer];
  for (PLCrashReportBinaryImageInfo *imageInfo_ in [report images]) {
      uint64_t normalizedBaseAddress = [MSErrorLogFormatter normalizeAddress:imageInfo_.imageBaseAddress is64bit:true];
      uint64_t max = (normalizedBaseAddress + imageInfo_.imageSize);
      if (normalizedBaseAddress <= normalizedPointer && normalizedPointer < max) {
          imageInfo = imageInfo_;
          break;
      }
  }
  
  if (imageInfo != nil) {
      baseAddress = [MSErrorLogFormatter normalizeAddress:imageInfo.imageBaseAddress is64bit:true];
      pcOffset = normalizedPointer - baseAddress;
  }

  /*
   * If symbol info is available, the format used in Apple's reports is Sym +
   * OffsetFromSym. Otherwise, the format used is imageBaseAddress + offsetToIP.
   */
  MSBinaryImageType imageType = [self imageTypeForImagePath:imageInfo.imageName processPath:report.processInfo.processPath];
  if (frameInfo.symbolInfo != nil && imageType == MSBinaryImageTypeOther) {
    NSString *symbolName = frameInfo.symbolInfo.symbolName;

    // Apple strips the _ symbol prefix in their reports. Only OS X makes use of
    // an underscore symbol prefix by default.
    if ([symbolName rangeOfString:@"_"].location == 0 && [symbolName length] > 1) {
      if (report.systemInfo.operatingSystem == PLCrashReportOperatingSystemiPhoneSimulator) {
        symbolName = [symbolName substringFromIndex:1];
      } else {
        MSLogWarning([MSCrashes logTag], @"Symbol prefix rules are unknown for this OS!");
      }
    }

    uint64_t symOffset = frameInfo.instructionPointer - frameInfo.symbolInfo.startAddress;
    symbolString = [NSString stringWithFormat:@"%@ + %" PRId64, symbolName, symOffset];
  } else {
    symbolString = [NSString stringWithFormat:@"0x%" PRIx64 " + %" PRId64, baseAddress, pcOffset];
  }

  /*
   * Note that width specifiers are ignored for %@, but work for C strings.
   * UTF-8 is not correctly handled with %s (it depends on the system encoding),
   * but UTF-16 is supported via %S, so we use it here.
   */
  return symbolString;
}
`

**Comment by Jamminroot** [comment]
Hello, thanks for reaching out and sharing the code.
We'll have a look at this.

**Comment by MatkovIvan** [comment]
Hi @izackp , thanks for highlighting the issue.
We'll take care about it, but the fix should be a bit different.

**Comment by MatkovIvan** [comment]
Hey!
We've included the fix for this issue to the latest SDK release ([3.3.1](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/3.3.1)).
I'm closing it, but please reopen if you some questions or run into this again.
