### ISSUE TITLE
Crashes module doesn't work on macOS 10.11 and older

### ISSUE THREAD

**Issue by guidedways** [microsoft/appcenter-sdk-apple#2112]
Please see this: https://github.com/microsoft/plcrashreporter/issues/107

**Comment by MatkovIvan** [comment]
Hey!
We've included the fix for this issue to the latest SDK release ([3.3.1](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/3.3.1)).
I'm closing it, but please reopen if you some questions or run into this again.
