### ISSUE TITLE
 MSAnalytics.trackEvent doesn't work from applicationWillTerminate

### ISSUE THREAD

**Issue by luci1329** [microsoft/appcenter-sdk-apple#2123]
### **Description**

The application delegate's lifecycle method, applicationWillTerminate has a ~ 5 second time window to execute, according to apple docs, yet the simple event I am trying to log never show's up in the AppCenter event logs.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. log a simple event in the applicationWillTerminate
2. close the app
3. wait for the logs
4. die of waiting

### **Details**

1. Which SDK version are you using?
    - e.g. 2.1.0
2. Which OS version did you experience the issue on?
    - e.g. iOS 13
3. Which Cocoapods version are you using (run `pod --version`)?
    - e.g. 1.6.1
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - both, emulator and physical device (ipad mini 4)
5. What language are you using?
    - [x ] Objective C
    - [ ] Swift
6. What third party libraries are you using?
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here: n/a

**Comment by vvechkanov** [comment]
Hi @luci1329!

Thank you for contacting us!

I checked this situation, and I also do not get events from applicationWillTerminate. I'll create an issue for it in the team backlog, and we will contact you when this will be fixed.

**Comment by luci1329** [comment]
Hi @vvechkanov thanks for your quick response

**Comment by MatkovIvan** [comment]
This one should be fixed in 3.3.3. Feel free to comment/reopen if you have more questions or if you run into this problem again
