### ISSUE TITLE
Affected users data not shown correctly in App Center portal

### ISSUE THREAD

**Issue by shyamjimishra1993** [microsoft/appcenter-sdk-apple#2125]
Hi team,

We have integrated app center SDK in our product for crash reporting and crashes are getting uploaded correctly.
We are using MSCrashes service for that like below.
[MSAppCenter start: appSecretKey withServices:@[[MSCrashes class]]];

<img width="703" alt="Screenshot 2020-07-02 at 8 42 45 PM" src="https://user-images.githubusercontent.com/20599875/86377970-b118b180-bca6-11ea-9002-bc5c8806e408.png">

When we look in the portal for affected users' data, It just shows an empty graph with 100% in the top right corner.
How can we get this data correctly in the portal? 

We are interested to find out crash-free sessions, How do we achieve that with Appcener?
Also, Do we need to use AppCenter Analytics services to get this data? 
Good if you can refer to some link that points to how we can get this data correctly.

Thanks and regards
Shyam Ji Mishra

**Comment by AnastasiaKubova** [comment]
Hi, @shyamjimishra1993 ! Thanks for getting in touch with us! Could you please share the [verbose log](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/ios#analytics-data-doesnt-show-up-in-the-portal) before and after crash your app?

**Comment by shyamjimishra1993** [comment]
Hi @AnastasiaKubova ,

Thanks for helping out with this. I have shared with you the required logs over mail (v-ankubo@microsoft.com) as I found it safer to share logs there. Hope that's fine for you.
 
I have hidden a few Ids with “***” in the logs.  Let me know if you need any further info.

Thanks and Regards
Shyam Ji Mishra

**Comment by AnastasiaKubova** [comment]
@shyamjimishra1993 
Thanks for share the logs. Based on your logs I see that App Center configured successfully. This chart shows how many sessions were affected from the total count of sessions. So, to correctly display this chart, App Center needs to have count of sessions which tracked via Analytics module.

**Comment by shyamjimishra1993** [comment]
Hi @AnastasiaKubova ,

Thanks for your support on this. So you mean, We will have to integrate and start the AppCenter analytics module to get session data correctly?

Could you please share some doc/article which explains what is the minimum required steps we need to follow to get the sessions data correctly using the Analytics module. We are not interested in all the data at this moment and only affected users' data / crash-free sessions data should suffice our requirement.

Thanks and Regards
Shyam Ji Mishra

**Comment by MatkovIvan** [comment]
> We will have to integrate and start the AppCenter analytics module to get session data correctly?

Yes, tracking sessions is analytics module feature.

> Could you please share some doc/article which explains what is the minimum required steps

Long story short: add framework to your project and `[MSAnalytics class]` to your start call.
You can find the full doc [here](https://docs.microsoft.com/en-us/appcenter/sdk/analytics/ios).

**Comment by shyamjimishra1993** [comment]
Thanks @MatkovIvan for helping out with this. Will try the integrating analytics module and get back in case of any queries.

**Comment by MatkovIvan** [comment]
You are welcome. I'm closing this issue for now, but feel free to reopen/reply here.

**Comment by shyamjimishra1993** [comment]
Hi @MatkovIvan @AnastasiaKubova 

I tried adding the AppCenter Analytics framework and [MSAnalytics class] in the Services as shown below.
[MSAppCenter start:*** appSecretKey*** withServices:@[[MSCrashes class],[MSAnalytics class]]];

Now When I go to the analytics section, I see the user's data getting updated correctly as shown below.
<img width="1394" alt="Screenshot 2020-08-10 at 3 48 45 PM" src="https://user-images.githubusercontent.com/20599875/89773476-9812e400-db21-11ea-8022-4b42d20de8aa.png">
 
However, under the diagnostics section, the Affected user's data still shows 100% as previously.
I had installed the build in 2 devices and had a force crash logic. I tried crashing the app on one of the devices. I see that the crash is uploaded in the Crashes section in diagnostics. But the Affected user's data is not correct. It should show 50% as the crash happened only for one user out of 2.

<img width="637" alt="Screenshot 2020-08-10 at 3 47 41 PM" src="https://user-images.githubusercontent.com/20599875/89773804-4028ad00-db22-11ea-9d49-bf51eb015b24.png">

Please let me know if I need to do any other change or does it take a long time for Affected user's data to be calculated and displayed?


Thanks and Regards
Shyam Ji Mishra

**Comment by vvechkanov** [comment]
Hi @shyamjimishra1993!

Sorry to hear, that you still have this issue. Affected user's data should not take too long to be calculated (maybe 2-3 hours). As I understand you see error logged on the web page, right? Then data is correctly sent from your device to the AppCenter backend. If I am right AppCenter support team could help you with this, because this looks like an AppCenter backend problem.

I could suggest you wait 2-3 hours more, and then (if the problem still exists) contact support on appcenter web page, by clicking the question mark in the right upper corner.

**Comment by shyamjimishra1993** [comment]
Hi @vvechkanov ,
Thanks for your support on this. Yes, You are right. I see the Crash logged correctly on the webPage.
I have contacted the support team on the appcenter webpage. Let' see. Will keep u posted.
