### ISSUE TITLE
Configurable Symbolication Strategy

### ISSUE THREAD

**Issue by WiesnerPeti** [microsoft/appcenter-sdk-apple#2128]
**Is your feature request related to a problem? Please describe.**
For production, we can upload the dSYMs and have nice desymbolicated crash logs. We also have a DEBUG application registered in AppCenter to catch trending crashes before release during dogfooding. For DEBUG versions, the developers don't want to upload dSYMs for every build, hence DEBUG AppCenter application we don't have symbols in crashlogs.

**Describe the solution you'd like**
KSCrash already solved on-device symbolication if the Build Settings' _Strip Style_ is set to _Debugging Symbols_. As I understood, they using the match tables to find the nearest symbol for the PC. This means we can have (nearest) symbols without uploading the dSYM for every debug build.
https://github.com/kstenerud/KSCrash/blob/15ae3affcfaa0193b1e367102978d7d38788385a/Source/KSCrash/Recording/Tools/KSDynamicLinker.c#L232

I searched a little and found, that MSPLCrashReporter used by MSCrash, already can achieve the same, but it needs to be created with the `PLCrashReporterSymbolicationStrategySymbolTable` strategy.

Currently, the config is created with `PLCrashReporterSymbolicationStrategyNone`. Is there a reason, why this cannot be set externally? MSCrashHandlerSetupDelegate would be a good place to make this parameter injectable.
https://github.com/microsoft/appcenter-sdk-apple/blob/a912ed21e5e87c3bdffc1ed9726636c825f4df31/MobileCenterCrashes/MobileCenterCrashes/MSCrashes.m#L245

Also if the strategy is not "None", the `MSErrorLogFormatter` will ignore the collected symbol info when creating MSThreads for the API as the symbol is only used for Other Binary Image types. Why is that?
https://github.com/microsoft/appcenter-sdk-apple/blob/a912ed21e5e87c3bdffc1ed9726636c825f4df31/MobileCenterCrashes/MobileCenterCrashes/Internals/Utils/MSErrorLogFormatter.m#L459

Thank you for the answers in advance!

**Comment by MatkovIvan** [comment]
Hi @WiesnerPeti ,
Thanks for getting in touch!
As you already found, `PLCrashReporter` has a few symbolycation strategies including `PLCrashReporterSymbolicationStrategySymbolTable`. But local symbolycation is not really reliable, so App Center SDK explicitly sets the most reliable way to collect and symbolicate the crash reports. You can find more details in [the PLCrashReporter's docs](https://github.com/microsoft/plcrashreporter/blob/050e1641de2b2d6ac157382a0123b8ed948941ac/Source/PLCrashReporterConfig.h#L104-L117)

> Why is that?

`MSErrorLogFormatter` is supposed to prepare data for backend side symbolycation.

Anyway, we got your point - we'll keep this feature request open. To anyone who also interested in local symbolycation: feel free to upvote this so we can properly triage it.

**Comment by WiesnerPeti** [comment]
Thank you for the quick answers :)

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
