### ISSUE TITLE
MASR rejection due to usage of private api getsectdatafromheader_64

### ISSUE THREAD

**Issue by berbie** [microsoft/appcenter-sdk-apple#2135]
### **Description**

Got rejected by MASR because AppCenter for macOS uses private api: getsectdatafromheader_64 in MSErrorLogFormatter.m

### **Details**

1. Which SDK version are you using?
    - e.g. 3.3.1
2. Which OS version did you experience the issue on?
    - e.g. macOS 10.15.6
5. What language are you using?
    - [x] Objective C
    - [ ] Swift
6. What third party libraries are you using? 
    NONE

**Comment by boyvanamstel** [comment]
Same here.

> Your app uses or references the following non-public APIs:
>Symbols: _getsectiondata, _getsectdatafromheader, _getsectdatafromheader_64

**Comment by sindresorhus** [comment]
I also got the exact same rejection as @boyvanamstel yesterday.

**Comment by sindresorhus** [comment]
I submitted the same update but without AppCenter and it was accepted.

**Comment by boyvanamstel** [comment]
My appeal was successful. The exact same build was just approved.

I didn’t get a reply, so I’m not sure if the flag for private API use was accidental or not. 🤷‍♂️

**Comment by berbie** [comment]
Same here now. After the appeal they just passed it through.

**Comment by MatkovIvan** [comment]
Hi there 👋 

First of all, thanks for getting in touch!
These APIs are public from [the `mach-o/getsect.h` header](https://opensource.apple.com/source/cctools/cctools-949.0.1/include/mach-o/getsect.h.auto.html) and I cannot find **any** mention that it's private. It sounds like a false positive on Apple side and I'm glad that your apps have been approved after all.

We're monitoring the situation with it, but please let us know if you have the same issue.

**Comment by tempelmann** [comment]
@boyvanamstel , @berbie What did you say in your appeal? You're not the only ones getting these rejections since recently: The alternative dev environment Xojo.com has the same issue with all apps it creates. Those people need an idea what to say in their appeal.

**Comment by berbie** [comment]
@tempelmann : I write something similar toi the edit of @boyvanamstel above.

**Comment by MatkovIvan** [comment]
It looks like this issue was temporary and has been resolved from Apple side.

Closing this issue, but please leave a comment here if the problem still exists.
