### ISSUE TITLE
It seems the `MSErrorLogSetting` is defined but never used?

### ISSUE THREAD

**Issue by Petr-2019** [microsoft/appcenter-sdk-apple#2142]
In `MSCrashes.h`, there's an enum called `MSErrorLogSetting`. I think in Hockey SDK we have something similar called `BITCrashManagerStatus`.

We used to rely on `BITCrashManagerStatus` to do some things, is there anything else equivalent we can make use of?

**Comment by Jamminroot** [comment]
Hey, thanks for reaching out.
It's part of legacy code, and users are supposed to be using `MSUserConfirmation` enum instead, which has the same meaning (although it's name leans more towards user's reaction, than behaviour of Crashes module).

I'm changing label, please revert it back to feature request if it's actually a feature request - and clarify what's requested, in this case.

**Comment by Petr-2019** [comment]
Thanks @Jamminroot for answering my question! 

I'll just close this.
