### ISSUE TITLE
Crash in -[MSAppCenterUserDefaults migrateKeys:forService:]

### ISSUE THREAD

**Issue by brownjoel** [microsoft/appcenter-sdk-apple#2162]
### **Description**

As we begin to adopt MS App Center, Analytics, and Crashes, I've had a few users crash on initialization.  The crash occurs inside of -[MSAppCenterUserDefaults migrateKeys:forService:].  It seems the code is making an assumption about the nature of the old keys in the dictionary.  Specifically, this code:

`NSArray *userDefaultsDictionary = [[[NSUserDefaults standardUserDefaults] dictionaryRepresentation] allKeys];
      for (NSString *userDefaultsKey in userDefaultsDictionary) {
        if ([userDefaultsKey hasPrefix:oldKeyPrefix]) {`

Not all objects in the user's dictionary are NSStrings, so it crashes:

> Application Specific Information:
> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFBoolean hasPrefix:]: unrecognized selector sent to instance 0x7fff86a4c380'
> abort() called
> terminating with uncaught exception of type NSException
> 
> Application Specific Backtrace 1:
> 0   CoreFoundation 	 __exceptionPreprocess + 250
> 1   libobjc.A.dylib 	 objc_exception_throw + 48
> 2   CoreFoundation 	 -[NSObject(NSObject) __retain_OA] + 0
> 3   CoreFoundation 	 ___forwarding___ + 1427
> 4   CoreFoundation 	 _CF_forwarding_prep_0 + 120
> 5   -[MSAppCenterUserDefaults migrateKeys:forService:]   (MSAppCenterUserDefaults.m:50)
> 6   -[MSAppCenter init]   (MSAppCenter.m:267)
> 7   __29+[MSAppCenter sharedInstance]_block_invoke   (MSAppCenter.m:64)
> 8   libdispatch.dylib 	 _dispatch_client_callout + 8
> 9   libdispatch.dylib 	 _dispatch_once_callout + 20
> 10  +[MSAppCenter sharedInstance]   (MSAppCenter.m:62)
> 11  +[MSAppCenter start:withServices:]   (MSAppCenter.m:87)

For now, we are patching around the crash by setting the Migrated key.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Have the NSUserDefaults for the app include a boolean.
2. Initialize MSAppCenter with MSAnalytics.

### **Details**

1. Which SDK version are you using?
Unknown, how do I confirm?
2. Which OS version did you experience the issue on?
macOS 10.15.6
3. Which Cocoapods version are you using (run `pod --version`)?
1.9.3
4. What device version did you see this error on?  Were you using an emulator or a physical device?
MacBook Pro
5. What language are you using?
    - [x] Objective C
    - [ ] Swift
6. What third party libraries are you using?
Dropbox, Sparkle, ZipArchive
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
I try to reproduce this case, but for me, it works correctly. Could you please clarify if you updated the App Center SDK? If so, which version did you use before and which one are you using now?

**Comment by brownjoel** [comment]
No, this is a fresh install for our program, and for the users that were crashing.

Did you try adding the invalid values to your NSUserDefaults?

**Comment by Jamminroot** [comment]
Hey, @brownjoel, sorry for a delay in reaction & response - this problem was adressed in our [PR](https://github.com/microsoft/appcenter-sdk-apple/pull/2167). Once it is merged, it will be included in the next SDK release.

**Comment by AnastasiaKubova** [comment]
The fix has been released in [4.0.0](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.0.0) version of App Center.
