### ISSUE TITLE
Unable to Weak-link correctly for <10.9 systems.

### ISSUE THREAD

**Issue by brownjoel** [microsoft/appcenter-sdk-apple#2163]
### **Description**

Our team is well aware that the framework requires macOS 10.9 as a minimum.  However, our app has not yet moved to 10.9 as a minimum.  We are currently unable to get a build that can run on macOS 10.7 or 10.8.  It crashes on launch with:

> Anonymous UUID: D302ADC5-3E2C-41ED-9852-148B1913AF6F
Crashed Th

> read: 0
> Exception Type: EXC_BREAKPOINT (SIGTRAP)
> Exception Codes: 0x0000000000000002, 0x0000000000000000
> Application Specific Information:
> dyld: launch, loading dependent libraries
> Dyld Error Message:
> Symbol not found: _NSKeyedArchiveRootObjectKey

Our program also includes Dropbox SDK support, but we are able to build the program where its calls to higher macOS calls are optional, so the program is fine as long as we don't call into the framework.  Is there a way to tweak AppCenter to not hard link to these Foundation methods (_NSKeyedArchiveRootObjectKey)?

### **Repro Steps**

Please list the steps used to reproduce your issue.

1.  Make a new project that targets macOS 10.7 and includes MSAppCenter.
2.  Include the MSAppCenter initialization inside an `(@available(macOS 10.9, *))` clause
3.  Attempt to launch on a 10.7 machine.

### **Details**

1. Which SDK version are you using?
Unknown, but built using CocoaPods on August 25th.
2. Which OS version did you experience the issue on?
macOS 10.7-10.8.
3. Which Cocoapods version are you using (run `pod --version`)?
1.9.3
4. What device version did you see this error on?  Were you using an emulator or a physical device?
MacBook Pro
5. What language are you using?
    - [x] Objective C
    - [ ] Swift
6. What third party libraries are you using?
Dropbox (also skipped on 10.7), Sparkle, ZipArchive
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
Unfortunately, for now we have no way to use `App Center` on `macOS` lower `10.9`, because the minimal target version is `10.9`.
But if you have a ready-made solution for this we'd happily accept PRs.

Thanks

**Comment by brownjoel** [comment]
Alright, thank you for the reply.  If I'm able to figure out the solution I'll set up a PR.
