### ISSUE TITLE
Can't work with SwiftUI preview

### ISSUE THREAD

**Issue by tpian928** [microsoft/appcenter-sdk-apple#2165]
#2088 # **Description**

Can't preview any view if I use the App Center

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create any SwiftUI View
2. Preview it

### **Details**

1. Which SDK version are you using?
    3.3.4
2. Which OS version did you experience the issue on?
    iOS 14
3. Which Cocoapods version are you using (run `pod --version`)?
    1.8.3
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    All emulator
5. What language are you using?
    Swift
6. What third party libraries are you using?

7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by Jamminroot** [comment]
Hey! Thanks for bringing this to our sight. Please, let me some time to look into it, and I'll update you here once I gather some context

**Comment by Jamminroot** [comment]
Closed ticket by mistake, sorry

**Comment by Jamminroot** [comment]
We've tested that problem on our machines, and the problem did not reproduce for us - tested against XCode 11 and 12.
Is there a chance to have a peek at a sample project you are testing with (just the App Center implementation, no other code required), or, at very least, can you provide verbose logs as per step [7] in issue the template? Or, if you can't even build the app and launch it (might've misunderstood the problem) - can you provide build output?

**Comment by tpian928** [comment]
The report is 
```
SchemeBuildError: Failed to build the scheme "WoWidgets"

linker command failed with exit code 1 (use -v to see invocation)

Link WoWidgets (arm64):
ld: in /Users/wangyifei/Codes/WoWidgets/Pods/AppCenter/AppCenter-SDK-Apple/iOS/AppCenter.framework/AppCenter(MSAppCenter.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/wangyifei/Codes/WoWidgets/Pods/AppCenter/AppCenter-SDK-Apple/iOS/AppCenter.framework/AppCenter' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
And I use new ios 14 app life circle. It may cause this issue?
```
import Foundation
import SwiftUI

@main
struct WoWidgetApp: App {
    
    static var shared = WoWidgetApp()
    
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    
    internal init() { }
    
    var settings: DWSettings = DWSettings()
    
    var body: some Scene {
        WindowGroup {
            MyView()
                .environmentObject(settings)
        }
    }
}
```

**Comment by GyroJoe** [comment]
@tpian928 is your active scheme building for Release mode (or some other configuration where you have `Build Active Architecture Only` = `No`)?

It seems like this is caused by Xcode trying to build for the arm64 simulator. Some related investigation here:
https://github.com/flurry/flurry-ios-sdk/issues/207

The AppCenter SDK will need to provide an arm64 simulator binary for this build to work, until then, you can exclude the arm64 arch from being built, *only* while targeting the simulator, like this:
![image](https://user-images.githubusercontent.com/2504702/94497369-ddf83a00-01ab-11eb-8083-d194b534c6d7.png)

**Comment by MatkovIvan** [comment]
> Which Cocoapods version are you using (run pod --version)?
1.8.3

@tpian928 How did you integrate the SDK? CocoaPods?

@GyroJoe this should not affect binary distribution. Also, App Center already excluded (temporary) `arm64` from simulator architectures, so if you are using our build configs, then it shouldn't be the case as well. The only way that I see it's SwiftPM that ignores all project configs, but it uses application setting instead 🤔 

So, waiting more details here for now.

**Comment by tpian928** [comment]
I use CocoaPods. And I can preview it with this:
<img width="456" alt="look" src="https://user-images.githubusercontent.com/8392842/94548727-bbd1eb00-0283-11eb-8ced-cb2ed7d5a828.png">

**Comment by MatkovIvan** [comment]
Ah right, got it.
The application builds with `arm64` simulator arch, but our framework doesn't provide the Apple Silicon support yet (this arch requires to run simulator on new macs).

See this feature request https://github.com/microsoft/appcenter/issues/1927 to track status of it.
