### ISSUE TITLE
Won't Build to iOS Simulator (MSAuthTokenContext, MSUserDefaults not found)

### ISSUE THREAD

**Issue by dgerding** [microsoft/appcenter-sdk-apple#2166]
### **Description**

Adding AppCenter.Auth causes build/deploy failure to iOS Simulator.

Native linking failed, undefined Objective-C class: MSAuthTokenContext. 
The symbol '_OBJC_CLASS_$_MSAuthTokenContext' could not be found in any of the libraries or frameworks linked with your application.	

Native linking failed, undefined Objective-C class: MSUserDefaults. 
The symbol '_OBJC_CLASS_$_MSUserDefaults' could not be found in any of the libraries or frameworks linked with your application.	

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Add AppCenter Auth Nuget to Xamarin Forms Solution 
2. Attempt to build and run on iOS simulator from VS Win. (Same solution builds and runs with Auth nuget removed)

### **Details**

1. Which SDK version are you using?
    - Xamarin 4.8 latest release
2. Which OS version did you experience the issue on?
    iPhone 14 OS (simulator), MacOS 10.15.6
5. What language are you using?
  C#

**Comment by Jamminroot** [comment]
Hello, thanks for using App Center SDK. Unfortunately, AppCenter.Auth module is [retired since version 3.0.0](https://github.com/microsoft/appcenter-sdk-apple/blob/develop/CHANGELOG.md#app-center-auth), and we no longer maintain or support it.

**Comment by dgerding** [comment]
Ha! Thanks :) That explains it.
