### ISSUE TITLE
Add a mechanism to MSCrashes to reset the user's confirmation preference

### ISSUE THREAD

**Issue by marmphco** [microsoft/appcenter-sdk-apple#2169]
**Is your feature request related to a problem? Please describe.**

After experiencing a crash, users are prompted with a dialog to let them decide how they want to handle the crash report. They can choose to send the report, not send the report, or always send reports. If the user chooses to always send reports, there is no way for them to reset that preference.

We would like to allow our users to change their crash reporting preference back from *always sending* to *asking for confirmation before sending*, and vice versa. 

I’m guessing that this functionality was intentionally omitted to prevent developers from abusing it and overriding the user’s preferences sneakily. If that’s the case, I’ll withdraw this request. Otherwise it would be nice to have 🙂 

**Describe the solution you'd like**

*Proposal 1*

Add a method to MSCrashes that sets the user’s confirmation preference.

```objectivec
typedef NS_ENUM(NSUInteger, MSUserConfirmationPreference)
{
    /*
     * Ask the user for confirmation before sending crash reports.
     */
    MSUserConfirmationAsk,

    /*
     * Always send crash reports without confirmation from the user.
     */
    MSUserConfirmationAlwaysSend,
}

/**
 * Set the user's crash reporting confirmation preference
 */
- (void) setConfirmationPreference:(MSUserConfirmationPreference) preference
{
    switch (preference)
    {
        case MSUserConfirmationAsk:
            [MS_APP_CENTER_USER_DEFAULTS setObject:@NO forKey:kMSUserConfirmationKey];
            break;
        case MSUserConfirmationAlwaysSend:
            [MS_APP_CENTER_USER_DEFAULTS setObject:@YES forKey:kMSUserConfirmationKey];
            break;
    }
}
```

*Proposal 2*

Add a method to MSCrashes that resets the user’s confirmation preference. This might be more palatable than Proposal 1 because it can't be used to force crash reports to be sent automatically.

```objectivec
/**
 * Reset the user's crash reporting confirmation preference.
 * The next time a crash occurs, the user will be prompted with a dialog allowing
 * them to choose how to handle the crash report.
 */
- (void) resetConfirmation
{
    [MS_APP_CENTER_USER_DEFAULTS setObject:@NO forKey:kMSUserConfirmationKey];
}
```

**Describe alternatives you've considered**

Reaching into the app center's user defaults object from our app code and setting the `kMSUserConfirmationKey` entry from there. It would probably work but it would be fragile.

**Comment by Jamminroot** [comment]
Hey! Thanks for reaching out.

For now you can work this around by resetting user defaults key manually from your code:

```swift
UserDefaults.standard.removeObject(forKey: @"MSAppCenterCrashesUserConfirmation")
```
```obj-c
[[NSUserDefaults standardUserDefaults] removeObjectForKey:@"MSAppCenterCrashesUserConfirmation"];
```

**Comment by marmphco** [comment]
Got it, the workaround should suffice for now.

**Comment by DmitriyKirakosyan** [comment]
Hi @marmphco , I'm going to close this feature request since the described case is very specific and we haven't had similar feature requests. Moreover, you can implement this behaviour using the [workaround](https://github.com/microsoft/appcenter-sdk-apple/issues/2169#issuecomment-698780109).
