### ISSUE TITLE
Defer sending network requests until a crash occurs

### ISSUE THREAD

**Issue by ksuther** [microsoft/appcenter-sdk-apple#2170]
**Is your feature request related to a problem? Please describe.**

The App Center SDK always sends a network connection when the app launches, even if there are no crash reports to send. This is a privacy concern because devices should not send data to App Center until the user consents to sending a crash report.

**Describe the solution you'd like**

`sendStartServiceLog:` sends device statistics on every app launch. This raises privacy concerns for users who see unexpected connections to App Center even when no crash has occurred.

**Describe alternatives you've considered**

The device statistics sent in `sendStartServiceLog:` should be deferred until a crash report needs to be sent. This is a more privacy-friendly approach. HockeySDK did not make network connections on every app launch, so now users are concerned that they're being tracked now that we've switched to the App Center SDK.

**Comment by MatkovIvan** [comment]
Hi @ksuther,

Thanks for getting in touch!
Sending crash reports is not only one function of App Center SDK, it also takes care of Analytics, in-app updates, etc. This event is not directly related to crashes and is not depend on Crashes module state. Also, I want to mention that Analytics data gives you "crash-free" sessions chart.

If you do not want to send anything until user confirmation, you can use [`MSAppCenter.setEnabled` API](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/ios#disable-all-services-at-runtime) to temporarily disable the SDK, but please. note that in disabled state SDK doesn't collect crashes.

PS this was already discussed in https://github.com/microsoft/appcenter-sdk-dotnet/issues/1231, https://github.com/microsoft/appcenter-sdk-dotnet/issues/1232. So, it's kind of a duplicate.

**Comment by MatkovIvan** [comment]
I've transferred original feature request to the main repo - https://github.com/microsoft/appcenter/issues/2004

Let's track the status of it there. Closing this one as a duplicate.
