### ISSUE TITLE
Cannot build macOS app on ARM Mac

### ISSUE THREAD

**Issue by sseyod** [microsoft/appcenter-sdk-apple#2176]
### **Description**

Building macOS app on ARM hardware,  I get a Linker error of this form:

... linked framework 'AppCenter.framework' is missing one or more architectures required by this target: arm64.

### **Repro Steps**

Simply build an application for macOS using the latest App Center SDK, on ARM-based Mac.

You'll get the above Linker error!

NB: I *presume* that you have at least one ARM-based Mac from Apple for development/testing...?

### **Details**

1. Which SDK version are you using?
    3.3.4
2. Which OS version did you experience the issue on?
    Big Sur - 11.x
3. Which Cocoapods version are you using (run `pod --version`)?
    N/A - using Swift Package manager under Xcode
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    ARM Mac
5. What language are you using?
    - [X ] Objective C
    - [X ] Swift
6. What third party libraries are you using?
  None
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
 N/A - this is a *linker* error

Thanks in advance,

Pete

**Comment by MatkovIvan** [comment]
Apple Silicon feature request is tracked here - https://github.com/microsoft/appcenter/issues/1927

Closing this as duplicate.
