### ISSUE TITLE
[Question]: is it possible to send an Actionable push notification using App Center?

### ISSUE THREAD

**Issue by oferRounds** [microsoft/appcenter-sdk-apple#2179]
https://developer.apple.com/documentation/usernotifications/declaring_your_actionable_notification_types

Thank you!

**Comment by vvechkanov** [comment]
Hello @oferRounds! 

We are retiring push service soon (31st of December 2020). You can migrate to Azure Notifications Hubs. [Here](https://devblogs.microsoft.com/appcenter/migrating-off-app-center-push/) is the article which can help you to do this. 

I am closing this ticket, but feel free to comment and reopen it if you need additional clarifications.
