### ISSUE TITLE
Crash in ISO8601DateFormatter

### ISSUE THREAD

**Issue by MBayard** [microsoft/appcenter-sdk-apple#2189]
When simultaneously launching multiple Mac audio plugins using the the AppCenter SDK, we get occasional crashes in ISO8601DateFormatter.

Thread 1 Crashed:: Dispatch queue: com.microsoft.appcenter.ChannelGroupQueue
0   libobjc.A.dylib               	0x00007fff7091069d objc_msgSend + 29
1   com.apple.Foundation          	0x00007fff484210d9 -[NSDateFormatter setLocale:] + 149
2   com.dolby.atmos.binaural.settings.AAX	0x0000000129c05a91 +[MSUtility(Date) ISO8601DateFormatter] + 140
3   com.dolby.atmos.binaural.settings.AAX	0x0000000129c0593e +[MSUtility(Date) dateToISO8601:] + 53
4   com.dolby.atmos.binaural.settings.AAX	0x0000000129c0cf00 -[MSAbstractLog serializeToDictionary] + 233
5   com.dolby.atmos.binaural.settings.AAX	0x0000000129bf5c4a -[MSStartServiceLog serializeToDictionary] + 64
6   com.dolby.DolbyAtmosPanner.AAX 	0x000000012c385d8b __49-[MSLogContainer serializeLogWithPrettyPrinting:]_block_invoke + 29
7   com.apple.CoreFoundation      	0x00007fff461b07bb -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 219
8   com.dolby.DolbyAtmosPanner.AAX 	0x000000012c385b75 -[MSLogContainer serializeLogWithPrettyPrinting:] + 176

Repro Steps:

Create multiple plugins with the AppCenter SDK, load them into your favorite audio workstation, see intermittent crashes on workstation launch.

Using AppCenter Apple 3.2.0
MacOS 10.14
Objective-C++ interface

**Comment by russelarms** [comment]
Hi! Thanks for reaching out, we're looking at this now!

**Comment by MBayard** [comment]
Thanks.  Attaching another crash log, this time from Ableton Live instead of Pro Tools.

[Live crash log.pdf](https://github.com/microsoft/appcenter-sdk-apple/files/5379957/Live.crash.log.pdf)

**Comment by AnastasiaKubova** [comment]
The fix has been released in [4.0.0](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.0.0) version of App Center.
