### ISSUE TITLE
exception 'NSInternalInconsistencyException', reason: 'Couldn't posix_spawn: error 13'

### ISSUE THREAD

**Issue by AmyLee91** [microsoft/appcenter-sdk-apple#2190]
Description

With appcenter v2.5.3, getting information for exceptions on the main thread has been greatly improved. Thanks for this! But we are still seing some exception crashes for which we do not understand, like this one:

> Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Couldn't posix_spawn: error 13'

> Thread 6 Crashed:
0   libsystem_kernel.dylib               0x00007fff6d1f733a __pthread_kill + 10
1   libsystem_c.dylib                    0x00007fff6d17e808 abort + 119
2   MyApp          -[MSPLCrashReporter setCrashCallbacks:].cold.1 (in MyApp) + 0
3   MyApp       -[MSPLCrashReporter generateLiveReportWithThread:] (in MyApp) (PLCrashReporter.m:660)
4   CoreFoundation                       0x00007fff3313493c __handleUncaughtException + 725
5   libobjc.A.dylib                      0x00007fff6bf095a3 _objc_terminate() + 89
6   MyApp          MSCrashesUncaughtCXXTerminateHandler() (in MyApp) (MSCrashesCXXExceptionHandler.mm:163)
7   libc++abi.dylib                      0x00007fff6a3dc887 std::__terminate(void (*)()) + 7
8   libc++abi.dylib                      0x00007fff6a3dc829 std::terminate() + 40
9   libobjc.A.dylib                      0x00007fff6bf093c2 objc_terminate + 8
10  libdispatch.dylib                    0x00007fff6d05666c _dispatch_client_callout + 27
11  libdispatch.dylib                    0x00007fff6d064aa8 _dispatch_root_queue_drain + 662
12  libdispatch.dylib                    0x00007fff6d065097 _dispatch_worker_thread2 + 91
13  libsystem_pthread.dylib              0x00007fff6d2b09f7 _pthread_wqthread + 219
14  libsystem_pthread.dylib              0x00007fff6d2afb77 start_wqthread + 14

> Thread 0:
0   libsystem_kernel.dylib               0x00007fff6d1f0dfa mach_msg_trap + 10
1   CoreFoundation                       0x00007fff3303fef5 __CFRunLoopServiceMachPort + 246
2   CoreFoundation                       0x00007fff3303e9c2 __CFRunLoopRun + 1318
3   CoreFoundation                       0x00007fff3303de3e CFRunLoopRunSpecific + 461
4   HIToolbox                            0x00007fff31c6aabd RunCurrentEventLoopInMode + 291
5   HIToolbox                            0x00007fff31c6a7d5 ReceiveNextEventCommon + 583
6   HIToolbox                            0x00007fff31c6a579 _BlockUntilNextEventMatchingListInModeWithFilter + 63
7   AppKit                               0x00007fff302b0039 _DPSNextEvent + 882
8   AppKit                               0x00007fff302ae880 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1351
9   AppKit                               0x00007fff302a058e -[NSApplication run] + 657
10  AppKit                               0x00007fff30272396 NSApplicationMain + 776
11  MyApp          main (in MyApp) (AppDelegate.swift:17)
12  libdyld.dylib                        0x00007fff6d0afcc9 start + 0

Is there any chance to also catch these?

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. myApp launch , Run at the background ;
2. crashed After a while

### **Details**

1. Which SDK version are you using?
    -  2.5.3
2. Which OS version did you experience the issue on?
    -  MacOS 10.15.7/10.15.6
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.9.1
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - MacBook Pro
5. What language are you using?
     -Swift

**Comment by MatkovIvan** [comment]
Hi @AmyLee91,

There are some cases when there is no way to get original stacktrace from C++ exceptions (most common case is the exception thrown from another dynamic library). Please read this comment for details - https://github.com/microsoft/appcenter-sdk-apple/issues/2042#issuecomment-620657538

So, based on report I can say that it's some C++ exception, but unfortunately there is not many details that we can grab here.
