### ISSUE TITLE
Integration by copying the binaries into your project generates warnings under Xcode 12

### ISSUE THREAD

**Issue by mledford** [microsoft/appcenter-sdk-apple#2195]
### **Description**

When integrating the SDK into a project under Xcode 12 upon compilation the following warnings are produced.

Double-quoted include "MSAbstractLog.h" in framework header, expected angle-bracketed instead
Double quoted include "MSAppcenter.h" in framework header, expected angle-bracketed instead
...

### **Repro Steps**

1. Follow the directions for getting started at:
https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios#34-integration-by-copying-the-binaries-into-your-project
2. Compile the project and see the warnings.

### **Details**

1. Which SDK version are you using?
AppCenter-SDK-Apple-3.3.4

2. Which OS version did you experience the issue on?
N/A

3. Which Cocoapods version are you using (run `pod --version`)?
N/A

4. What device version did you see this error on?  Were you using an emulator or a physical device?
N/A

5. What language are you using?
N/A

6. What third party libraries are you using?
N/A

**Comment by MatkovIvan** [comment]
Hi @mledford,

Yeah, this is a new warning that was introduced recently, it's already in our backlog.
You can disable this warning in Xcode build settings (`CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER`)

**Comment by ConnorQi** [comment]
Hey!
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.
