### ISSUE TITLE
macOS SDK: MSCompression failing with "Invalid parameter passed in to function."

### ISSUE THREAD

**Issue by logancollins** [microsoft/appcenter-sdk-apple#2203]
### **Description**

We've recently updated our apps to build in Xcode 12.2 and on Apple Silicon, in preparation with the release of ARM Macs later this year. However, in doing so we noticed that the AppCenter SDK stopped working (which I think isn't _directly_ related to anything except for linked libraries).

The SDK is failing to submit diagnostics and analytics with the following error messages:

```
[AppCenter] ERROR: +[MSCompression compressData:]/47 Compression failed with error: Invalid parameter passed in to function.
[AppCenter] ERROR: -[MSChannelUnitDefault sendLogContainer:]_block_invoke/228 Log(s) sent with failure, batch Id:D8C45C92-85B1-4665-9778-B177B5733957, status code:400
[AppCenter] ERROR: -[MSChannelUnitDefault sendLogContainer:]_block_invoke/241 Fatal error encountered; shutting down channel unit with group ID Analytics
```

The first error message is what I started investigating, and was able to trace it to zlib's `deflateInit2`. The AppCenter SDK appears to be passing the value `31` for the `windowBits` argument. However, the zlib header doc for `deflateInit2` for macOS mentions that the only valid arguments for this is in the range `0..15`. Sure enough, setting this value to 15 results in the SDK (seemingly) compressing and then sending data properly.

Strangely, this issue only began presenting itself after updating some of our (unrelated) frameworks to the new XCFramework format for building both Intel and ARM targets for macOS. As best I can tell, this might be because the linked version of `zlib` for the application (which AppCenter would then use) is now using the Apple SDK's `zlib.tbd` placeholder and thus the SDK's newest available version of the library, which perhaps has made this argument check far more strict?

I'm happy to try and provide any other information that might be needed! I understand that our environment is a tad bit bleeding edge.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Link our application against the macOS 11.0 SDK in Xcode 12.2
2. Link with the `zlib.tbd` library placeholder of the macOS 11.0 SDK
3. Link the AppCenter SDK (AppCenter + Crashes + Analytics)
4. Initialize the SDK on launch to send crash reports

### **Details**

1. Which SDK version are you using?
    - 3.3.4
2. Which OS version did you experience the issue on?
    - macOS 10.15.7 and 11.0
3. Which Cocoapods version are you using (run `pod --version`)?
    - None (direct download and integration)
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - All Intel and ARM Macs running 10.15 (Catalina) and 11.0 (Big Sur)
5. What language are you using?
    - Objective C
6. What third party libraries are you using?
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

(See above in Description.)

**Comment by russelarms** [comment]
Hi @logancollins, thanks for reaching out!
I tested AppCenter SDK on a new app on macOS BigSur (arm64 & Rosetta) on Xcode 12.2 beta2 and it worked fine for me.
Maybe it's possible for you to share a sample app where this issue can be reproduced?

**Comment by logancollins** [comment]
Hello @russelarms! Thank you for looking into this!

I'm attaching a sample project that is reproducing the issue in the same way (I really hope it's not specific to something about our environment. 😅)

https://www.dropbox.com/s/v9v5av4pj64tj3o/AppCenterTestApp.zip?raw=1

The project contains and links the following libraries to properly emulate our app:
- AppCenter 3.3.4
- libgit2
- libcrypto
- libssl
- libssh2
- libz (from the macOS 11.0 SDK)
- libiconv (from the macOS 11.0 SDK)

To properly reproduce, I had to cause the test app to crash (outside of Xcode / the debugger) using the "Crash" button provided. On the next launch (attached to Xcode), AppCenter attempts to send the crash report and fails with the same console output:

```
[AppCenterCrashes] WARNING: -[MSCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/689 Detecting crashes is NOT enabled due to running the app with a debugger attached.
[AppCenter] ERROR: +[MSCompression compressData:]/47 Compression failed with error: Invalid parameter passed in to function.
[AppCenter] ERROR: -[MSChannelUnitDefault sendLogContainer:]_block_invoke/228 Log(s) sent with failure, batch Id:79E3A8F3-1433-4EF1-AF67-CDA764D3BD54, status code:400
[AppCenter] ERROR: -[MSChannelUnitDefault sendLogContainer:]_block_invoke/241 Fatal error encountered; shutting down channel unit with group ID AppCenter
```

**Comment by russelarms** [comment]
@logancollins, thanks for sharing the project! 
I've just tested it on Catalina 10.15.7 Xcode 12.0.1 and on Big Sur 11.0 Xcode 12.0 beta6.
The only thing I found is a build error when targeting "My Mac" on arm64:
```
/Users/appcenter/Downloads/AppCenterTestApp/AppCenterTestApp.xcodeproj The linked library 'libssh2-mac.a' is missing one or more architectures required by this target: arm64.
```
Checked the file with lipo, it only has x86_64 arch:
```
lipo -info libssh2-mac.a
Non-fat file: libssh2-mac.a is architecture: x86_64
```
Aside from that, I didn't see any errors on Catalina and on Big Sur targeting My Mac (Rosetta).

**Comment by logancollins** [comment]
Ah, darn. I'm still at a loss trying to figure out what might be different. Just to confirm… you're using Xcode 12.0, or the 12.2 beta?

**Comment by logancollins** [comment]
I think we've figured out our issue.

`libgit2`, unbeknownst to me, includes an internal copy of zlib (which can be disabled, but wasn't). This was causing duplicate symbols when both libgit2 and the system zlib were linked in for AppCenter.

It appears that things just happened to be invoked safely, _until_ we made the switch to `xcframeworks` recently. I'm not sure if something with `dyld` or Xcode is causing the behavior to _slightly_ change for duplicate symbols, but it's now causing AppCenter to use the libgit2-zlib (which appears to be more strict) instead of the system zlib.dylib.

In the implementation of zlib, there is this:

```c
#ifdef GZIP
    else if (windowBits > 15) {
        wrap = 2;       /* write gzip wrapper instead */
        windowBits -= 16;
    }
#endif
```

It appears that the libgit2-provided code is being built without the `GZIP` flag, thus making the library more strict.

Terribly sorry for the noise on this, and thank you for your assistance anyway!
