### ISSUE TITLE
Connection to "in.appcenter.ms" - Analytics disabled, no crash

### ISSUE THREAD

**Issue by vitwo** [microsoft/appcenter-sdk-apple#2205]
Hello,

Only [MSCrashes.self] is enabled in my app.
For what reason a connection to in.appcenter.ms is established periodically without app crashes?

Thanks

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
If you use only the Crashes module, then the App Center SDK should connect to `in.appcenter.ms` only when:
- AC just was started and send `startService` event. This event is not directly related to crashes and is not dependent on the Crashes module state. 
- To send a crash report if it was in the previous start session.

If you do not want to send anything until user confirmation, you can use MSAppCenter.setEnabled API to temporarily disable the SDK, but please note that in disabled state SDK doesn't collect crashes.

Also we already have the feature request to the main repo about it - [microsoft/appcenter#2004](https://github.com/microsoft/appcenter/issues/2004)

**Comment by MatkovIvan** [comment]
Also, #2170 looks similar. Closing as duplicate, but feel free to reopen/comment if you have more questions.

**Comment by vitwo** [comment]
Question still remains!
For what reason a connection to in.appcenter.ms is established periodically without app crashes?
Which kind of information will be sent?

If "AC just was started and send startService event" is the answer I cannot use the SDK for privacy reasons...

**Comment by AnastasiaKubova** [comment]
Sending crash reports is not only one function of App Center SDK, it also takes care of Analytics, in-app updates, etc. All information which App Center send you can find in the logs (just enable the [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/ios#adjust-the-log-level) before MSAppCenter.start).

**Comment by MatkovIvan** [comment]
If SDK itself is enabled (MSAppCenter.setEnabled API) it sends the information about the application version and list of started modules (in your case - only crashes). The full list of fields you can find in the verbose logs. If you do not want to have any network connections before explicit confirmation, you should disable the SDK until that time.

**Comment by fulldecent** [comment]
Got it // so this is something we want to include in our block list because it is a phone home

**Comment by AnatolyPristensky** [comment]
Hello, `AppCenter.networkRequestsAllowed` API has been added in [4.2.0 version](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.2.0). You can use it to block network requests when you need it.
