### ISSUE TITLE
Define `operation_id` when tracking a customEvent

### ISSUE THREAD

**Issue by jhatzics** [microsoft/appcenter-sdk-apple#2210]
Is it possible somehow to define the operation_id (Application Insights) / correlation_id for a custom event?

I need to correlate mobile app custom events with backend events/dependencies/exceptions using the operation_id.

Is there any to set these top level properties while using the trackEvent?

<img width="625" alt="image" src="https://user-images.githubusercontent.com/1389266/97983613-39869a80-1dde-11eb-9ef9-2921626de21f.png">

**Comment by DmitriyKirakosyan** [comment]
Hi @jhatzics , thanks for getting in touch!

Could you share more details about your idea.
- Why do you want to set/add top level properties? Top level properties are for SDK internal usage only and you don't have access to them on the App Center portal.
- Have you tried using custom properties for `trackEvent`? If you want to use a 'default' property that would be added to all your custom events, I would recommend to implement a custom analytics wrapper, which would set these properties on every `trackEvent` call.

**Comment by jhatzics** [comment]
Hi @DmitriyKirakosyan, thank you for your response.

In [this tutorial ](https://codingcanvas.com/end-to-end-correlation-using-azure-application-insights-for-asp-net-mvc-apps/) you can see the correlation performed automatically by Azure Application Insights on client / server telemetry events. In that scenario operation_id is used to identify a single operation tracked through front and back end Application Insights.

Just a note. Application Insights SDK for JS and C#, allows to track Operations, Dependencies, Traces etc, which utilize the operation_id event property ([Docs](https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation)).

**Comment by DmitriyKirakosyan** [comment]
@jhatzics,

If I understand it correctly, you're trying to use AppCenter Analytics with Application Insights as described [here](https://docs.microsoft.com/en-us/azure/azure-monitor/learn/mobile-center-quickstart), right?
And you're trying to connect mobile and backend events in your dashboard?

So, in this case the custom properties that you're sending with `trackEvent` should be the thing you're looking for.
Try to call API this way:
```swift
MSAnalytics.trackEvent("Video clicked", withProperties: ["operation_id" : "your-operation-id"])
```

I'm not sure how correlations work in Application Insights and whether it does it automatically or you should query it yourself. But having this property set you would be able to query your mobile and backend events based on that "operation_id".

Please correct me if my understanding is wrong.

**Comment by vvechkanov** [comment]
HI!
Hope you are doing well. 
I want to check if our suggestion solves your problem? I will close this request for now but feel free to answer/reopen if you have some additional questions/thoughts.
