### ISSUE TITLE
Crash in Simulator

### ISSUE THREAD

**Issue by ezathashim** [microsoft/appcenter-sdk-apple#2223]
### **Description**

The latest SDK 4.0.0 seems to have a crashy bug when running on iOS. Specifically, I see the crash using iPhone 11 Pro Simulator.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. update the SDK to 4.0.0
2. add a line of code on app launch: 

[MSACAppCenter start: SecretIdentifier
                 withServices: @[
                    [MSACAppCenter class],
                   [MSACCrashes class]
                  ]];

3. run on Simulator and see the crash. It seems to dislike some internal API '[MSACAppCenter initializationPriority]'

Here is the crash log:

2020-11-17 19:04:46.565412-0500 NopaliMobile[8419:2705981] -[MSACAppCenter initializationPriority]: unrecognized selector sent to instance 0x600001ea5650
2020-11-17 19:04:46.579181-0500 NopaliMobile[8419:2705981] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MSACAppCenter initializationPriority]: unrecognized selector sent to instance 0x600001ea5650'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2041daf2 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2042c6f7 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00007fff20422032 ___forwarding___ + 1489
	4   CoreFoundation                      0x00007fff20424068 _CF_forwarding_prep_0 + 120
	5   NopaliMobile                        0x000000010946c69c __30-[MSACAppCenter sortServices:]_block_invoke + 146
	6   CoreFoundation                      0x00007fff203a708d __CFSimpleMergeSort + 74
	7   CoreFoundation                      0x00007fff203a6c3a CFSortIndexes + 395
	8   CoreFoundation                      0x00007fff20407fa2 -[NSArray sortedArrayFromRange:options:usingComparator:] + 632
	9   NopaliMobile                        0x000000010946c5df -[MSACAppCenter sortServices:] + 69
	10  NopaliMobile                        0x000000010946c183 -[MSACAppCenter startServices:withAppSecret:transmissionTargetToken:fromApplication:] + 165
	11  NopaliMobile                        0x000000010946c0b7 -[MSACAppCenter start:withServices:fromApplication:] + 205
	12  NopaliMobile                        0x000000010946ab49 +[MSACAppCenter start:withServices:] + 103
	13  NopaliMobile                        0x00000001092ae8e7 -[AppDelegate application:didFinishLaunchingWithOptions:] + 423
	14  UIKitCore                           0x00007fff2467146d -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 232
	15  UIKitCore                           0x00007fff24672fef -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 3919
	16  UIKitCore                           0x00007fff246789fd -[UIApplication _runWithMainScene:transitionContext:completion:] + 1237
	17  UIKitCore                           0x00007fff23ca37bb -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 122
	18  UIKitCore                           0x00007fff2423120a _UIScenePerformActionsWithLifecycleActionMask + 88
	19  UIKitCore                           0x00007fff23ca42ca __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 198
	20  UIKitCore                           0x00007fff23ca3d8e -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 474
	21  UIKitCore                           0x00007fff23ca40fb -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 819
	22  UIKitCore                           0x00007fff23ca398f -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 345
	23  UIKitCore                           0x00007fff23cabc27 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 178
	24  UIKitCore                           0x00007fff2413afe7 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] + 871
	25  UIKitCore                           0x00007fff2424dab2 _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 240
	26  UIKitCore                           0x00007fff23cab92d -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 361
	27  UIKitCore                           0x00007fff23acf034 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 797
	28  UIKitCore                           0x00007fff23acdade -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 253
	29  UIKitCore                           0x00007fff23acec6d -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 208
	30  UIKitCore                           0x00007fff24676e9c -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 508
	31  UIKitCore                           0x00007fff241633f3 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 358
	32  FrontBoardServices                  0x00007fff25a7e0ae -[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 391
	33  FrontBoardServices                  0x00007fff25aa6b41 __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke.176 + 102
	34  FrontBoardServices                  0x00007fff25a8bad5 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 209
	35  FrontBoardServices                  0x00007fff25aa680f __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke + 352
	36  libdispatch.dylib                   0x000000010a9a59c8 _dispatch_client_callout + 8
	37  libdispatch.dylib                   0x000000010a9a8910 _dispatch_block_invoke_direct + 295
	38  FrontBoardServices                  0x00007fff25acc7a5 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	39  FrontBoardServices                  0x00007fff25acc48b -[FBSSerialQueue _targetQueue_performNextIfPossible] + 433
	40  FrontBoardServices                  0x00007fff25acc950 -[FBSSerialQueue _performNextFromRunLoopSource] + 22
	41  CoreFoundation                      0x00007fff2038c37a __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	42  CoreFoundation                      0x00007fff2038c272 __CFRunLoopDoSource0 + 180
	43  CoreFoundation                      0x00007fff2038b754 __CFRunLoopDoSources0 + 248
	44  CoreFoundation                      0x00007fff20385f1f __CFRunLoopRun + 878
	45  CoreFoundation                      0x00007fff203856c6 CFRunLoopRunSpecific + 567
	46  GraphicsServices                    0x00007fff2b76adb3 GSEventRunModal + 139
	47  UIKitCore                           0x00007fff24675187 -[UIApplication _run] + 912
	48  UIKitCore                           0x00007fff2467a038 UIApplicationMain + 101
	49  NopaliMobile                        0x00000001092cc2a1 main + 97
	50  libdyld.dylib                       0x00007fff20256409 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MSACAppCenter initializationPriority]: unrecognized selector sent to instance 0x600001ea5650'
terminating with uncaught exception of type NSException
CoreSimulator 732.18.0.2 - Device: iPhone 11 Pro (0889D426-14E7-40A5-88E5-0D39A6A04BCF) - Runtime: iOS 14.2 (18B79) - DeviceType: iPhone 11 Pro

### **Details**

1. Which SDK version are you using?
    - 4.0.0
2. Which OS version did you experience the issue on?
    - iOS 14
3. Which Cocoapods version are you using (run `pod --version`)?
    - e.g. N/A
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone 11 emulator
5. What language are you using?
    - [X ] Objective C
    - [ ] Swift
6. What third party libraries are you using?
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by vvechkanov** [comment]
Hi! 
Thank you for contacting us. I reproduce this issue on my side, so I'll label this ad=s a bug, and we will start looking at this.

**Comment by MatkovIvan** [comment]
Hi @ezathashim,
Thanks for getting in touch!
Passing `[MSACAppCenter class]` to the services array is incorrect, please follow [the docs](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios) to grab the code to initialize the SDK. Most likely you wanted to pass `[MSACAnalytics class]` there.

**Comment by ezathashim** [comment]
Awwk - I migrated from an earlier framework and XCode autocorrect suggestions put that there. My apologies!
