### ISSUE TITLE
Found an unexpected Mach-O header code: 0x72613c21

### ISSUE THREAD

**Issue by PotterDai** [microsoft/appcenter-sdk-apple#2224]
### **Description**

After upgrading to the latest SDK for Apple Silicon devices, it constantly report "Found an unexpected Mach-O header code: 0x72613c21"

<img width="747" alt="Screen Shot 2020-11-18 at 8 44 03 AM" src="https://user-images.githubusercontent.com/3758951/99468061-a96a5880-297a-11eb-933c-db5b22c0abe0.png">

And here is the log:

2020-11-18 00:43:48 +0000  Unable to determine platform from macho "......./Contents/Frameworks/AppCenter.framework/Versions/A". Failed with error: "Failed to discover platform for executable ........../Contents/Frameworks/AppCenter.framework/Versions/A/AppCenter"

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Add AppCenter into your App
2. Compile and submit app for notarization.

### **Details**

1. Which SDK version are you using?
    - e.g. 1.5.0
2. Which OS version did you experience the issue on?
    - e.g. iOS 11
3. Which Cocoapods version are you using (run `pod --version`)?
    - e.g. 1.4.0
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. iPhone X physical device, iPhone 8 emulator
5. What language are you using?
    - [ ] Objective C
    - [ ] Swift
6. What third party libraries are you using?
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by MatkovIvan** [comment]
Hi @PotterDai,

Thanks for getting in touch!
Most likely you're embedding/signing AppCenter static framework. Could you please check that? Have you already found the same issue in this repo (#2200)?

**Comment by PotterDai** [comment]
Hi @MatkovIvan ,
Thank you for pointing out! Marking all AppCenter libraries as "Do Not Embed" solved the issue. = )
