### ISSUE TITLE
Ability to ignore postpone of the update

### ISSUE THREAD

**Issue by NickolaySheika** [microsoft/appcenter-sdk-apple#2226]
**Is your feature request related to a problem? Please describe.**
I have an "Update the app" button in my application on which I want to check for updates and and show the user a custom alert to actually download the update or cancel. I want this to be working for all the updates (even non-mandatory). 
I've found out that Distribute.checkForUpdates() doesn't work if user postponed the update on the initial dialog. I see no way in this case to present alert again.

**Describe the solution you'd like**
I would like to be able to ignore if the user postponed the update and be able to still trigger Distribute.checkForUpdates(). Also, would be nice to get result of Distribute.checkForUpdates() - if update exist or not. 

**Describe alternatives you've considered**
Currently, I simply redirect the user to the installation URL which is not the best solution. 

**Additional context**
none

**Comment by MatkovIvan** [comment]
Hi @NickolaySheika,
Thanks for getting in touch! There is 2 ways to achieve this in current version of SDK. You can reset this by just re-enabling distribute module:
```swift
Distribute.enabled = false
Distribute.enabled = true
```

or by removing a flag from user defaults manually (⚠️ not documented way):
```swift
UserDefaults.standard.removeObject(forKey: "MSAppCenterPostponedTimestamp")
```

As for
> Also, would be nice to get result of Distribute.checkForUpdates() - if update exist or not.

We're already tracking this request in https://github.com/microsoft/appcenter-sdk-android/issues/1215. It's filed to Android repo, but we'll do it across all platforms anyway.

**Comment by NickolaySheika** [comment]
I tried the first suggested way and it works. Thanks for your help!
