### ISSUE TITLE
Nullability for attachmentsWithCrashes:forErrorReport: is incorrect

### ISSUE THREAD

**Issue by andalman** [microsoft/appcenter-sdk-apple#2227]
In MSACCrashesDelegate.h, the return value for attachmentsWithCrashes:forErrorReport: is implicitly nonnull (as it is inside an NS_ASSUME_NONNULL_BEGIN/END block).

However, the documentation for this method indicates that nil is an appropriate return value:
"@return The attachments associated with the given error report or nil if the error report doesn't have any attachments."

We have code that returns nil, as per the docs, and our automated builds are failing because it no longer passes Xcode's Analyze.

Is the correct return value now an empty array if the report doesn't have any attachments? If it's still OK to return nil, it would be great if the method signature could be fixed.

**Comment by MatkovIvan** [comment]
Hi @andalman,
Thanks for getting in touch and reporting this! We'll have a look. Marking it as a bug.

**Comment by ConnorQi** [comment]
Hey!
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.
