### ISSUE TITLE
MSDistributeLocalizedString Values not found

### ISSUE THREAD

**Issue by StNebel** [microsoft/appcenter-sdk-apple#2228]
### **Description**

I use App Center / Distribution is v3.3.4
Implemented as a static lib to use it without cocopods.

I get this one:
<img width="402" alt="Bildschirmfoto 2020-11-24 um 11 10 50" src="https://user-images.githubusercontent.com/54270778/100080397-1469d280-2e46-11eb-9273-233fbb1187ea.png">

### **Repro Steps**

1.
Implemented App Center / Distribution is v3.3.4 as a static lib 

2.
```
import AppCenter
import AppCenterDistribute
```
in AppDelegate

3.
`MSAppCenter.start(mySpecialValue, withServices: [MSDistribute.self])`

### **Details**

1. Which SDK version are you using?
    - e.g. v3.3.4
2. Which OS version did you experience the issue on?
    - e.g. iOS 14.2
3. Which Cocoapods version are you using (run `pod --version`)?
    - e.g. use a static lib
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. iPhone SE (2nd) real device
5. What language are you using?
    - [ ] Objective C
    - [x] Swift
6. What third party libraries are you using?
 Standard like RxSwift, SnapKit
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
The error was found on the device of a tester. There are therefore no logs

**Comment by russelarms** [comment]
Hi! Please check out this instruction:
https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/ios#the-alert-that-prompts-users-for-an-update-doesnt-contain-strings-but-just-the-keys-for-them
