### ISSUE TITLE
Carthage --no-use-binaries build ends up in Build/iOS/Static directory

### ISSUE THREAD

**Issue by bencallis** [microsoft/appcenter-sdk-apple#2230]
### **Description**

Framework ends up in a different directory when --no-use-binaries is used with Carthage.

If --no-use-binaries is used the project is built from scratch and the framework ends up in a **Static** directory `/Carthage/Build/iOS/Static/AppCenter.framework `

Without the flag a prebuilt binary is used and the framework ends up in the root iOS directory as expected
`/Carthage/Build/iOS/AppCenter.framework `

I would expect the frameworks to be in the same directory (`/Carthage/Build/iOS/AppCenter.framework`) irrespective if it is a prebuilt binary vs built on the machine. 

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Add app centre to your cart file
2. run `carthage bootstrap --platform iOS --no-use-binaries `

![Static](https://user-images.githubusercontent.com/1911951/100134676-78a98800-2e80-11eb-9bc9-c532c49e8753.jpg)

### **Details**

1. Which SDK version are you using?
 4.0.0
2. Which OS version did you experience the issue on?
N/A
3. Which Carthage version are you using 
0.36.0

**Comment by MatkovIvan** [comment]
Hi @bencallis,
Thanks for getting in touch!

It's [expected Carthage folder](https://github.com/Carthage/Carthage/blob/158dacdd5626dd00190180c5c0aec598f61a2b22/Source/CarthageKit/Xcode.swift#L314-L315) for static framework build. I'd suggest you open an issue in https://github.com/Carthage/Carthage if you want to change the behavior of the Carthage tool.
As a workaround you can apply recursive scan for frameworks search path as described in [this article](https://medium.com/fluxom/building-static-frameworks-under-carthage-ed010c904296).

Closing this as it doesn't look like App Center issue, but feel free to comment/re-open if you have more questions.
