### ISSUE TITLE
Swift compile error with v4.0 - using 'Log'

### ISSUE THREAD

**Issue by zulfishah** [microsoft/appcenter-sdk-apple#2234]
After updating to version 4.0 of the AppCenter library, a new issue has cropped up, where I get this Swift compile error:

'Log' is ambiguous for type lookup in this context

Note: I have a CoreData model entity called 'Log' in my app. It unfortunately doesn't have a namespace with it. When I build with the latest update, this line produces the above error:

let fetchRequest = NSFetchRequest<Log>(entityName: "Log")

### **Details**

1. Which SDK version are you using?
    - v4.0
2. Which OS version did you experience the issue on?
    - iOS13 / iOS14
3. Which Cocoapods version are you using (run `pod --version`)?
    - Carthage v0.35
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. iPhone simulator
5. What language are you using?
    - [x] Objective C
    - [x] Swift
6. What third party libraries are you using?
- Appcenter

7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
- this is a compile error
- the error logs show this:

CJDataKit.Log:1:12: note: found this candidate
open class Log : NSManagedObjectCJBase, ManagedObjectSpotlightSupport {
           ^
AppCenter.Log:1:17: note: found this candidate
public protocol Log : NSObjectProtocol {

Can the "Log" object be renamed for AppCenter, into something that has a namespace?

**Comment by MatkovIvan** [comment]
Hi @zulfishah,
Thanks for getting in touch!
Namespacing is implicit in Swift, meaning that all types, variables (etc) are automatically scoped by the module. You need to put the package name in front of the class name to resolve the conflict. Something like: `YourTargetName.Log`

> Can the "Log" object be renamed for AppCenter, into something that has a namespace?

Real name of this class is MSACLog, it should be used as-is in Objective-C that doesn't have namespaces. Swift has another convection, all classes there are in namespaces.

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.
