### ISSUE TITLE
Crash on MSACSessionHistoryInfo

### ISSUE THREAD

**Issue by yichengchen** [microsoft/appcenter-sdk-apple#2240]
### **Description**

Some user report crash at mac app launch https://github.com/yichengchen/clashX/issues/350

`Application Specific Information:
Crashing on exception: *** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (MSACSessionHistoryInfo) for key (NS.objects) because no class named "MSACSessionHistoryInfo" was found; the class needs to be defined in source code or linked in from a library (ensure the class is part of the correct target). If the class was renamed, use setClassName:forClass: to add a class translation mapping to NSKeyedUnarchiver`
```

Application Specific Backtrace 1:
0 CoreFoundation 0x00007fff204826af __exceptionPreprocess + 242
1 libobjc.A.dylib 0x00007fff201ba3c9 objc_exception_throw + 48
2 Foundation 0x00007fff21287c20 ___collectionClasses_block_invoke + 0
3 Foundation 0x00007fff212273e0 -[NSCoder(Exceptions) __failWithExceptionName:errorCode:format:] + 378
4 Foundation 0x00007fff211424d9 _decodeObjectBinary + 652
5 Foundation 0x00007fff211447a9 -[NSKeyedUnarchiver _decodeArrayOfObjectsForKey:] + 848
6 Foundation 0x00007fff2115cb0c -[NSArray(NSArray) initWithCoder:] + 161
7 Foundation 0x00007fff21142d1b _decodeObjectBinary + 2766
8 Foundation 0x00007fff21142125 _decodeObject + 152
9 Foundation 0x00007fff21142010 -[NSKeyedUnarchiver decodeObjectForKey:] + 162
10 Foundation 0x00007fff211ff6cd +[NSKeyedUnarchiver unarchiveObjectWithData:] + 79
11 ClashX 0x0000000109538967 -[MSSessionContext init] + 180
12 ClashX 0x0000000109538899 __34+[MSSessionContext sharedInstance]_block_invoke + 52
13 libdispatch.dylib 0x00007fff201657c7 _dispatch_client_callout + 8
14 libdispatch.dylib 0x00007fff2016696b dispatch_once_callout + 20
15 ClashX 0x0000000109538862 +[MSSessionContext sharedInstance] + 45
16 ClashX 0x000000010953aa23 -[MSAppCenter configureWithAppSecret:transmissionTargetToken:fromApplication:] + 462
17 ClashX 0x000000010953ad94 -[MSAppCenter start:withServices:fromApplication:] + 166
18 ClashX 0x0000000109539c3d +[MSAppCenter start:withServices:] + 103
19 ClashX 0x00000001094bbcec $s6ClashX11AppDelegateC17registCrashLoggeryyFyycfU + 188
20 ClashX 0x00000001094ccaa9 $sIeg_IeyB_TR + 25
21 libdispatch.dylib 0x00007fff201657c7 _dispatch_client_callout + 8
22 libdispatch.dylib 0x00007fff20168195 _dispatch_continuation_pop + 423
23 libdispatch.dylib 0x00007fff20178550 _dispatch_source_invoke + 2079
24 libdispatch.dylib 0x00007fff20171a3f _dispatch_main_queue_callback_4CF + 613
25 CoreFoundation 0x00007fff20445960 CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE + 9

```
### **Repro Steps**

Please list the steps used to reproduce your issue.

1. unknown

### **Details**

1. Which SDK version are you using?
    - AppCenter/Analytics (3.2.0):
2. Which OS version did you experience the issue on?
    - macOS11
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.10
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Mac 
5. What language are you using?
    - [ ] Objective C
    - [x] Swift
6. What third party libraries are you using?
 listed in https://github.com/yichengchen/clashX/blob/master/Podfile
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
 Can not reproduce on my computer

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! Could you please clarify which version of App Center SDK you use before? Have you downgraded the SDK version after updating App Center SDK to the 4.0.0 version?

**Comment by yichengchen** [comment]
I am using the latest AppCenter SDK 4.0.0, I haven't downgraded the sdk on my version update. But I am not sure does my user downgraded the app version. Maybe I can ask him

**Comment by yichengchen** [comment]
Sorry, I recheck the crash report, It was using the appcenter 3.2.0, I will contact the user does he downgrade the app version
