### ISSUE TITLE
Release 4.1.0 not available

### ISSUE THREAD

**Issue by lrun-cmck** [microsoft/appcenter-sdk-apple#2247]
Hello ! Thanks for the hard work on this SDK. I just saw that there's a changelog for version 4.1.0 from 4 days ago, but we cannot use it due to fact no tag `4.1.0` was pushed. I'm wondering if this is on purpose to not be released yet or somebody forgot. Thanks 🤘🏻

**Comment by MatkovIvan** [comment]
It was under testing. The release is here - https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.1.0
CocoaPods will be available a bit later.

**Comment by lrun-cmck** [comment]
Thanks a lot !

**Comment by MatkovIvan** [comment]
Thank you for having an interest and for making sure that things are going as expected 😄
