### ISSUE TITLE
Cannot archive iOS apps after upgrading to the 4.1.0 release

### ISSUE THREAD

**Issue by elitalon** [microsoft/appcenter-sdk-apple#2251]
### **Description**
Our iOS apps fail to archive after upgrading AppCenter SDK to [4.1.0](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.1.0). This is the error we see during linking:

```
ld: in /Users/<redacted>/Library/Developer/Xcode/DerivedData/<redacted>-cyiamcntrweteseuezdusbdvsmme/Build/Intermediates.noindex/ArchiveIntermediates/<redacted>/BuildProductsPath/Release-iphoneos/AppCenterAnalytics.framework/AppCenterAnalytics(MSACAnalyticsAuthenticationProvider.o), building for iOS, but linking in object file built for Mac Catalyst, file '/Users/<redacted>/Library/Developer/Xcode/DerivedData/<redacted>-cyiamcntrweteseuezdusbdvsmme/Build/Intermediates.noindex/ArchiveIntermediates/<redacted>/BuildProductsPath/Release-iphoneos/AppCenterAnalytics.framework/AppCenterAnalytics' for architecture arm64
```

Downgrading to AppCenter SDK 4.0.0 with the exact same app and code makes archiving successful again.

### **Repro Steps**
1. Upgrade AppCenter SDK to [4.1.0](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.1.0)
2. Clean the Xcode project
3. Archive the Xcode project

I created a [sample project](https://github.com/microsoft/appcenter-sdk-apple/files/5754108/AppCenterSample.zip) that reproduces the issue (you need to run `pod install` first).

### **Details**
1. Which SDK version are you using?
    - [4.1.0](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.1.0)
2. Which OS version did you experience the issue on?
    - All
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.9.3
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - None, the issue occurs when archiving for any iOS device
5. What language are you using?
    - [ ] Objective C
    - [x] Swift
6. What third party libraries are you using?
    - Not relevant
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
    - Not relevant

**Comment by Jamminroot** [comment]
Hey, @elitalon, thanks for reaching out, and big thanks for providing us with sample project.
Please let me some time to have a look at the project you've sent.

**Comment by libe** [comment]
Hello,

I am reproducing the same problem and I cannot build for a device:

`
ld: in /Users/libe/Library/Developer/Xcode/DerivedData/TestApp-gzecwbbvzjolndgeheissfvpqrks/Build/Intermediates.noindex/ArchiveIntermediates/TestApp/BuildProductsPath/Release-iphoneos/AppCenterAnalytics.framework/AppCenterAnalytics(MSACAnalytics.o), building for iOS, but linking in object file (/Users/libe/Library/Developer/Xcode/DerivedData/TestApp-gzecwbbvzjolndgeheissfvpqrks/Build/Intermediates.noindex/ArchiveIntermediates/TestApp/BuildProductsPath/Release-iphoneos/AppCenterAnalytics.framework/AppCenterAnalytics(MSACAnalytics.o)) built for Mac Catalyst, for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

My app is an iOS app and not a Catalyst one.

Thanks in advance for your help!

**Comment by russelarms** [comment]
Thanks, @libe, it worked for me too. Apparently, it is a bug in Cocoapods < 1.10.0. I see a lot of fixes for XCFramework implementation in the Cocoapods changelog:
https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md
So I encourage you to update your cocoapods version to 1.10+.
