### ISSUE TITLE
AppCenterAnalytics built for wrong architecture (Mac Catalyst) in 4.1.0

### ISSUE THREAD

**Issue by tumatauenga** [microsoft/appcenter-sdk-apple#2255]
### **Description**

We're having an issue with the latest release of the library via Cocoapods, where we get an error similar to the following:

AppCenterAnalytics.framework/AppCenterAnalytics(MSACAnalyticsAuthenticationProvider.o), building for iOS, but linking in object file (AppCenterAnalytics.framework/AppCenterAnalytics(MSACAnalyticsAuthenticationProvider.o)) built for Mac Catalyst, file 'AppCenterAnalytics.framework/AppCenterAnalytics' for architecture arm64

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install the latest version of the AppCenter SDK via Cocoapods
2. Build for a physical device

### **Details**

1. Which SDK version are you using?
    - 4.1.0
2. Which OS version did you experience the issue on?
    - iOS 14.3
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.10.0
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone 11 physical device
5. What language are you using?
    - Swift
6. What third party libraries are you using?
    - AFNetworking
    - AppAuth
    - AppCenter
    - Branch
    - Connectivity
    - FBSDKCoreKit
    - FBSDKLoginKit
    - GoogleConversionTracking
    - GoogleIDFASupport
    - GoogleSignIn
    - GTMAppAuth
    - GTMSessionFetcher
    - KeychainAccess
    - MarqueeLabel
    - Mixpanel-swift
    - SDWebImage
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
    - Unfortunately it's not at runtime that we get this error - it's at compile time, so no logs are available from `MSAppCenter`

**Comment by russelarms** [comment]
Hi there! Thanks for reaching out, it looks pretty similar to https://github.com/microsoft/appcenter-sdk-apple/issues/2251
But I see that you use pods 1.10 which should work fine. I'll check it and get back to you soon.

**Comment by tumatauenga** [comment]
Sorry you're right - I had updated to 1.10.0, but my co-worker hadn't, and he was the one having this issue.  He's updated to 1.10.1 now and all appears to be well again. Sorry for the unnecessary ticket, I had a quick look but didn't see that it was a duplicate - I obviously didn't look hard enough.
