### ISSUE TITLE
Connecting to Managed Google play private store via intune  

### ISSUE THREAD

**Issue by liveinvarun** [microsoft/appcenter-sdk-apple#2258]
I have app distributed via intune and i use managed google play via private store distribution.
I wanted to integrate it with azure devops. 
Previously it was possible. Can you let me know how should i connect it ?
Is it possible to connect this way?
I had tried connecting via appcenter Store and then INTune company portal option and then tried to reach the intune distribution. 
Cam you provide some help how to connect it to the private appstore that we have maintained from Appcenter.

Managed Google Play private (LOB) app publishing directly in the Intune console
https://docs.microsoft.com/en-us/mem/intune/apps/apps-add-android-for-work
Can we connect to such LOB private apps via appcenter

**Comment by vvechkanov** [comment]
HI @liveinvarun!
As far as I understand you have a problem with integrating your app with azure. If I am right then you can ask in azure support. If your problem is connected with AppCenter SDK, could you please provide some more details how you configure AppCenter SDK, and what you want to achieve.

**Comment by liveinvarun** [comment]
We have a app that is published using Managed GooglePlay. We have Appcenter to Intune store connect done for the distrubution for the company apps. 
https://support.google.com/a/answer/2494992#zippy=%2Cmanaging-private-apps-in-admin-console-versus-google-play-console%2Cimportant-information-about-app-publishing%2Cedit-advanced-private-app-details
So we have an app that is in private mode and is created using Admin Console.  
we are trying to push the app via appcenter to intune which then manages to push it to the priavate app distributions. Somehow this is not happening and we dont see the app listed in appcenter afte the intune connected store.

So is it not possiable to see a private app crated by Admin Console to be shown in Appcenter?

**Comment by AnastasiaKubova** [comment]
Hi! Not sure that this issue related to SDK. Could you please open the intercom ticket about your question (the question symbol on the right top corner of the App Center portal ).
I’m closing this issue, but feel free to reopen this issue if you have additional questions.
