### ISSUE TITLE
The Crashes SDK stopped reporting crashes since Feb. 05 2021.

### ISSUE THREAD

**Issue by fbrescia** [microsoft/appcenter-sdk-apple#2266]
### **Description**

The Crashes SDK suddenly stopped reporting crashes since Feb. 05 2021.
This is affecting all versions of our app.

### **Details**

1. Which SDK version are you using?
    - 3.3.4
2. Which OS version did you experience the issue on?
    - any OS version
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.9.0
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - irrelevant / physical devices
5. What language are you using?
    - [X] Objective C
    - [ ] Swift

Here is a screenshot of the crash reporting issue:
<img width="2275" alt="crashes" src="https://user-images.githubusercontent.com/1257015/107197239-ee3ee200-69f3-11eb-8fec-f6fac100e54a.png">

**Comment by fbrescia** [comment]
Seems to be a server-side issue.

**Comment by MatkovIvan** [comment]
Yep, it doesn't look like the SDK side.
As mentioned in the issue template
> If your issue is not related to using our Apple SDK but rather about the product experience like the portal or CI, please create an issue on https://github.com/Microsoft/appcenter instead.

Please open a support ticket for this, so our support team and engineers from backend side will help you. Open the help menu in the upper right corner of the App Center portal: ? > Contact support

In case if you still think that it's SDK problem, please collect verbose logs from device (7th point in issue template) and share it with us. Thanks.

**Comment by fbrescia** [comment]
Thank you, it's definitely server-side. I'm closing the issue.
