### ISSUE TITLE
Location of crash reports in the file system

### ISSUE THREAD

**Issue by fmoraes74** [microsoft/appcenter-sdk-apple#2270]
### **Description**

Is there a location where crash reports can be found? If a user is reporting problems, I need to know which problem they are hitting by getting the actual crash report from the customer's machine. 

So, where are the crash reports located so that I can direct the user to collect them for problem determination?

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
You can find crash reports by the path  "[NSApplicationSupportDirectory](https://developer.apple.com/documentation/foundation/nssearchpathdirectory/nsapplicationsupportdirectory)/[bundle Identifier]/com.microsoft.appcenter/crashes"
You can take a look at it [here](https://github.com/microsoft/appcenter-sdk-apple/blob/51da048c65cdfc12ff804ad9eac983bddfefcd65/AppCenter/AppCenter/Internals/Util/MSACUtility%2BFile.m#L149).

**Comment by AnastasiaKubova** [comment]
We haven't heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.

**Comment by schmidt9** [comment]
In my case directory `crashes` seems to be always empty even before a crash report does gets sent, `hasCrashes` is always empty for instance even when checking inside `- (void)crashes:(MSACCrashes *)crashes willSendErrorReport:(MSACErrorReport *)errorReport`

checked on iOS 10.3.2 iPhone SE real device

```
NSURL *crashesURL = [[[NSFileManager.defaultManager URLsForDirectory:NSApplicationSupportDirectory inDomains:NSUserDomainMask].firstObject URLByAppendingPathComponent:@"com.microsoft.appcenter"] URLByAppendingPathComponent:@"crashes"];
    NSError *error;
    BOOL hasCrashes = [NSFileManager.defaultManager contentsOfDirectoryAtPath:crashesURL.path error:&error].count > 0;
```
