### ISSUE TITLE
CocoaPods integration as source

### ISSUE THREAD

**Issue by ghugues** [microsoft/appcenter-sdk-apple#2273]
**Is your feature request related to a problem? Please describe.**
We commit CocoaPods dependencies in order to ensure reproductible builds even after remote sources (AWS links, etc...) are gone. Dependencies provided as precompiled binaries take a lot of space, especially when they are XCFrameworks. We're also running into CocoaPods and/or XCFrameworks limitations when integrating different sets of subspecs in the main app and an app extension and this would probably solve that as well.

**Describe the solution you'd like**
Since AppCenter is open source, it would be great if the CocoaPods integration was provided as source instead of a precompiled framework. This is usually how open source frameworks do it.

**Describe alternatives you've considered**
None at the moment, apart from attempting that in a fork if this is not acceptable for some reason.

**Additional context**
Can you let me know if this has been considered in the past but abandoned due to some technical limitation ?

**Comment by ghugues** [comment]
Hello @DmitriyKirakosyan,
It's been a year. This would still be a very useful feature, at least for us.
Best,

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
