### ISSUE TITLE
AppCenter Dependency import failed usig SPM

### ISSUE THREAD

**Issue by Kapitaliste1** [microsoft/appcenter-sdk-apple#2294]
Hello, 

i am using XCode 12.4 with swift-tools-version:5.3 

I tried to import the library into my project using Swift Package Manager.
The dependencies are downloaded properly but XCode keeps saying that AppCenter can't be found.

Please describe the issue you are facing using the SDK.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a fresh Swift Package Manager project 
2. add AppCenter refence in the package description as a dependency
3. save and wait for XCode to download the related dependencies
<img width="1435" alt="Screen Shot 2021-04-23 at 11 10 34 AM" src="https://user-images.githubusercontent.com/22551688/115896354-531dac00-a429-11eb-84d3-34bd81b8a4dc.png">
<img width="1432" alt="Screen Shot 2021-04-23 at 11 10 50 AM" src="https://user-images.githubusercontent.com/22551688/115896358-544ed900-a429-11eb-8525-67abd3acd284.png">

### **Details**

1. Which SDK version are you using?
    - e.g. 4.1.1
2. Which OS version did you experience the issue on?
    - e.g. iOS 14
3. Which Xcode version did you build the app with?
    - e.g. Xcode 12.4
5. Which Cocoapods version are you using (run `pod --version`)?
    - e.g. 1.10.1
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. iPhone 12 physical device, iPhone 11 emulator
7. What language are you using?
    - [ ] Objective C
    - [x] Swift
8. What third party libraries are you using?
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by DmitriyKirakosyan** [comment]
Hi @Kapitaliste1,

Thank you for getting in touch with us!
I will try to reproduce it and get back to you shortly.

**Comment by DmitriyKirakosyan** [comment]
@Kapitaliste1 Sorry for the delay,

The AppCenter package consists of tree products: `AppCenterAnalytics`, `AppCenterCrashes` and `AppCenterDistribute`.
So to reference any of these products in your target's dependencies, you will have to declare it this way:
```
targets: [
  .target(
    name: "First",
    dependencies: [.product(name: "AppCenterAnalytics", package: "AppCenter")]
]
```

**Comment by Kapitaliste1** [comment]
@DmitriyKirakosyan  Thank you

**Comment by cuzv** [comment]
@Kapitaliste1 Hey, I got the same issue here. And I use the `.product`  method declare dependencies, Instead of working well,  It just don't resolving packages.

```Swfit
// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "AppCenterResolvingPackageIssueReproduce",
    products: [
        .library(
            name: "AppCenterResolvingPackageIssueReproduce",
            targets: ["AppCenterResolvingPackageIssueReproduce"]),
    ],
    dependencies: [
        .package(url: "https://github.com/microsoft/appcenter-sdk-apple", .upToNextMajor(from: "4.1.1")),
    ],
    targets: [
        .target(
            name: "AppCenterResolvingPackageIssueReproduce",
            dependencies: [
                .product(name: "AppCenterAnalytics", package: "AppCenter"),
                .product(name: "AppCenterCrashes", package: "AppCenter"),
            ]),
        .testTarget(
            name: "AppCenterResolvingPackageIssueReproduceTests",
            dependencies: ["AppCenterResolvingPackageIssueReproduce"]),
    ]
)
```

<img width="893" alt="image" src="https://user-images.githubusercontent.com/5976127/116178628-7d80a980-a748-11eb-820e-c668bf11b79d.png">

You could clone this [demo project](https://github.com/cuzv/AppCenterResolvingPackageIssueReproduce) to checkout

**Comment by DmitriyKirakosyan** [comment]
Hi @cuzv 

You need to add `name: "AppCenter"` in your product deps, like this:
```
dependencies: [
        .package(name: "AppCenter", url: "https://github.com/microsoft/appcenter-sdk-apple", .upToNextMajor(from: "4.1.1")),
    ],
```

**Comment by cuzv** [comment]
@DmitriyKirakosyan Thanks!  Lol...
