### ISSUE TITLE
AppCenter logUrl purpose

### ISSUE THREAD

**Issue by johnborges** [microsoft/appcenter-sdk-apple#2296]
I can't seem to find any info on this property in the docs. What are use cases for changing this property?

`AppCenter.logUrl = "{logUrl}"`

**Comment by DmitriyKirakosyan** [comment]
Hi @johnborges 

The property `logUrl` is used for SDK team internal testing only. It is used to specify the base server url the logs will be sent to.
Basically, you can ignore this property.

Please feel free to reopen the issue if you have more questions.
