### ISSUE TITLE
AppCenterDistribute is not compiling XCFramework

### ISSUE THREAD

**Issue by apps4everyone** [microsoft/appcenter-sdk-apple#2298]
AppCenterDistribute is not compiling XCFramework at: `return (BOOL)[sharedApp performSelector:@selector(openURL:) withObject:url];`

https://github.com/microsoft/appcenter-sdk-apple/blob/5dce272f5080158be168e7dacea10d6f7bf4b67e/AppCenterDistribute/AppCenterDistribute/MSACDistribute.m#L688

**Comment by DmitriyKirakosyan** [comment]
Hi @apps4everyone 

Thank you for reporting this issue.
It is happening when compiling with Xcode 12.5, right?

I will create a bug on our board.

**Comment by apps4everyone** [comment]
> Hi @apps4everyone
> 
> Thank you for reporting this issue.
> It is happening when compiling with Xcode 12.5, right?
> 
> I will create a bug on our board.

Yes exactly with Xcode 12.5 and also with `carthage update --use-xcframeworks --no-use-binaries --new-resolver`. Thx for the quick reply and Bug ticket.

**Comment by apps4everyone** [comment]
The problem with `carthage` is the `swift_version 5.4`. This forces the local build because there is (not yet) a binary for this. Only 5.3!

**Comment by DmitriyKirakosyan** [comment]
Hi @apps4everyone 

The changes were just merged into `develop`: https://github.com/microsoft/appcenter-sdk-apple/pull/2301
I'll let you know when it is released.

**Comment by apps4everyone** [comment]
any news here? thx

**Comment by AnastasiaKubova** [comment]
We are starting the next SDK release, so I hope it will be available in a couple of weeks. We will notify here when the fix will be released.

**Comment by AnastasiaKubova** [comment]
The fix has been released in the [4.2.0](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.2.0) version of App Center SDK. Please update App Center to the latest version and let me know if this issue still persists.
