### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by JCpoz123** [microsoft/appcenter-sdk-apple#2299]
### **Description**

We have a NativeScript app, using NS plugin for AppCenter (nativescript-microsoft-appcenter).  After upgrading to XCode 12.2, the app build fails with this error:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ASWebAuthenticationSession", referenced from:
      objc-class-ref in AppCenterDistribute(MSACDistribute.o)
ld: symbol(s) not found for architecture x86_64

### **Repro Steps**

Please list the steps used to reproduce your issue.

1.  Create new app using NativeScript CLI v6.8.0 (any version)
2.  Install nativescript-microsoft-appcenter via npm
3. tns build ios

### **Details**

1. Which SDK version are you using?
    - 4.1.1
2. Which OS version did you experience the issue on?
    - n/a (build issue)
3. Which Xcode version did you build the app with?
    - Xcode 12.2 (but building via NativeScript CLI v 6.8.0)
5. Which Cocoapods version are you using (run `pod --version`)?
    - 1.10.1
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - n/a (build error)
7. What language are you using?
    - TypeScript
8. What third party libraries are you using?
   - Using NativeScript framework
   - nativescript-microsoft-appcenter v2.0.0
   - https://www.npmjs.com/package/nativescript-microsoft-appcenter

9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by DmitriyKirakosyan** [comment]
Hi @JCpoz123 

Thank you for reaching out to us!

This issue was fixed recently in PR https://github.com/microsoft/appcenter-sdk-apple/pull/2284.

I will keep this thread open until the fix is released.

**Comment by MatkovIvan** [comment]
@JCpoz123 you can fix it with current version by manually adding `AuthenticationServices` system dependency.

**Comment by AnastasiaKubova** [comment]
The fix has been released in the [4.2.0](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.2.0) version of App Center SDK. Please update App Center to the latest version and let me know if this issue still persists.
