### ISSUE TITLE
Can't override appVersion or appName 

### ISSUE THREAD

**Issue by cjappl** [microsoft/appcenter-sdk-apple#2302]
### **Description**

I can't determine how to override the appVersion or appName, but it appears it's possible if MSACPropertyConfigurator.h is to be believed.

```
/**
 * Override the application version.
 *
 */
@property(nonatomic, copy) NSString *_Nullable appVersion;

/**
 * Override the application name.
 *
 */
@property(nonatomic, copy) NSString *_Nullable appName;

```

### **Repro Steps**

Our analytics are very simple at the moment, this is the entirety of the code:

```
...
        [MSACAppCenter start:appUid withServices:@[[MSACAnalytics class]]];
        NSString* typeName = [NSString stringWithUTF8String:type];
        NSString* hostName = [NSString stringWithUTF8String:hostName];
    
        NSDictionary *properties = @{@"Name" : hostName, @"Type" : typeName};
    
        [MSACAnalytics trackEvent:@"Host" withProperties: properties];
...
```

Does anyone know how I can set a custom appName or appVersion? Apologies if I'm missing something obvious, I don't consider myself an Objective C pro!

### **Details**

1. Which SDK version are you using?
    - 4.1.1
2. Which OS version did you experience the issue on?
    - OSX Catalina
3. Which Xcode version did you build the app with?
    - Xcode 12.4
5. Which Cocoapods version are you using (run `pod --version`)?
    - N/A
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - MBP
7. What language are you using?
    - [ ] Objective C
    - [ ] Swift
8. What third party libraries are you using?
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
N/A

**Comment by russelarms** [comment]
Hi @cjappl, thanks for reaching out!
App Center SDK doesn't have a public API to alter an app`s version or an app`s name.
`MSACPropertyConfigurator` is for internal use only.

**Comment by cjappl** [comment]
Thanks @russelarms for the info!

Is there a formal way to request a feature for this?

We are in a bit of a unique position (audio plug-ins) where we run our code inside of another app.

For example our "Awesome Example Plugin v10.1" may run inside "Pro Tools v2021.1.0"

When we start our analytics, it records our app name and version as "Pro Tools" "2021.1.0". This gets especially messy if we use another plug-in in the same session (which is almost always the case).

We could always do a custom event, it'd be nice to have an easy way to override this information somewhere.

**Comment by bluecrowbar** [comment]
@cjappl I'm using `CrashesDelegate` for that.

```swift
public func crashes(_ crashes: Crashes, shouldProcess errorReport: ErrorReport) -> Bool {
    errorReport.device.setValue("1.0", forKey: "appVersion")
    errorReport.device.setValue("1", forKey: "appBuild")
    return true
}
```

**Comment by russelarms** [comment]
```
public func crashes(_ crashes: Crashes, shouldProcess errorReport: ErrorReport) -> Bool {
    errorReport.device.setValue("1.0", forKey: "appVersion")
    errorReport.device.setValue("1", forKey: "appBuild")
    return true
}
```
I believe the above solution is not enough if we're talking about sending analytics events.
@cjappl I've tagged this issue as a feature request, but I don't have an ETA for it.
If it's urgent you can fork and modify the SDK yourself to alter the required fields (and probably create a contribution to this repo 😄 ).

**Comment by cjappl** [comment]
Thanks @russelarms ! 

Keep me posted. We will consider doing a PR if custom events can't hold us over until the feature is implemented.

**Comment by DmitriyKirakosyan** [comment]
Hi @cjappl , we already have a similar feature request https://github.com/microsoft/appcenter/issues/1313. The changes will affect all platforms, so I'm closing it as a duplicate. Let's follow the progress in the main feature request.
