### ISSUE TITLE
How to use MSACWrapperCrashesHelper.unprocessedCrashReports?

### ISSUE THREAD

**Issue by schmidt9** [microsoft/appcenter-sdk-apple#2303]
### **Description**
I try to implement the following: wait until crash reports (if any) are sent, then launch main app logic (to solve case where a crash may occur on app start while crash reporting system may not be ready or reports from previous failed launches cannot be sent in time).
So there are 2 cases:
- if there are no reports, proceed immediately
- if there are reports, wait until they are sent (show wait screen and hide it afterwards based on methods of `MSACCrashesDelegate`)

I try to handle these cases using `MSACWrapperCrashesHelper.unprocessedCrashReports`, with no avail though because it blocks execution even in `didSetUpCrashHandlers` method of `MSACCrashHandlerSetupDelegate`.

As per docs `MSACWrapperCrashesHelper.unprocessedCrashReports` "will block until the service starts". So my idea was the service should have been started when `didSetUpCrashHandlers` is called, obviously that is wrong. 

So my questions are: 
- how can I check properly if there are unsent reports on app start? 
- when and how could I safely use `MSACWrapperCrashesHelper.unprocessedCrashReports`?

Reasons for not using `MSACCrashes.hasCrashedInLastSession`:
- not working with attached debugger
- not handling case where unsent report might be left even if there was no crash in last session (for instance reports could not be sent because of missing internet connection)

### **Example**

```
- (void)setupCrashReporting
{
    MSACWrapperCrashesHelper.crashHandlerSetupDelegate = self;

    MSACCrashes.delegate = self;

    // Use 20 MB for storage.
    [MSACAppCenter setMaxStorageSize:(20 * 1024 * 1024) completionHandler:^(BOOL success) {
        if (!success) {
            NSLog(@"Unable to set max storage size for App Center logging");
        }
    }];

    [MSACAppCenter setLogLevel:MSACLogLevelVerbose];

    [MSACAppCenter start:@"secret" withServices:@[MSACAnalytics.class, MSACCrashes.class]];
}

#pragma mark - MSACCrashHandlerSetupDelegate

- (void)didSetUpCrashHandlers
{
    NSLog(@"PRE");
    NSUInteger count = MSACWrapperCrashesHelper.unprocessedCrashReports.count;
    NSLog(@"POST"); // <-- it gets never executed because of lock on prev line

    // ...
}
```

### **Details**

1. Which SDK version are you using?
    - 4.1.1
2. Which OS version did you experience the issue on?
    - iOS 10.3.2
3. Which Xcode version did you build the app with?
    - Xcode 12.4
5. Which Cocoapods version are you using (run `pod --version`)?
    - 1.10.1
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone 5S physical device
7. What language are you using?
    - [x] Objective C
    - [ ] Swift
8. What third party libraries are you using? - for crash reporting AppCenter only
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
```
[AppCenter] VERBOSE: -[MSACDelegateForwarder addTraceBlock:]_block_invoke_2/88 Start buffering traces.
[AppCenter] DEBUG: -[MSACDelegateForwarder setEnabledFromPlistForKey:]_block_invoke/278 Delegate forwarder for info.plist key 'AppCenterAppDelegateForwarderEnabled' enabled. It may use swizzling.
[AppCenter] VERBOSE: +[MSACDelegateForwarder flushTraceBuffer]/106 Stop buffering traces, flushed.
[AppCenter] DEBUG: -[MSACSessionContext init]/42 3 session(s) in the history.
[AppCenter] VERBOSE: -[MSACSessionContext setSessionId:]/66 Stored new session with id:(null) and timestamp: 2021-05-20 08:54:51 +0000.
[AppCenter] DEBUG: -[MSACUserIdContext init]/54 3 userId(s) in the history.
[AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
[AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
[AppCenter] INFO: -[MSACHttpClient networkStateChanged:]/204 Internet connection is up.
[AppCenter] DEBUG: -[MSACDBStorage initWithSchema:version:filename:]_block_invoke/31 SQLite global configuration successfully updated.
[AppCenter] INFO: -[MSACAppCenter configureWithAppSecret:transmissionTargetToken:fromApplication:]/349 App Center SDK configured successfully.
[AppCenter] VERBOSE: -[MSACAppCenter startServices:withAppSecret:transmissionTargetToken:fromApplication:]/375 Start services MSACCrashes, MSACAnalytics from an application
[AppCenterCrashes] DEBUG: -[MSACCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/691 EnableUncaughtExceptionHandler is set to YES
[AppCenterCrashes] VERBOSE: -[MSACCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/701 Enabled Mach exception handler.
[AppCenter] DEBUG: -[MSACDBStorage setMaxStorageSize:completionHandler:]/457 Found 15 pages in the database.
[AppCenter] INFO: -[MSACDBStorage setMaxStorageSize:completionHandler:]/482 Changed maximum database size to 20971520 bytes.
[AppCenterCrashes] WARNING: -[MSACCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/715 Detecting crashes is NOT enabled due to running the app with a debugger attached.
PRE
```

**Comment by russelarms** [comment]
Hi @schmidt9!

> how can I check properly if there are unsent reports on app start?

There's no public API for this exactly, but with some custom counter logic around the following callbacks, I guess you can achieve the mentioned behavior.
1. `MSACCrashes.hasCrashedInLastSession`
2. And https://docs.microsoft.com/en-us/appcenter/sdk/crashes/ios#get-information-about-the-sending-status-for-a-crash-log
`willSendErrorReport` that will resolve into `didSucceedSending/didFailSending` callbacks.

> Reasons for not using MSACCrashes.hasCrashedInLastSession:
> 
> not working with attached debugger

The debugger only prevents the app from a crash and the SDK from catching it. After restart `hasCrashedInLastSession` is working fine.

> when and how could I safely use MSACWrapperCrashesHelper.unprocessedCrashReports?

`MSACWrapperCrashesHelper` is an internal class for our wrapper SDKs and is not intended for public use. If you are interested, you can see how it is used here:
https://github.com/microsoft/appcenter-sdk-react-native/blob/edf49c45bfdd36c208e9f195256d9a2212ea59d7/appcenter-crashes/ios/AppCenterReactNativeCrashes/AppCenterReactNativeCrashes.m
https://github.com/microsoft/appcenter-sdk-dotnet/blob/13483bdd0f39b994a0fa5bdce9248f583f38159d/SDK/AppCenterCrashes/Microsoft.AppCenter.Crashes.iOS/Crashes.cs

**Comment by schmidt9** [comment]
@russelarms when can I use `MSACCrashes.hasCrashedInLastSession` so it gives me the right result?
Problem is even when not launching with debugger it always gives me `false` when used in `didSetUpCrashHandlers`, but it works for instance in `- (void)crashes:(MSACCrashes *)crashes willSendErrorReport:(MSACErrorReport *)errorReport`

**Comment by schmidt9** [comment]
@russelarms  Should I always wait for callbacks? But they won't fire when there are no pending reports, so my idea was to use `didSetUpCrashHandlers` to be sure that the system is up and ready

**Comment by schmidt9** [comment]
@russelarms this works as a dirty workaround

```
NSURL *lastSessionCrashReportURL = [[[[NSFileManager.defaultManager URLsForDirectory:NSCachesDirectory inDomains:NSUserDomainMask].firstObject
        URLByAppendingPathComponent:@"com.plausiblelabs.crashreporter.data"]
        URLByAppendingPathComponent:NSBundle.mainBundle.bundleIdentifier]
        URLByAppendingPathComponent:@"live_report.plcrash"];
    BOOL hasCrashedInLastSession = [NSFileManager.defaultManager fileExistsAtPath:lastSessionCrashReportURL.path];
```

**Comment by schmidt9** [comment]
BTW solution for crash report path proposed [here](https://github.com/microsoft/appcenter-sdk-apple/issues/2270) is not working for some way

**Comment by russelarms** [comment]
> @russelarms when can I use MSACCrashes.hasCrashedInLastSession so it gives me the right result?
> Problem is even when not launching with debugger it always gives me false when used in didSetUpCrashHandlers, but it works for instance in - (void)crashes:(MSACCrashes *)crashes willSendErrorReport:(MSACErrorReport *)errorReport

`This method must only be used after MSACCrashes has been started, it will always return NO or false before start.`
It should work after `AppCenter.start` is called, e.g.: https://github.com/microsoft/appcenter-sdk-apple/blob/develop/Sasquatch/SasquatchObjC/AppDelegate.m#L200:L210

> @russelarms Should I always wait for callbacks? But they won't fire when there are no pending reports, so my idea was to use didSetUpCrashHandlers to be sure that the system is up and ready

I meant increasing the counter each session when `hasCrashedInLastSession` returned true and decrease it after the `didSucceedSending` is fired. To do that you'd need to save it across sessions, for example inside UserDefaults.

**Comment by russelarms** [comment]
> solve case where a crash may occur on app start while crash reporting system may not be ready or reports from previous failed launches cannot be sent in time

To be honest, I don't understand the need to deal with this. Have you faced such problems?

What I mean is that if you initialize the Crashes service as early as possible (didFinishLaunchingWithOptions for iOS), as soon as the SDK indicates any crashes from the previous session, it will save the corresponding log to the DB and send it when the device is online.

**Comment by schmidt9** [comment]
> `This method must only be used after MSACCrashes has been started, it will always return NO or false before start.`
> It should work after `AppCenter.start` is called

@russelarms  Actually I call `hasCrashedInLastSession` after start, it does not work in `didSetUpCrashHandlers` callback
```
-[TSAAppDelegate didSetUpCrashHandlers] TSAAppDelegate.mm:343
-[MSACCrashes applyEnabledState:] 0x000000010061b428
-[MSACCrashes startWithChannelGroup:appSecret:transmissionTargetToken:fromApplication:] 0x000000010061bc00
-[MSACAppCenter startService:withAppSecret:transmissionTargetToken:fromApplication:] 0x00000001005d0c90
-[MSACAppCenter startServices:withAppSecret:transmissionTargetToken:fromApplication:] 0x00000001005d0530
-[MSACAppCenter start:withServices:fromApplication:] 0x00000001005d02f0
+[MSACAppCenter start:withServices:] 0x00000001005ced24
-[TSAAppDelegate setupCrashReporting] TSAAppDelegate.mm:230
-[TSAAppDelegate application:didFinishLaunchingWithOptions:] TSAAppDelegate.mm:64
```

Should it also work in `didSetUpCrashHandlers` and if not what's purpose of `didSetUpCrashHandlers`?

**Comment by schmidt9** [comment]
> To be honest, I don't understand the need to deal with this. Have you faced such problems?
> 
> What I mean is that if you initialize the Crashes service as early as possible (didFinishLaunchingWithOptions for iOS), as soon as the SDK indicates any crashes from the previous session, it will save the corresponding log to the DB and send it when the device is online.

It's a real case where crash happens too quickly (after ~2sec after launch) and the crash reporting system is unable to send previous crash report before the new one happens, so because of such "vicious circle" it's no chance crash reports ever arrive to me from the affected build/user. 

OK supposed a crash happens a bit later there is a chance a minimal report without attachments will be sent, but what if I decide to attach an image making payload much "heavier" and if the affected user has a poor internet connection it's again an "undefined behaviour" case - maybe report will be sent and maybe not

**Comment by russelarms** [comment]
>Should it also work in didSetUpCrashHandlers and if not what's purpose of didSetUpCrashHandlers?

This happens because this callback is [called](https://github.com/microsoft/appcenter-sdk-apple/blob/develop/AppCenterCrashes/AppCenterCrashes/MSACCrashes.mm#L372) before the SDK [processes a report](https://github.com/microsoft/appcenter-sdk-apple/blob/develop/AppCenterCrashes/AppCenterCrashes/MSACCrashes.mm#L413) from the previous session.
Again, `didSetupCrashHandlers` is not a public API, the call's purpose is described as
`Allow a wrapper SDK to perform custom behavior after setting up crash handlers.`

```
[MSACAppCenter start:appSecret withServices:services];
[MSACCrashes hasCrashedInLastSession];
```
Should work.

> It's a real case where crash happens too quickly (after ~2sec after launch) and the crash reporting system is unable to send previous crash report before the new one happens, so because of such "vicious circle" it's no chance crash reports ever arrive to me from the affected build/user.

> OK supposed a crash happens a bit later there is a chance a minimal report without attachments will be sent, but what if I decide to attach an image making payload much "heavier" and if the affected user has a poor internet connection it's again an "undefined behaviour" case - maybe report will be sent and maybe not

Thank you, I got it finally. As far as I know
`hasCrashedInLastSession` and `didSucceedSending` are the only public way to achieve this at the moment.

**Comment by schmidt9** [comment]
> [MSACAppCenter start:appSecret withServices:services];
> [MSACCrashes hasCrashedInLastSession];

It works, @russelarms thank you for patience and help
