### ISSUE TITLE
Send custom data along with report

### ISSUE THREAD

**Issue by schmidt9** [microsoft/appcenter-sdk-apple#2304]
I could not find any possibility to add some custom data to reports, if there is none, I'm requesting that - for instance sending console logs and arbitrary data

**UPD**
`- (NSArray<MSACErrorAttachmentLog *> *)attachmentsWithCrashes:(MSACCrashes *)crashes forErrorReport:(MSACErrorReport *)errorReport` (it seems to be the only option) is pretty useless is this case, because

> The following callback will be invoked right before sending the stored crash from previous application launches. It won't be invoked when the crash happens.

**Comment by russelarms** [comment]
Hi, @schmidt9. The time frame between the crash and the application termination is pretty small, therefore no requests are allowed there.
One possible solution is to track events to Analytics and after the crash sent, they will be shown on the portal linked to the crash report.

**Comment by schmidt9** [comment]
@russelarms thanks I tried events, they work but have some downsides ie limitations (https://docs.microsoft.com/en-us/appcenter/analytics/event-metrics#limits) preventing extensive logging and they appear not at once along with report arriving later so it's a bit misleading.

So I ended up using custom logging and using attachments for that logs, at least attachments appear immediately along with crash reports

**Comment by russelarms** [comment]
Glad you have solved it, using attachments is the best option for this case.
