### ISSUE TITLE
In-App Update Work for the Wrong Distribution Group

### ISSUE THREAD

**Issue by DavidB948** [microsoft/appcenter-sdk-apple#2311]
### **Description**

I have recently implemented the app center in-app update feature for my app. The in-app update push supposes to happen when the app is pushed to the production distribution group only, not when the app is pushed to the tester distribution group too.

I do not want users to receive updates when test builds are pushed since they should be properly tested by testers first before introduced to users in production. Any suggestions to resolve this? Both groups are set with public access.

Thanks in advanced.

### **Details**

1. Which SDK version are you using?
    - 4.1.1
2. Which OS version did you experience the issue on?
    - iOS 14.5.1
3. Which Xcode version did you build the app with?
    - Xcode 12.4
5. Which Cocoapods version are you using (run `pod --version`)?
    - 1.10.1
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone 12 physical device
7. What language are you using?
    - Swift

**Comment by russelarms** [comment]
Hi @DavidB948, thanks for reaching out! 
What do you mean by push? An update dialog inside the app or a notification?
Please, share how you have integrated the App Center SDK and especially Distribute module in your app (omitting any private data).

**Comment by DavidB948** [comment]
Hi @russelarms, sorry, I meant the update dialog. 

I do not expect users to see the update dialog if I distribute the app to the tester group. Below shows how the distribute module is integrated.

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        configureForAppCenter()
...
...
}


extension AppDelegate: DistributeDelegate {
    private func configureForAppCenter() {
        
        let appSecret = "535b5b66-30da-49d0-acb7-300de92cb37f"
        #if DEBUG
            AppCenter.start(withAppSecret: appSecret, services: [Analytics.self, Crashes.self])
        #else
            Distribute.delegate = self;
            AppCenter.start(withAppSecret: appSecret, services: [Analytics.self, Crashes.self, Distribute.self])
        #endif
    }
    
    func distributeWillExitApp(_ distribute: Distribute) {
        if userDetailsVC.userDetailsModel.locationStatus {
            userDetailsVC.stopServiceAndCallUserState()
        }
    }
}

Thanks for the prompt response.

**Comment by russelarms** [comment]
@DavidB948 the SDK uses Public track by default, which means the SDK checks for the most recent public build among all the public distribution groups. Apparently, your testers group is set to public, that's why your users see the test builds.
To address this, you can switch your testers groups to private (turn off `App can be downloaded by anyone with link access` in the group settings) and use the private track for the testers builds (before `AppCenter.start`):
```
Distribute.updateTrack = .private
```
https://docs.microsoft.com/en-us/appcenter/sdk/distribute/ios#use-private-distribution-group

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.

**Comment by DavidB948** [comment]
Hi @russelarms, sorry for the late response. However, how about when releasing updates to users? Having "Distribute.updateTrack = .private" would prevent users from getting the update right when I distribute it to the public users' group? 

Do I have any condition that I can set so that users can still get the update when I distribute to the users' group and only tester will get the update when I distribute to the testers' group? Thanks.

**Comment by AnastasiaKubova** [comment]
You can check the type of user programmatically and set the right distribution group, or create two different builds with different group types for example.

**Comment by DavidB948** [comment]
Hi @AnastasiaKubova, thanks for the prompt response. 

Do you mean I could set in the code to "Distribute.updateTrack = .private" for the testers' private group and "Distribute.updateTrack = .public" for the users' public group? Please correct me if I am wrong. As I know, there isn't any way to set the right distribution group programmatically in the code right? I only see app secret to be put in the code, which represents the whole app center environment for the project.

**Comment by AnastasiaKubova** [comment]
> Do you mean I could set in the code to "Distribute.updateTrack = .private" for the testers' private group and "Distribute.updateTrack = .public" for the users' public group? Please correct me if I am wrong.

Yes, you are correct, this is one of the way. You can set the type of distribution group in your app via this [API](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/ios#use-private-distribution-group).

If you set `Distribute.updateTrack = .private` then the updates will be checked from the private group, otherwise from the public group.

**Comment by DavidB948** [comment]
Alright, got it thanks.
