### ISSUE TITLE
System API calls are not symbolicated in MS App Center Crashes if crashes happen on macOS 11 Big Sur

### ISSUE THREAD

**Issue by cli-acdsystems** [microsoft/appcenter-sdk-apple#2315]
### **Description**

With App Center SDK added and enabled, I'm seeing it gathered crashes  in the Diagnostics tab. But when I view the crash in THREADS tab by selecting a device, system API calls are not symbolicated if crash happens on macOS 11 Big Sur.
<img width="1700" alt="image001" src="https://user-images.githubusercontent.com/85767934/121752503-1edb7900-cac5-11eb-91ed-099fb2ac1f83.png">

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Enable App Center SDK in my app
2. Trigger a crash from my app running on macOS 11 Bug Sur

### **Details**

1. Which SDK version are you using?
    - 4.1.1
2. Which OS version did you experience the issue on?
    - macOS 11 Big Sur
3. Which Xcode version did you build the app with?
    - Xcode 11
5. Which Cocoapods version are you using (run `pod --version`)?
    - none
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - all mac devices: mac mini, iMac, macbook, macbook pro
7. What language are you using?
    - [X] Objective C
    - [ ] Swift
8. What third party libraries are you using?
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by DmitriyKirakosyan** [comment]
Hi @cli-acdsystems 

Please note, that iOS and macOS apps require symbolication for displaying stack traces.
You can find instructions on how to get and upload symbols for iOS/macOS apps to the AppCenter portal in [App Center Diagnostics documentation](https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication).

If you already did that, please share a code sample of how exactly you trigger a crash in your app.
Thanks.

**Comment by cli-acdsystems** [comment]
Hi @DmitriyKirakosyan

I understand I need to upload symbolication .dSYM for my macOS app, there is no problem to symbolicate customized symbols. My issue is about APIs from Apple like CoreFoundation, AppKit , CoreGraphics... etc. are not symbolicated if crashes happen on macOS 11 Big Sur. But on macOS 10.15, there is no problem to symbolicate them. See comparison screenshot of macOS 11 vs macOS 10.15 below:
<img width="1909" alt="Screen Shot 2021-06-15 at 2 39 04 PM" src="https://user-images.githubusercontent.com/85767934/122129746-6460b480-cdeb-11eb-9b79-efd1a894cb68.png">

**Comment by DmitriyKirakosyan** [comment]
Hi @cli-acdsystems 

All call stack symbolication is done on the backend side.
The SDK is only responsible for creating call stacks and sending it to the backend.
Please report the problem using the "Contact Support" button on the AppCenter portal: Top-right corner, question mark -> Contact support.

I'm closing this issue as it is not related to the SDK.
Please let me know if you have additional questions.
