### ISSUE TITLE
Invalid Resource 'Resources/AppCenterDistribute.strings': File not found

### ISSUE THREAD

**Issue by tonyarnold** [microsoft/appcenter-sdk-apple#2318]
### **Description**

The Swift Package declared for AppCenterDistribute is showing an error in Xcode:

```
Invalid Resource 'Resources/AppCenterDistribute.strings': File not found.
```

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Setup an Xcode project that integrates AppCenter's SPM package.
2. Build the target that depends on AppCenter.
3. Note that Xcode shows a warning against the AppCenter package with the message shown in the description for this issue.

It looks like the Package.swift doesn't need to manually specify resources to process if they're in the correct directory structure and format (which this file appears to be!).

### **Details**

1. Which SDK version are you using?
    4.2.0
2. Which OS version did you experience the issue on?
    macOS 11.4
3. Which Xcode version did you build the app with?
    Xcode 12.5

**Comment by DmitriyKirakosyan** [comment]
Hi @tonyarnold 

Thank you for getting in touch with us and for your contribution!

Actually, `.process("Resources/AppCenterDistribute.strings")` is required for the correct integration of the Distribute module. The option was introduced in SwftPM 5.3, please check this [Bundling Resources with a Swift Package](https://developer.apple.com/documentation/swift_packages/bundling_resources_with_a_swift_package).

Could you please add more information on how you integrate AppCenter and what platform you're developing for.
You mentioned that OS version is "macOS 11.4". Please note that the Distribute module is not supported for macOS applications, it only works on iOS.
Also what SPM version do you use?

I tried to reproduce the issue you described but without success. It didn't show any errors for me while integrating AppCenter via SPM. I'm using Xcode 12.5 and Swift 5.4.

**Comment by tonyarnold** [comment]
Ah, whoops - I was using Xcode 13 beta 1. 

I'll close this and #2319 out, because that's likely to be a bug.

**Comment by tonyarnold** [comment]
I mean, to be fair, here is what the docs say in the page you linked to (https://developer.apple.com/documentation/swift_packages/bundling_resources_with_a_swift_package):

> When you add a resource to your Swift package, Xcode detects common resource types for Apple platforms and treats them as a resource automatically. For example, you don’t need to make changes to your package manifest for the following resources:
> - Interface Builder files; for example, XIB files and storyboards
> - Core Data files; for example, xcdatamodeld files
> - Asset catalogs
> - .lproj folders you use to provide localized resources

So it's not necessary to include this line.

**Comment by DmitriyKirakosyan** [comment]
hi @tonyarnold 

Just tested your PR and It worked for me indeed. So explicitly importing localized resources does look redundant.
I tested with swift 5.3, 5.4, 5.5, Xcode 12.0.1, 12.5, 13.
Reopened the PR. We will perform a few more tests and merge it.
Thank you again.

**Comment by DmitriyKirakosyan** [comment]
PR https://github.com/microsoft/appcenter-sdk-apple/pull/2319 is merged.
The fix will be available in the next release.
Alternatively to avoid the warning on XCode 13, you can integrate the SDK via SPM from `develop`.

**Comment by DmitriyKirakosyan** [comment]
Hi, we've released a new version with this fix included.
