### ISSUE TITLE
CocoaPods — AppCenter Release 4.2.0 Not Available

### ISSUE THREAD

**Issue by michaeldclifford** [microsoft/appcenter-sdk-apple#2320]
Usually there is a delay of ~1-30 minutes between an AppCenter GitHub release and it becoming available via CocoaPods.

However, the [latest version of AppCenter (4.2.0)](https://github.com/microsoft/appcenter-sdk-apple/releases) was released 24 hours ago and hasn't yet appeared [on CocoaPods](https://github.com/CocoaPods/Specs/tree/master/Specs/f/9/9/AppCenter).

This issue is raised as both a query — is CocoaPods no longer supported? — and/or as a notification that something may have gone wrong in some process or pipeline.

**Comment by DmitriyKirakosyan** [comment]
Hi @michaeldclifford 

We had an issue on our CI releasing the new version to cocoapods.
It is now resolved and the version is published.

Sorry for the inconvenience.

**Comment by michaeldclifford** [comment]
No worries. Thank you for solving it so quickly. 👍
