### ISSUE TITLE
Can I use the SDK to upload a custom crash report?

### ISSUE THREAD

**Issue by gongzhang** [microsoft/appcenter-sdk-apple#2332]
My iOS app collects crash reports and diagnostic reports from the counterpart watch app. Does the current SDK have an API that allows me to create my own `ErrorReport` object and then upload it?

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us and my apologies for the long response. 
Currently, the App Center SDK has no API for creating a custom error report. I will label this issue as a feature request.
For now, if you have any custom data you can try to send it via [attachments](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/ios#add-attachments-to-a-crash-report).

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us and my apologies for the long response! 
We have already merged to develop the feature for [tracking handle errors](https://github.com/microsoft/appcenter-sdk-apple/pull/2337) in the Apple App Center SDK. It will be available in the next release. We will notify you about it.

**Comment by gongzhang** [comment]
> Hi! Thanks for getting in touch with us and my apologies for the long response!
> We have already merged to develop the feature for [tracking handle errors](https://github.com/microsoft/appcenter-sdk-apple/pull/2337) in the Apple App Center SDK. It will be available in the next release. We will notify you about it.

Wow! This is great. Looking forward to it.

**Comment by gongzhang** [comment]
@AnastasiaKubova Now I can use `4.3.0`, right? 🎉 🎉 🎉

**Comment by AnastasiaKubova** [comment]
Yes, the [feature](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.3.0) has been released so I'm closing this issue. Please feel free to contact us if you will have additional questions.
Thanks for using App Center.

**Comment by gongzhang** [comment]
@AnastasiaKubova Thank you very much!

**Comment by AnastasiaKubova** [comment]
Oh, @gongzhang my apologies for the confusion. 
We released this feature only from the SDK side. But this feature requires some updates on the App Center portal. I will notify you when these changes will be released on the App Center portal.

**Comment by gongzhang** [comment]
@AnastasiaKubova Ok, no problem. I'll integrate the feature in my project first. 👌

**Comment by DmitriyKirakosyan** [comment]
Hi @gongzhang , the backend is updated, so I'm closing the issue.
Feel free to ping us if you encounter any issues while using the `trackError` API.
Currently there is a known issue with symbolicating stack traces of error reports which we are working on right now.
Related feature request in main repo: https://github.com/microsoft/appcenter/issues/192.

**Comment by gongzhang** [comment]
@DmitriyKirakosyan It works! Thanks. 😄
