### ISSUE TITLE
Invalid Resource 'Resources/AppCenterDistribute.strings': warning in Xcode 13

### ISSUE THREAD

**Issue by donnywdavis** [microsoft/appcenter-sdk-apple#2333]
### **Description**

We are getting a warning for the AppCenter Swift package when using Xcode 13 beta. It states that there is a missing file in the resources folder of the package.

Everything in our project builds and runs fine. Just seeing this warning during the package resolution.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Open Xcode 13.
2. See the warning during package resolution.

### **Details**

1. Which SDK version are you using?
    4.2.0
2. Which Xcode version did you build the app with?
    Xcode 13 beta 2

<img width="459" alt="Untitled" src="https://user-images.githubusercontent.com/2036378/125571318-78319322-c2ad-46d5-a26a-057f39bc53a6.png">

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
We already had a similar request. The fix will be included in the next release.
Close this issue as a duplicate #2318
