### ISSUE TITLE
SPM swift-tools-version:5.4 & 5.5 has no AppCenterDistribute target

### ISSUE THREAD

**Issue by apps4everyone** [microsoft/appcenter-sdk-apple#2341]
With SPM and swift-tools-version:5.4 or 5.5 there is no Package@swift-5.4.swift or Package@swift-5.5.swift then the fallback is Package.swift and this has no AppCenterDistribute.

**Comment by apps4everyone** [comment]
maybe it is better to have for older version specific Package@swift-x.swift and from >= 5.3 Package.swift is used with AppCenterDistribute.

**Comment by DmitriyKirakosyan** [comment]
Hi @apps4everyone,

SPM picks the most compatible version if the exact version is not present in repo. So swift v5.5 will pick the `Package@swift-5.3.swift` package. From official docs:

> The package manager will pick `Package.swift` on Swift 3, `Package@swift-4.swift` on Swift 4, and `Package@swift-4.2.swift` on Swift 4.2 **and above because its tools version will be most compatible with future version of the package manager**.
> 

Link: https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#version-specific-manifest-selection
