### ISSUE TITLE
App Center Distribute – iOS In-app updates with SwiftUI ?

### ISSUE THREAD

**Issue by X901** [microsoft/appcenter-sdk-apple#2358]
Hi , 
I tried to add App Center Distribute following this

https://docs.microsoft.com/en-us/appcenter/sdk/distribute/ios

but it doesn't work 

what I did was add this to line

```
 static func checkUpdate() {
        AppCenter.start(withAppSecret: "My Secret", services: [Distribute.self])
        Distribute.updateTrack = .private
    }

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        AppDatabaseConfig.shared.setUp(with: DatabaseInitializationConfig(connectionType: .pool))
        AppDelegate.checkUpdate()
        return true
    }
```
    

On AppDelegate 

then after I download it on my device , I upload new version with different build
but I didn't get any Alert inside the app to download new version !

is there something missed ?

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
Please pay attention that `Distribute.updateTrack` [property](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/ios#use-private-distribution-group) can only be updated before the `AppCenter.start` method call.  Changes to the update track aren't persisted when the application process restarts, thus if the property isn't always updated before the `AppCenter.start call`, it will be public, by default.

If after setting this property before `AppCenter.start` you still get this problem then could you please share the [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/ios#adjust-the-log-level) with reproducing of this issue?

**Comment by X901** [comment]
Thank you , it work great now 👍
I have one more question , Can I change the alert ? for example show it inside sheet (custom view)

**Comment by DmitriyKirakosyan** [comment]
Yep, you can do it. See [Customize the update dialog](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/ios#2-customize-the-update-dialog).

I'm closing the issue but feel free to reopen it if you have additional questions.
