### ISSUE TITLE
Xcode SPM warning with 4.4.0

### ISSUE THREAD

**Issue by apps4everyone** [microsoft/appcenter-sdk-apple#2383]
Xcode SPM warning:

ignoring broken symlink /Users/yxz/Library/Developer/Xcode/DerivedData/Project-emfyjoecalbwrpehdgovbuoresyd/SourcePackages/checkouts/appcenter-sdk-apple/AppCenter/AppCenter/include/MSACCustomProperties.h

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! This is a[ known issue](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.4.0) and we already merged a[ fix](https://github.com/microsoft/appcenter-sdk-apple/pull/2380) for it.

**Comment by Janoz94** [comment]
> Hi! Thanks for getting in touch with us! This is a[ known issue](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.4.0) and we already merged a[ fix](https://github.com/microsoft/appcenter-sdk-apple/pull/2380) for it.

Hi Anastasia,
I'm not sure about it but I believe that you have to add proper tag to it as SPM is still downloading the package version with this issue. 😉

**Comment by Janoz94** [comment]
Hi,
Anastasia when is next released planned? As I saw previous releases it take months between and as it's breaking thing maybe there is a chance for patch release?

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
We have no plans to make a new release in the near time. We will notify you when the fix will be available.

**Comment by apps4everyone** [comment]
Sad to hear this, we will not update to 4.4.0 until this warning is fixed with a new release....

**Comment by gongzhang** [comment]
Also waiting for the new version. 

For the impatient 😅

```swift
// tag 4.4.0 + a simple fix
.package(name: "AppCenter", url: "https://github.com/gongzhang/appcenter-sdk-apple.git", .revisionItem("bd85b7b2adf3843312cdc2afea23cc9ec3cd0a3a")),
```

**Comment by DmitriyKirakosyan** [comment]
Hi guys, we decided to publish a patch release with this fix next week.

**Comment by apps4everyone** [comment]
fixed with 4.4.1, thx

**Comment by gongzhang** [comment]
Upgraded immediately. Thanks! ❤️

**Comment by DmitriyKirakosyan** [comment]
Love your fast reaction guys 👍
