### ISSUE TITLE
Application with AppCenter pod v. 4.1.0.  is not responding after launch.

### ISSUE THREAD

**Issue by SRykhletskiy** [microsoft/appcenter-sdk-apple#2385]
I have  Catalyst application, that uses AppCenter pod version 4.3.0

When loading a production app version from Test Flight on OS X 12.0.1 on a new guest user, the application is not responding after launch. When restarted, everything is work . The problem is not reproducible in App, that used AppCenter pod v. 4.1.0.

1. Which SDK version are you using?
  - 4.3.0, 4.1.0
2. Which OS version did you experience the issue on?
  - OS X 12.0.1
3. Which Xcode version did you build the app with?
  - Xcode 13.1
5. Which Cocoapods version are you using (run `pod --version`)?
  - 1.10.0
6. What device version did you see this error on?  Were you using an emulator or a physical device?
  - mac mini
7. What language are you using?
  - Objective C
  - Swift
8. What third party libraries are you using?
  boost, glm, Differ, AFNetworking, GoogleAPIClientForREST, GoogleAPIClientForREST/YouTube, GTMAppAuth, DarklyEventSource, FBSDKLoginKit, FBSDKShareKit, FreshchatSDK, TwitterCore, TwitterKit, AppsFlyerFramework, TwitterKitCatalyst, TwitterCoreCatalyst, XCDYouTubeKit, GDataXML-HTML, Alamofire, PromiseKit, SwiftyJSON, CocoaAsyncSocket, GZIP, ProtocolBuffers

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! Could you please share [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/ios#adjust-the-log-level)?

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.
