### ISSUE TITLE
AppCenter crash number are not same as CrashesDelegate callback

### ISSUE THREAD

**Issue by tianpeili** [microsoft/appcenter-sdk-apple#2386]
### **Description**

We received callback for method `func crashes(_ crashes: Crashes, shouldProcess errorReport: ErrorReport) -> Bool`, But we didn't see same `incidentIdentifier` in AppCenter Dashboard. 

For now, we found two `incidentIdentifier` in our system that can not found in AppCenter Dashboard.

### **Repro Steps**

We can not repro in dev environment. But we send callback `ErrorReport` to our telemetry system.
And we found the number in our system are always higher than AppCenter Dashboard(also higher than Apple report).
We search the `incidentIdentifier`, which found in our system, in AppCenter Dashboard and result is not found.

### **Details**

1. Which SDK version are you using?
     - AppCenter (4.3.0):
    - AppCenter/Analytics (= 4.3.0)
    - AppCenter/Crashes (= 4.3.0)
2. Which OS version did you experience the issue on?
    - iOS 15.1.1 and 14.8.1
3. Which Xcode version did you build the app with?
    -  13.1
5. Which Cocoapods version are you using (run `pod --version`)?
    - COCOAPODS: 1.11.2
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone12ProMax(15.1.1) iPhone7Plus(14.8.1
7. What language are you using?
     Swift
8. What third party libraries are you using?
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by aleksandr-dorofeev** [comment]
Hi, @tianpeili 
Thank you for getting in touch with us!

`incidentIdentifier` is not displaying on portal among other metrics, but you can find it in the RAW crash log by navigating to Diagnostics -> Issues -> Your Crash -> Reports. On the Reports screen select a report and click the "RAW" button on the right side of the screen.
Please let me know if it helps!

**Comment by AnatolyPristensky** [comment]
Hello, @tianpeili ,

We haven't heard from you in a while so I'm going ahead and close this issue, but feel free to reopen if you have additional questions.
