### ISSUE TITLE
Stack traces for Swift Errors are insufficient

### ISSUE THREAD

**Issue by atakanozcan** [microsoft/appcenter-sdk-apple#2393]
### **Description**

We want to use tracking errors feature of AppCenter for our project. However when we track an error using `Crashes.trackError(error, properties: properties, attachments: nil)` , resulting stack trace on AppCenter is very sparse and contains no useful information. How can we get a good stack trace and also what is the suggested approach for logging Swift Errors?

<img width="654" alt="Screen Shot 2022-01-17 at 12 18 05@2x" src="https://user-images.githubusercontent.com/35854230/149791927-b4d0d3df-9fbd-438b-8252-93424d7a464b.png">

### **Details**

1. Which SDK version are you using?
    - 4.4.0
2. Which OS version did you experience the issue on?
    - iOS 15.2
3. Which Xcode version did you build the app with?
    - Xcode 13.2.1
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone 12 physical device
7. What language are you using?
    - [x] Swift

**Comment by DmitriyKirakosyan** [comment]
Hi @atakanozcan , thank you for reaching out to us!
This is a known issue and we have a work item on our board.
I'll update this thread on the progress.

Meanwhile, for getting more info about the error, you can try checking the raw report data by navigating to `Reports -> <your report> -> RAW`.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
