### ISSUE TITLE
Appcenter Update Pop-up shows String IDs

### ISSUE THREAD

**Issue by KraemeRoQM** [microsoft/appcenter-sdk-apple#2394]
### **Description**
When open a app version which is not the latest version, the Update is available Pop-up is shown. The pop-up does not display the correct strings, but instead the string IDs are shown to the user. 

### **Repro Steps**
1. Download not the latest App version from appcenter
2. Open the app -> a popup should appear that on AppCenter is a newer Version
3. Texts are not displayed, only the IDs

### **Details**

1. Which SDK version are you using?
4.0.0

2. Which OS version did you experience the issue on?
iOS 15.2.1

3. Which Xcode version did you build the app with?
Xcode 13.1

4. What device version did you see this error on?  Were you using an emulator or a physical device?
iPhone 12 mini physical device

5. What language are you using?
    - [X] Swift
    
6. Screenshot of the issue:
![Appcenter_string_IDs_shown](https://user-images.githubusercontent.com/88835392/150515042-df77ba58-db8c-40cf-863f-cdf79988e9d2.PNG)

**Comment by aleksandr-dorofeev** [comment]
Hi @KraemeRoQM
Thanks for reaching out.

Could you clarify how do you integrate the App Center? (SPM, Carthage, Cocoapods or Binary)?

If you are integrating SDK by adding frameworks manually, please make sure that you have added `AppCenterDistributeResources.Bundle` to your project. [Documentation](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/ios#the-alert-that-prompts-users-for-an-update-doesnt-contain-strings-but-just-the-keys-for-them)

Could you please try to update SDK to latest version ([4.4.1](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.4.1)) and check if the issue persists.

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.
