### ISSUE TITLE
Application crash on Crashes.TrackError(ex) when using Hot Restart

### ISSUE THREAD

**Issue by kaniosm** [microsoft/appcenter-sdk-apple#2400]
The application Crashes when calling the Crashes.TrackError(ex) method with the below error:

> Xamarin.PreBuilt.iOS[2462:612625] Xamarin.iOS: Received unhandled ObjectiveC exception: NSInvalidArgumentException *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]
> 
> * Assertion: should not be reached at /Users/builder/jenkins/workspace/archive-mono/2020-02/ios/release/mono/mini/mini-exceptions.c:452
> 
> The app has been terminated.
> 

The application will only crash when deploying the app to a Local iPhone device using Hot Restart.

1. Which SDK version are you using?
    - 4.4 and 4.5
2. Which OS version did you experience the issue on?
    - iOS 15
3. Which Xcode version did you build the app with?
    - 12.4
4. Which version of Visual Studio are you using
    - VS 2022

**Comment by AnatolyPristensky** [comment]
Hello @kaniosm ,
Unfortunately I'm unable to reproduce your issue. 
Could you please describe the repro steps more precisely?

**Comment by kaniosm** [comment]
Hello @AnatolyPristensky,

I just prepared a small project that reproduces the issue.
Just make sure that you debug this project using Hot Restart with a local iOS device.
You should ge the error below:

> An error occurred: 'Could not create an native instance of the type 'Microsoft.AppCenter.iOS.Bindings.MSACWrapperSdk': the native class hasn't been loaded.
> It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.'. Callstack: '  at Foundation.NSObject.InitializeObject (System.Boolean alloced) [0x0002e] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:327 
>   at Foundation.NSObject..ctor (Foundation.NSObjectFlag x) [0x0000d] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:184 
>   at Microsoft.AppCenter.iOS.Bindings.MSACWrapperSdk..ctor (System.String wrapperSdkVersion, System.String wrapperSdkName, System.String wrapperRuntimeVersion, System.String liveUpdateReleaseLabel, System.String liveUpdateDeploymentKey, System.String liveUpdatePackageHash) <0x11a509f10 + 0x0000a> in <57c9e239a4a24902835d9ec6d66cb938>:0 
>   at Microsoft.AppCenter.AppCenter.SetWrapperSdk () <0x11a4e92f0 + 0x00012> in <a55b22030e284d4993b4fa4dbd648997>:0 
>   at Microsoft.AppCenter.AppCenter.PlatformStart (System.String appSecret, System.Type[] services) <0x11a4e9008 + 0x00002> in <a55b22030e284d4993b4fa4dbd648997>:0 
>   at Microsoft.AppCenter.AppCenter.Start (System.String appSecret, System.Type[] services) <0x11a4e8b00 + 0x00008> in <a55b22030e284d4993b4fa4dbd648997>:0 
>   at App10.App.OnStart () [0x00001] in C:\Users\Michalis\source\repos\App10\App10\App10\App.xaml.cs:25 
>   at Xamarin.Forms.Application.SendStart () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Application.cs:346 
>   at Xamarin.Forms.Platform.iOS.FormsApplicationDelegate.FinishedLaunching (UIKit.UIApplication uiApplication, Foundation.NSDictionary launchOptions) [0x00036] in D:\a\1\s\Xamarin.Forms.Platform.iOS\FormsApplicationDelegate.cs:58 
>   at App10.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x00013] in C:\Users\Michalis\source\repos\App10\App10\App10.iOS\AppDelegate.cs:28 
>   at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
>   at UIKit.UIApplication.Main (System.String[] args, System.Type principalClass, System.Type delegateClass) [0x0003b] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:83 
>   at App10.iOS.Application.Main (System.String[] args) [0x00001] in C:\Users\Michalis\source\repos\App10\App10\App10.iOS\Main.cs:17 
>   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
>   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:395 '


[App10.zip](https://github.com/microsoft/appcenter-sdk-apple/files/8067931/App10.zip)
.

**Comment by kaniosm** [comment]
Apologies...
I'm building the same project from another environement and I can't get this now.
I'll close the issue for now, and open another one in case I face this again.

Thx
