### ISSUE TITLE
Can AppCenter start in a non-main thread?

### ISSUE THREAD

**Issue by iCodeWoods** [microsoft/appcenter-sdk-apple#2410]
Can AppCenter start in a non-main thread?

**Comment by DmitriyKirakosyan** [comment]
Hi @iCodeWoods , yes AppCenter SDK can be started on non-main thread.
The only drawback I can think about is due to the delayed initialization the Crashes SDK may miss some crash if it happens on the app launch.

Closing this issue, but feel free to ask any additional questions.
