### ISSUE TITLE
Maximums size for attached text using MSACErrorAttachmentLog

### ISSUE THREAD

**Issue by schmidt9** [microsoft/appcenter-sdk-apple#2412]
What is maximums size for attached text using `+ (MSACErrorAttachmentLog *)attachmentWithText:(NSString *)text filename:(NSString *)filename` with `- (NSArray<MSACErrorAttachmentLog *> *)attachmentsWithCrashes:(MSACCrashes *)crashes forErrorReport:(MSACErrorReport *)errorReport` ?

**Comment by MatkovIvan** [comment]
Hi, It's documented [here](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/ios#add-attachments-to-a-crash-report):

> The size limit is currently 7 MB. Attempting to send a larger attachment will trigger an error.

Please let me know if you have any questions.

Best Regards,
Ivan
