### ISSUE TITLE
Impossible to perform an Archive with Xcode 14

### ISSUE THREAD

**Issue by jordimele** [microsoft/appcenter-sdk-apple#2415]
### **Description**

Using Xcode 14 beta 3 and trying to archive an iOS app, the following error occurs:

<img width="893" alt="AppCenter_Error" src="https://user-images.githubusercontent.com/11957195/177996392-8fbd91c6-57e6-44f0-afbb-63b5b2e267ea.png">

The application compiles without problems, but it is impossible to perform an Archive.

Configuration of the generated Pods project:

<img width="1104" alt="AppCenter_Config" src="https://user-images.githubusercontent.com/11957195/177997511-ac3f39c5-5162-4b53-9bdf-febfebf38980.png">

### **Repro Steps**

1. Product - Archive iOS Aplication with Xcode 14 beta 3

### **Details**

1. Which SDK version are you using?
    - 4.3.0
2. Which OS version did you experience the issue on?
    - iOS 16
3. Which Xcode version did you build the app with?
    - Xcode 14 beta 3
5. Which Cocoapods version are you using (run `pod --version`)?
    - 1.11.3
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - NO Device, Archive
7. What language are you using?
    - [X] Swift

**Comment by AnatolyPristensky** [comment]
Hello @jordimele,
Thank you for getting in touch with us. 
We will check this case and get back to you once get results.

**Comment by DmitriyKirakosyan** [comment]
Hi there, this is not an AppCenter SDK issue. See https://github.com/CocoaPods/CocoaPods/issues/8891.
It either Xcode or Cocoapods issue. Please follow the issue in the CocoaPods thread. You can also find a workaround there.

Closing as not related to the AppCenter SDK.
