### ISSUE TITLE
AppCenter - iOS SDK: userId doesn't get set at global level

### ISSUE THREAD

**Issue by lokeshgs** [microsoft/appcenter-sdk-apple#2416]
### **Description**

I'm logging events to AppCenter via Appcenter iOS SDK and I'm trying to set the userId at the global level as mentioned here https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/ios#identify-users. But our backend team confirmed that they are not seeing the userId set at the global level. Can you please take a look?

### **Repro Steps**

Please list the steps used to reproduce your issue.

1.
2.

### **Details**

1. Which SDK version are you using?
    - 4.4.1
2. Which OS version did you experience the issue on?
    - iOS 14.5
3. Which Xcode version did you build the app with?
    - Xcode 13.4
5. Which Cocoapods version are you using (run `pod --version`)?
    - 1.11.3
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone 12 Pro physical device (basically all devices/simulators)
7. What language are you using?
    - Swift
8. What third party libraries are you using?
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
Attached the logs to ICM https://portal.microsofticm.com/imp/v3/incidents/details/318940069/home

**Comment by MatkovIvan** [comment]
Hi,

Based on your logs you're using 1ds backend instead of App Center portal. Let's continue our conversation in IcM or teams. Closing this one.
