### ISSUE TITLE
iOS Simulator Unexpectedly Shows In-app Updates Alert

### ISSUE THREAD

**Issue by iHaifaa** [microsoft/appcenter-sdk-apple#2422]
### **Description**
Hello,

I am using the SDK to enable in-app updates and everything seems fine. The only issue is that the in-app update alert keeps appearing in the Xcode simulator even though I run the latest app release. When I distribute the same release on App Center and test it on an actual iPad, the alert does not appear which is expected behavior. Could anyone tell me why the alert keeps showing in the simulator and how to stop it in this case?

### **Repro Steps**

1. Create release 1
2. Create release 2
3. Distribute both releases on App Center
4. As expected,  release 1 shows the update alert on the physical iPad
5. As expected, release 2 does not show the update alert on the physical iPad
6. Run both releases on the Xcode simulator
7. As expected, release 1 shows the update alert
8. Unexpectedly, release 2 shows the update alert

### **Details**

1. Which SDK version are you using?
    - 4.4.3
2. Which OS version did you experience the issue on?
    - iOS 15.4
8. Which Xcode version did you build the app with?
    - Xcode 13.4.1
9. Which Cocoapods version are you using (run `pod --version`)?
    - 1.10.2
10. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPad Mini 5th Generation
    - iPad simulator 
11. What language are you using?
    - Swift

**Comment by aleksandr-dorofeev** [comment]
Hi @iHaifaa  thanks for reaching out!
Do you have two releases on the portal or more? Also, can you tell me which distribution group you are using?

**Comment by aleksandr-dorofeev** [comment]
Hi @iHaifaa  thanks for reaching out!
Do you have two releases on the portal or more? Also can you share which distribution group you are using?

**Comment by iHaifaa** [comment]
> Hi @iHaifaa thanks for reaching out! Do you have two releases on the portal or more? Also can you share which distribution group you are using?

Thanks for your response. 
I have more than 2 releases, and I distributed them to a public group.

**Comment by aleksandr-dorofeev** [comment]
Thanks for the info, I'm trying to reproduce the behavior you describe but unfortunately with no success so far. 
I will need more information. 
Can you confirm that you are using the same `distribution group` to build on the physical device and on the simulator? Also do you use the `build version` in your releases?

**Comment by iHaifaa** [comment]
Could you please elaborate more on the distribution group and build version?
In App Center Portal, I created a public group and distribute the release to that group. In Xcode, I didn't link the source code with the group. Also, I change the build version of the release from the Xcode itself, is there any configuration I need to apply?

**Comment by aleksandr-dorofeev** [comment]
Thanks for the info about the group and build version. 
Also please share [verbose logs](https://docs.microsoft.com/en-gb/appcenter/sdk/other-apis/ios#adjust-the-log-level).

**Comment by aleksandr-dorofeev** [comment]
We haven’t heard from you in a while so I’m closing this issue. Feel free to reopen this issue if it isn’t resolved or you have additional questions.
