### ISSUE TITLE
SwiftUI Previews in Xcode 14 failed to run when adding AppCenterCraches through SPM

### ISSUE THREAD

**Issue by pyby** [microsoft/appcenter-sdk-apple#2429]
### **Description**

An iOS project doesn't work anymore for SwiftUI Preview with Xcode 14 RC.
The project builds and runs fine, but Preview never works. The error message is as follows:

```
HumanReadableSwiftError

SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x0000600279d29500):'AppCenterCrashes'>)
```

`AppCenterCrashes` is added thought PSM.  SwiftUI Preview with Xcode 13.4.1 works.

It was mentioned during Xcode 14 beta version here:
https://developer.apple.com/forums/thread/707569?page=2

I [opened a radar to Apple](http://openradar.appspot.com/radar?id=5579116359188480), but as the issue is not on all SPM packages, I'm not sure that Apple will fix it.
Any idea?

### **Repro Steps**

With Xcode 14 RC:
1. Create a new project (command+Shift+N)
2. Choose iOS app / Swift UI / swift
3. Click on "ContentView" file
4. Display Canevas and run the Preview with a simulator device

"Hello, world!" preview is displayed.

5. In Project / Package dependencies, add https://github.com/microsoft/appcenter-sdk-apple.git, Up to next major version, 4.0.0
6. Add AppCenterCrashes product to the target.
7. Click on "ContentView" file to display the preview again.

"Unexpected error occured".

### **Details**

1. Which SDK version are you using?
    - 4.4.3
2. Which OS version did you experience the issue on?
    - Any. Xcode 14 with iOS16 / tvOS 16 SDK.
3. Which Xcode version did you build the app with?
    - e.g. Xcode 14.0 RC (beta 4, 5, 6 as well).
5. Which Cocoapods version are you using (run `pod --version`)?
    - None
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Phone or Apple TV simulator, SwitUI preview.
7. What language are you using?
    - Swift
8. What third party libraries are you using?
In this example, no one: just `AppCenterCrashes`.

In our project, other libraries (binaries or to compile) has no impacts with SwiftUI preview build.

**Comment by AlexeyBudynkov** [comment]
@pyby Hello. You mean if to exclude AppCenterCrashes from the project, then everything is working as expected?

**Comment by DmitriyKirakosyan** [comment]
Thank you for the report! I'm marking it as a bug.

**Comment by johnescobia** [comment]
Having the same issue on Xcode 14.0 (14A309).

**Comment by pyby** [comment]
> @pyby Hello. You mean if to exclude AppCenterCrashes from the project, then everything is working as expected?
> 
> And another question, what if not to launch Preview, but just start the application on a simulator? 

1. Yes. The SwiftUI previews build succeed and the previews in Xcode are ok.

2. Build and run the application in the simulator starts as expected. Also for release build on devices or for AppStore submission.

The issue impacts developers using the previewing SwiftUI feature in Xcode.

**Comment by kvyatkovskys** [comment]
The same issue on Xcode 14.0 (14A309).

**Comment by pyby** [comment]
As the issue seems to be linked to "Static Library ProductBuildable", [we tried to remove](https://github.com/microsoft/appcenter-sdk-apple/compare/develop...SRGSSR:appcenter-sdk-apple:develop) the `type: .static` declaration for product libraries.

SwiftUI previews build succeed again with Xcode 14.0 (14A309).

I'm not sure if we can create a PR with this change without a validation from the core team:
- Should we have a third `Packages.swift` file for Swift 5.7 (Xcode 14) without the static type only for new Xcode version?
- Why AppCenter libraries are delivered as static libraries with SPM?

Same issue with Xcode 14.1 beta (14B5024h).

**Comment by pyby** [comment]
https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html

```
/// If possible, don't declare the type of library explicitly to let 
/// the Swift Package Manager choose between static or dynamic linking based
/// on the preference of the package's consumer.
```

It would be great for the libraries to re-evaluate why it's static only.

**Comment by peternowell** [comment]
Any update on a fix or suggestions about how to resolve this? Is the only option to fork this repo and remove the library types in package.swift?

**Comment by klaas** [comment]
I ran into the same issue. Removing AppCenter from code and the list of embedded libraries did "fix" the previews.

Any solution to get previews and App Center work together would be great.

**Comment by johnescobia** [comment]
> 

Previews in Xcode work when [AppCenter is added via CocoaPods](https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/ios#31-integration-via-cocoapods).

**Comment by johnescobia** [comment]
> I ran into the same issue. Removing AppCenter from code and the list of embedded libraries did "fix" the previews.
> 
> Any solution to get previews and App Center work together would be great.

Previews in Xcode work when [AppCenter is added via CocoaPods](https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/ios#31-integration-via-cocoapods).

**Comment by AnatolyPristensky** [comment]
I've prepared PR with a fix of this issue: https://github.com/microsoft/appcenter-sdk-apple/pull/2433
The fix will be released soon, as a workaround you can use the fork which is mentioned in comments above.

**Comment by smakus** [comment]
It would be great if we could get the workaround as part of the main library.  All previews crash with the current version, which makes development painful, as you have to completely remove the AppCenter swift package for previews to work.

**Comment by MartinMajewski** [comment]
I have the same issue with Xcode version 14.0.1 (14A400).
Even though I removed the static type, I could not solve this issue completely, as now AppCenterCrashes is causing SwiftUI preview problems. I removed the static type there as well but still. This is annoying, and I cannot simply use a forked package on this project. Any ETA?

**Comment by aleksandr-dorofeev** [comment]
Hi there
The release is expected this month.

**Comment by pyby** [comment]
It still an issue with Xcode version 14.1 (14B47).

```
HumanReadableSwiftError

SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x000060006329fc90):'AppCenterDistribute'>)
```

Thank you @AnatolyPristensky for the PR and MS team for the future release.

**Comment by honkmaster** [comment]
@aleksandr-dorofeev We are already in the dawn of the next month... When can we expect a release?

**Comment by MikhailSuendukov** [comment]
Hi @honkmaster, the apple SDK is planned to be released within two weeks.

**Comment by zulfishah** [comment]
> Hi @honkmaster, the apple SDK is planned to be released within two weeks.

This was 2 weeks ago. Any update?

**Comment by mreichelt** [comment]
Same for us. Our SwiftUI previews do not work, just because we integrated AppCenter. We would love for the previews to work again :)

**Comment by summongr** [comment]
Hi @zulfishah and @mreichelt the update is **already** available for some days now under version **5.0.0**. I suppose you already have the version 4.4.3 and you are using Swift Package Manager (SPM) under Xcode. In order to get the latest version you have to remove the package and install it again, or you have to go and manually enter version 5.0.0 as shown in the screenshot below: 

<img width="471" alt="Screenshot 2022-11-17 at 00 45 09" src="https://user-images.githubusercontent.com/17517771/202310744-a00f28c7-ccbb-499b-85ea-cf04527c701f.png">

**Comment by mreichelt** [comment]
Oh, I didn't see that a new version was out - or that it would include the fix for this! Thank you so much @summongr - I'll test it as soon as I get around to it and provide feedback 👍

**Comment by mreichelt** [comment]
I just tried it locally with version 5.0.0 - and indeed the previews appear again! Thank you so much! 🎉

**Comment by aleksandr-dorofeev** [comment]
[Release 5.0.0](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/5.0.0) is ready! I am closing this issue.
