### ISSUE TITLE
Cannot archive Mac app with multiple embedded XPC targets

### ISSUE THREAD

**Issue by thermogl** [microsoft/appcenter-sdk-apple#2430]
### **Description**

I'm building a Mac Catalyst application that has an embedded XPC service which embeds a LaunchService. I've added AppCenter as a Swift package, and it is listed in the _Link Binary With Libraries_ Build Phase for all three targets. This builds and runs fine, all works as expected. 

To deploy the software, I'm running a GitHub action. The action first builds the project using the Release configuration, then tries to Archive it. The Archive is what is failing for me with:

```
error: Multiple commands produce '/Users/runner/Library/Developer/Xcode/DerivedData/Muse-cobuxzghcnyqnodwqwhioiepgkwt/Build/Intermediates.noindex/ArchiveIntermediates/Muse/IntermediateBuildFilesPath/UninstalledProducts/macosx/AppCenter.o'
[51](https://github.com/staffpad/Muse/runs/8265091786?check_suite_focus=true#step:10:52)
    note: Target 'AppCenter' (project 'AppCenter') has a command with output '/Users/runner/Library/Developer/Xcode/DerivedData/Muse-cobuxzghcnyqnodwqwhioiepgkwt/Build/Intermediates.noindex/ArchiveIntermediates/Muse/IntermediateBuildFilesPath/UninstalledProducts/macosx/AppCenter.o'
[52](https://github.com/staffpad/Muse/runs/8265091786?check_suite_focus=true#step:10:53)
    note: Target 'AppCenter' (project 'AppCenter') has a command with output '/Users/runner/Library/Developer/Xcode/DerivedData/Muse-cobuxzghcnyqnodwqwhioiepgkwt/Build/Intermediates.noindex/ArchiveIntermediates/Muse/IntermediateBuildFilesPath/UninstalledProducts/macosx/AppCenter.o'
[53](https://github.com/staffpad/Muse/runs/8265091786?check_suite_focus=true#step:10:54)
error: Multiple commands produce '/Users/runner/Library/Developer/Xcode/DerivedData/Muse-cobuxzghcnyqnodwqwhioiepgkwt/Build/Intermediates.noindex/ArchiveIntermediates/Muse/IntermediateBuildFilesPath/UninstalledProducts/macosx/AppCenterCrashes.o'
[54](https://github.com/staffpad/Muse/runs/8265091786?check_suite_focus=true#step:10:55)
    note: Target 'AppCenterCrashes' (project 'AppCenter') has a command with output '/Users/runner/Library/Developer/Xcode/DerivedData/Muse-cobuxzghcnyqnodwqwhioiepgkwt/Build/Intermediates.noindex/ArchiveIntermediates/Muse/IntermediateBuildFilesPath/UninstalledProducts/macosx/AppCenterCrashes.o'
[55](https://github.com/staffpad/Muse/runs/8265091786?check_suite_focus=true#step:10:56)
    note: Target 'AppCenterCrashes' (project 'AppCenter') has a command with output '/Users/runner/Library/Developer/Xcode/DerivedData/Muse-cobuxzghcnyqnodwqwhioiepgkwt/Build/Intermediates.noindex/ArchiveIntermediates/Muse/IntermediateBuildFilesPath/UninstalledProducts/macosx/AppCenterCrashes.o'
[56](https://github.com/staffpad/Muse/runs/8265091786?check_suite_focus=true#step:10:57)
error: Multiple commands produce '/Users/runner/Library/Developer/Xcode/DerivedData/Muse-cobuxzghcnyqnodwqwhioiepgkwt/Build/Intermediates.noindex/ArchiveIntermediates/Muse/IntermediateBuildFilesPath/UninstalledProducts/macosx/CrashReporter.o'
[57](https://github.com/staffpad/Muse/runs/8265091786?check_suite_focus=true#step:10:58)
    note: Target 'CrashReporter' (project 'PLCrashReporter') has a command with output '/Users/runner/Library/Developer/Xcode/DerivedData/Muse-cobuxzghcnyqnodwqwhioiepgkwt/Build/Intermediates.noindex/ArchiveIntermediates/Muse/IntermediateBuildFilesPath/UninstalledProducts/macosx/CrashReporter.o'
[58](https://github.com/staffpad/Muse/runs/8265091786?check_suite_focus=true#step:10:59)
    note: Target 'CrashReporter' (project 'PLCrashReporter') has a command with output '/Users/runner/Library/Developer/Xcode/DerivedData/Muse-cobuxzghcnyqnodwqwhioiepgkwt/Build/Intermediates.noindex/ArchiveIntermediates/Muse/IntermediateBuildFilesPath/UninstalledProducts/macosx/CrashReporter.o'
```

Is there some configuration step I'm missing?

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a new Mac Catalyst application
2. Create a new XPC Service 
3. Create a new LaunchService
4. Embed the LaunchService inside the XPC Service
5. Embed the XPC Service inside the Mac Catalyst application
6. Archive the Mac Catalyst application

### **Details**

1. Which SDK version are you using?
    - 4.4.3
2. Which OS version did you experience the issue on?
    - macOS 12.5
5. Which Xcode version did you build the app with?
    - Xcode 13.4.1
6. Which Cocoapods version are you using (run `pod --version`)?
    - N/A
7. What device version did you see this error on?  Were you using an emulator or a physical device?
    - macOS 12.5 Hosted Agent (GitHub)
8. What language are you using?
    - [ ] Objective C
    - [x] Swift
9. What third party libraries are you using?
  - N/A

**Comment by MikhailSuendukov** [comment]
Hi @thermogl and thanks for contacting us. Your repro does not describe how you integrate AppCenter in your application, the same for embedding steps. It would also be helpful if you could specify which libraries you are using. Building and archiving with your configuration normally works locally?

**Comment by thermogl** [comment]
I'm using Swift Package Manager for integration and trying to link AppCenterCrashes.

Archiving doesn't work locally either for the same reason as CI fails.

**Comment by AnatolyPristensky** [comment]
Hello @thermogl, I'm trying to reproduce your issue, but on the first sight it looks similar with the issues that have been discussed on Apple forums. Looks like that issue related to Xcode and project configurations. [Here](https://developer.apple.com/forums/thread/681831) and [here](https://developer.apple.com/forums/thread/679542). While I'm trying to reproduce it, could you please check above solutions?

**Comment by thermogl** [comment]
I did come across both of those in my travels too but neither seemed to have any impact 😔

**Comment by thermogl** [comment]
Yeah sure I'll do that over the weekend!

**Comment by aleksandr-dorofeev** [comment]
> 

Were you able to create a sample app? Do you have updates in this area?

**Comment by aleksandr-dorofeev** [comment]
@thermogl Were you able to create a sample app? Do you have updates in this area?

**Comment by thermogl** [comment]
Sorry the weekend got away from me (god save the queen?). I'm going to close this issue until I have some time to help reproduce the problem.
