### ISSUE TITLE
Xcode 14.0 

### ISSUE THREAD

**Issue by Krahulik** [microsoft/appcenter-sdk-apple#2432]
### **SDK cannot be built with Xcode 14.0**

Build of AppCenter macOS Framework fails with an error:
'+load' is called at app startup and can increase launch time; consider using '+initialize' instead

### **Details**
SDK 4.4.3
macOS 12.5.1
Xcode 14.0(14A309)

**Comment by MatkovIvan** [comment]
Yep, already working on it (`feature/xcode-14` branch)

**Comment by honkmaster** [comment]
@MatkovIvan When will version 5.0.0. be released?

**Comment by MikhailSuendukov** [comment]
Hi @MatkovIvan, the apple SDK is planned to be released within two weeks.
