### ISSUE TITLE
Increase Mac deployment target to 10.13

### ISSUE THREAD

**Issue by ksuther** [microsoft/appcenter-sdk-apple#2442]
### **Description**

Xcode 14 now shows a warning if the deployment target is below 10.13. The deployment target for iOS was increased in 8bb1bb6ee938b998cce9e4fa537b6bc89e5c63ee and it would be great if the same could be done for Mac (both here and in PLCrashReporter).

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Build App Center for Mac with Xcode 14
2. Xcode shows warnings about MACOSX_DEPLOYMENT_TARGET

### **Details**

1. Which SDK version are you using?
    - 5.0.0
2. Which OS version did you experience the issue on?
    - N/A
3. Which Xcode version did you build the app with?
    - Xcode 14.1
5. Which Cocoapods version are you using (run `pod --version`)?
    - N/A
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - N/A
7. What language are you using?
    - [x] Objective C
    - [x] Swift

**Comment by AnatolyPristensky** [comment]
Hello @ksuther, the bug is confirmed. I've created an item on our internal dashboard. Will update this thread once bug is fixed.
