### ISSUE TITLE
Correlate logs using SessionId

### ISSUE THREAD

**Issue by thomas-vercoutre-nzta** [microsoft/appcenter-sdk-apple#2462]
I'm trying to correlate logs between our iOS app and our backend.
All the logs are sent to ApplicationInsights and I was trying to get the current SessionID so I can add it as a header when calling the backend API.

Is there a way to get the current SessionID ? Was checking the code and it seems it is all internal ?

**Comment by aleksandr-dorofeev** [comment]
Hello @thomas-vercoutre-nzta thanks for getting in touch with us!
We are not planning to provide an API for retrieving a session id. Also, you can do correlation using custom define property. Also related:
https://github.com/microsoft/appcenter-sdk-react-native/issues/994
https://github.com/microsoft/appcenter/issues/2469
https://github.com/microsoft/appcenter/issues/1838

**Comment by thomas-vercoutre-nzta** [comment]
Hi @aleksandr-dorofeev, I wasn't talking about creating a new API but make the internal sessionID available. something like AppCenter.SessionID so we can use that.
I'm trying to implement W3C Context tracing (see [documentation](https://learn.microsoft.com/en-us/azure/azure-monitor/app/correlation#correlation-headers-using-w3c-tracecontext)) but the AppCenter SDK doesn't provide anything to do modern correlation.
