### ISSUE TITLE
crash with MSACUtility unarchiveKeyedData on 4.4.2

### ISSUE THREAD

**Issue by happysally001** [microsoft/appcenter-sdk-apple#2465]
### **Description**

crash with MSACUtility unarchiveKeyedData on 4.4.2

### **Repro Steps**

Please list the steps used to reproduce your issue.

crash report
Thread 8 Crashed: 
0   libobjc.A.dylib                      0x00000001c77d9c08 objc_msgSend + 8 
1   CoreFoundation                       0x00000001ce4b2104 -[__NSDictionaryM objectForKeyedSubscript:] + 160 
2   TeamSpaceApp                         0x000000010b5adfa0 +[MSACUtility unarchiveKeyedData:] (MSACUtility.m:60) 
3   TeamSpaceApp                         0x000000010b5a9d2c -[MSACLogDBStorage logsWithCondition:andValues:] (MSACLogDBStorage.m:296) 
4   TeamSpaceApp                         0x000000010b5a90d0 -[MSACLogDBStorage loadLogsWithGroupId:limit:excludedTargetKeys:completionHandler:] (MSACLogDBStorage.m:201) 
5   TeamSpaceApp                         0x000000010b5875b8 -[MSACChannelUnitDefault flushQueue] (MSACChannelUnitDefault.m:302) 
6   libdispatch.dylib                    0x00000001d5a884b4 _dispatch_call_block_and_release + 28 
7   libdispatch.dylib                    0x00000001d5a89fdc _dispatch_client_callout + 16 
8   libdispatch.dylib                    0x00000001d5a91694 _dispatch_lane_serial_drain + 668 
9   libdispatch.dylib                    0x00000001d5a921e0 _dispatch_lane_invoke + 380 
10  libdispatch.dylib                    0x00000001d5a9ce10 _dispatch_workloop_worker_thread + 648 
11  libsystem_pthread.dylib              0x000000021b513df8 _pthread_wqthread + 284 
12  libsystem_pthread.dylib              0x000000021b513b98 start_wqthread + 4

https://appcenter.ms/orgs/thomas-olsen-er92/apps/Skype-Teams-iOS-Store/crashes/errors/1983203012u/reports?q=unarchiveKeyedData&searchType=all

### **Details**

1. Which SDK version are you using?
    - 4.4.2
2. Which OS version did you experience the issue on?
    - iOS 15 and 16
3. Which Xcode version did you build the app with?
    -  Xcode 14.1
5. Which Cocoapods version are you using (run `pod --version`)?
    - 1.11.3
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - physical device
7. What language are you using?
    - [X ] Objective C
    - [X ] Swift
8. What third party libraries are you using? n/a
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by AnatolyPristensky** [comment]
Hello @happysally001, could you please provide more information on your issue?
How we can to reproduce it?

**Comment by IlyaBausovAkvelon** [comment]
@happysally001 could you please provide repro steps and more information on your issue?

**Comment by DmitriyKirakosyan** [comment]
We haven't heard from you for a while, so I'm closing this issue. Please reopen if you have any update.
