### ISSUE TITLE
Something went wrong on our end

### ISSUE THREAD

**Issue by joaoricardoduarte** [microsoft/appcenter-sdk-apple#2466]
### **Description**

When I navigate to Diagnostics -> Issues, I am being presented with a page saying "Something went wrong on our end". This has been like that for weeks.

### **Details**

1. Which SDK version are you using?
5.0.0
2. Which OS version did you experience the issue on?
all
3. Which Xcode version did you build the app with?
Xcode 14.2
4. What language are you using?
    - [X] Objective C
    - [X] Swift

<img width="1604" alt="Screenshot 2023-02-08 at 12 16 53" src="https://user-images.githubusercontent.com/399969/217527555-c6d1f0b0-abd3-41b5-b380-0ade2896577b.png">

**Comment by MikhailSuendukov** [comment]
Hello @joaoricardoduarte, thank you for reaching out! For assistance, please contact support by clicking on the "?" icon on the App Center portal. Our support team will be happy to assist you.
Closing as not an SDK issue.
