### ISSUE TITLE
AppCenter Error when call AppCenter.start

### ISSUE THREAD

**Issue by QuentinWangWJJ** [microsoft/appcenter-sdk-apple#2468]
### **Description**

Hi, please help me. I update AppCenter SDK from 4.3.0 to 5.0.1 using pod install.
I'm seeing multiple [AppCenter] ERROR (log attached below) when Calling:
AppCenter.start(withAppSecret: xxx, services: [Analytics.self, Crashes.self])

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. AppCenter.start(withAppSecret: xxx, services: [Analytics.self, Crashes.self])

### **Details**

1. Which SDK version are you using?
    - 5.0.1
2. Which OS version did you experience the issue on?
    - iOS 16
3. Which Xcode version did you build the app with?
    - Xcode 14.2
5. Which Cocoapods version are you using (run `pod --version`)?
    - 1.11.3
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone 11 physical device
7. What language are you using?
    - [ ] Objective C
    - [ X] Swift
8. What third party libraries are you using?
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
[AppCenter] ERROR: +[MSACDBStorage executeQuery:inOpenedDatabase:withValues:usingBlock:]/357 Failed to finalize SQLite statement, result=5 database is locked
[AppCenter] ERROR: +[MSACDBStorage executeSelectionQuery:inOpenedDatabase:result:withValues:]_block_invoke/404 Query failed with error: 5 database is locked
[AppCenter] ERROR: -[MSACDBStorage executeQueryUsingBlock:]/129 Failed to open database with specified maximum size constraint.
[AppCenter] ERROR: +[MSACDBStorage executeQuery:inOpenedDatabase:withValues:usingBlock:]/357 Failed to finalize SQLite statement, result=5 database is locked
[AppCenter] ERROR: +[MSACDBStorage executeSelectionQuery:inOpenedDatabase:result:withValues:]_block_invoke/404 Query failed with error: 5 database is locked

**Comment by shadyabarada** [comment]
Hi @QuentinWangWJJ, thank you for reporting, we are working on identifying the issue and will get back to you as soon as possible.

**Comment by shadyabarada** [comment]
Hi @QuentinWangWJJ does it happen all the time? so the app center sdk is never starting successfully? Also, it only happens on version 5.0.1 of the sdk?

**Comment by QuentinWangWJJ** [comment]
Hi @shadyabarada , thanks for the reply. Yes,  it happens all the time for version 5.0.1. Version 4.3.0 works fine and I don't see the error message.

**Comment by shadyabarada** [comment]
Hi @QuentinWangWJJ , thank you for the reply, may I also please ask if you face the same issue with vesion 5.0.0 of the sdk?

**Comment by QuentinWangWJJ** [comment]
@shadyabarada Yes, 5.0.0 also has the same issue. I tried several versions between 4.3.0 and 5.0.1, Looks like only 4.3.0 works fine without errors.

**Comment by shadyabarada** [comment]
@QuentinWangWJJ Thank you for your reply, have you tried to remove and re pod install the sdk and relaunch your app?

**Comment by QuentinWangWJJ** [comment]
Hi @shadyabarada , I tried reinstall through pod, but still can see the errors. Meanwhile I am also seeing: 
[AppCenter] ERROR: +[MSACUtility unarchiveKeyedData:]/72 Unarchiving NSData failed with error: (null)
2023-02-21 15:53:46.461289-0500 
[AppCenter] ERROR: -[MSACLogDBStorage logsWithCondition:andValues:]/304 Deserialization failed for log with Id 370

**Comment by shadyabarada** [comment]
Hi @QuentinWangWJJ, thanks for the additional information. May I please ask for the full logs with the db error? This all happens on the on start call of the sdk correct?

**Comment by QuentinWangWJJ** [comment]
@shadyabarada Here it is:
2023-02-21 17:41:28.856418-0500 [AppCenter] ERROR: +[MSACUtility unarchiveKeyedData:]/72 Unarchiving NSData failed with error: (null)
2023-02-21 17:41:28.869982-0500 [AppCenter] ERROR: +[MSACDBStorage executeSelectionQuery:inOpenedDatabase:result:withValues:]_block_invoke/404 Query failed with error: 5
	database is locked
2023-02-21 17:41:28.869990-0500 [AppCenter] ERROR: +[MSACDBStorage executeQuery:inOpenedDatabase:withValues:usingBlock:]/357 Failed to finalize SQLite statement, result=5
	database is locked
2023-02-21 17:41:28.870069-0500 [AppCenter] ERROR: +[MSACDBStorage executeQuery:inOpenedDatabase:withValues:usingBlock:]/357 Failed to finalize SQLite statement, result=5
	database is locked
2023-02-21 17:41:28.870075-0500 [AppCenter] ERROR: -[MSACDBStorage executeQueryUsingBlock:]/129 Failed to open database with specified maximum size constraint.
2023-02-21 17:41:28.870079-0500 [AppCenter] ERROR: +[MSACDBStorage executeSelectionQuery:inOpenedDatabase:result:withValues:]_block_invoke/404 Query failed with error: 5
	database is locked
2023-02-21 17:41:28.870628-0500 [AppCenter] ERROR: +[MSACDBStorage executeNonSelectionQuery:inOpenedDatabase:withValues:]_block_invoke/333 Could not execute the statement, result=5
	database is locked
2023-02-21 17:41:28.870711-0500 [AppCenter] ERROR: +[MSACDBStorage executeQuery:inOpenedDatabase:withValues:usingBlock:]/357 Failed to finalize SQLite statement, result=5
	database is locked

**Comment by AnatolyPristensky** [comment]
@QuentinWangWJJ, unfortunately I'm unable to reproduce this issue from my side. 
Did you tried to reproduce it on empty project?
Also it would be great if you able to share an example application where issue is persist.

**Comment by aleksandr-dorofeev** [comment]
Hello @QuentinWangWJJ 
We haven't heard from you for a while, so I m closing this issue.
Please feel free to reopen it in case of new information.

**Comment by RTonnesen** [comment]
I'm experiencing this problem as well, with the same error messages.

I'm using AppCenter 5.0.1 though a Xamarin.Forms project.
Tested on:
- Physical iPhone 11 running iOS 16.3.1
- Physical iPhone 14 running iOS 16.4.1

I'll try to reproduce on an empty project.
