### ISSUE TITLE
_OBJC_CLASS_$_MSACAnalytics

### ISSUE THREAD

**Issue by MateuszLas421** [microsoft/appcenter-sdk-apple#2469]
## **Description**

`ld: warning: ignoring file Pods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/ios-arm64_arm64e/AppCenter.framework/AppCenter, file is universal (arm64,arm64e) but does not contain the x86_64 architecture: Pods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/ios-arm64_arm64e/AppCenter.framework/AppCenter
ld: warning: ignoring file Pods/AppCenter/AppCenter-SDK-Apple/AppCenterCrashes.xcframework/ios-arm64_arm64e/AppCenterCrashes.framework/AppCenterCrashes, file is universal (arm64,arm64e) but does not contain the x86_64 architecture: Pods/AppCenter/AppCenter-SDK-Apple/AppCenterCrashes.xcframework/ios-arm64_arm64e/AppCenterCrashes.framework/AppCenterCrashes
ld: warning: ignoring file Pods/AppCenter/AppCenter-SDK-Apple/AppCenterAnalytics.xcframework/ios-arm64_arm64e/AppCenterAnalytics.framework/AppCenterAnalytics, file is universal (arm64,arm64e) but does not contain the x86_64 architecture: Pods/AppCenter/AppCenter-SDK-Apple/AppCenterAnalytics.xcframework/ios-arm64_arm64e/AppCenterAnalytics.framework/AppCenterAnalytics
ld: warning: ignoring file Pods/FirebaseAnalytics/Frameworks/FirebaseAnalytics.xcframework/ios-arm64_armv7/FirebaseAnalytics.framework/FirebaseAnalytics, file is universal (armv7,arm64) but does not contain the x86_64 architecture: Pods/FirebaseAnalytics/Frameworks/FirebaseAnalytics.xcframework/ios-arm64_armv7/FirebaseAnalytics.framework/FirebaseAnalytics
ld: warning: ignoring file Pods/GoogleAppMeasurement/Frameworks/GoogleAppMeasurementIdentitySupport.xcframework/ios-arm64_armv7/GoogleAppMeasurementIdentitySupport.framework/GoogleAppMeasurementIdentitySupport, file is universal (armv7,arm64) but does not contain the x86_64 architecture: Pods/GoogleAppMeasurement/Frameworks/GoogleAppMeasurementIdentitySupport.xcframework/ios-arm64_armv7/GoogleAppMeasurementIdentitySupport.framework/GoogleAppMeasurementIdentitySupport
ld: warning: ignoring file Pods/GoogleAppMeasurement/Frameworks/GoogleAppMeasurement.xcframework/ios-arm64_armv7/GoogleAppMeasurement.framework/GoogleAppMeasurement, file is universal (armv7,arm64) but does not contain the x86_64 architecture: Pods/GoogleAppMeasurement/Frameworks/GoogleAppMeasurement.xcframework/ios-arm64_armv7/GoogleAppMeasurement.framework/GoogleAppMeasurement
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MSACAnalytics", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_MSACAppCenter", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_MSACCrashes", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64`

### **Details**

1. Which SDK version are you using?
    - e.g. 5.0.1
2. Which OS version did you experience the issue on?
    - e.g. iOS 16
3. Which Xcode version did you build the app with?
    - e.g. Xcode 14.2
5. Which Cocoapods version are you using (run `pod --version`)?
    - e.g. 1.12.0
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone 14 emulator
7. What language are you using?
    - [ ] Objective C
    - [ X] Swift
8. What third party libraries are you using?
9. `        AppCenter.start(withAppSecret: "key", services:[
            Analytics.self,
            Crashes.self,
        ])`. 
 I modified the project settings to arm64 and it still has the same problem. Something else needs to be set for the library to work ?

**Comment by vvechkanov** [comment]
Hello @MateuszLas421!
Thank your question. For helping you I need some additional information. If you can provide some sample application, it would be great, if not we will try to help you without it. 
Did you modify fields "Valid architecture" or "Architectures/Debug" or "Architectures/Release" AppCenter targets? Can you please send what values your project has for this configuration keys?

**Comment by aleksandr-dorofeev** [comment]
Hello @MateuszLas421 
We haven't heard from you for a while, so I m closing this issue.
Please feel free to reopen it in case of new information.
