### ISSUE TITLE
Unable to use both Firebase crashlytics and App Center Crashes in the same project

### ISSUE THREAD

**Issue by chaithanyaprathyush** [microsoft/appcenter-sdk-apple#2482]
I wanted to use both Crashlytics and AppCenter crashes in the same project. 
AFIK currently this is not possible and Firebase throws an error if both these libraries are integrated in the same project. 
Would it be possible to have App Center crashes and other crash reporting tools in iOS working in parallel?

**Comment by AnatolyPristensky** [comment]
Hello @chaithanyaprathyush, unfortunately there is no opportunity to use App Center crashes and other crash reporting tool in parallel. When one crash tool is catching the crash - another will not get it. I'm closing this issue, but feel free to reopen it if you have additional questions.
