### ISSUE TITLE
Support Xcode 15

### ISSUE THREAD

**Issue by hadiidbouk** [microsoft/appcenter-sdk-apple#2484]
### **Description**

It seems that there is problems when building my app with Xcode 15; the appcenter package can't find `#import "MSACDistributeIngestion.h"`

![Screenshot 2023-06-07 at 2 38 37 PM](https://github.com/microsoft/appcenter-sdk-apple/assets/19314956/5d82977d-572b-490a-bfa1-386801682f86)

![Screenshot 2023-06-07 at 2 38 30 PM](https://github.com/microsoft/appcenter-sdk-apple/assets/19314956/4dda0740-0ad5-4be2-a993-23f299986154)

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install Xcode 15 beta
2. Install the appcenter SDK using SPM.
2. Build your project

### **Details**

1. Which SDK version are you using?
    - 4.4.3
2. Which OS version did you experience the issue on?
    - iOS 17
3. Which Xcode version did you build the app with?
    - Xcode 15 beta
5. Which Cocoapods version are you using (run `pod --version`)?
    - N/A
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone 14 Pro
7. What language are you using?
    - [ ] Objective C
    - [x] Swift
8. What third party libraries are you using?
N/A
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
N/A

**Comment by hadiidbouk** [comment]
**UPDATE:**

The problem is also happening on version `5.0.2`.

**Comment by AnatolyPristensky** [comment]
Hello @hadiidbouk, thank you for the information. 
We've filed an item on our task list and will update this issue once support of Xcode15 will be added.

**Comment by AnatolyPristensky** [comment]
@hadiidbouk, the fix has been merged and will be available in the next release.

**Comment by hadiidbouk** [comment]
Thank you @AnatolyPristensky!

**Comment by kaybutter** [comment]
It looks like Xcode 15 beta 3 brought some new Linker problems. Technically different from the original issue, but since this is about Xcode 15 support:
```
ld: null objc class data for '_OBJC_METACLASS_$_PLCrashHostInfo' in '/Users/kay/Library/Developer/Xcode/DerivedData/Applause-cblnwbdzxvnoeweifdogbatpgjtb/Build/Products/Debug-iphonesimulator/CrashReporter.o'
clang: error: linker command failed with exit code 1 (use -v to see invocation) 
```

**Comment by kaybutter** [comment]
Opting out of the new linker by using `-ld64` in Other Linker Flags fixes both this and the original issue (but it also sacrifices all the performance improvements of the new linker)

**Comment by AnatolyPristensky** [comment]
@kaybutter, thank you for the update. 
We've filed an item on our internal dashboard. Will update this thread once issue is fixed.

**Comment by MikhailSuendukov** [comment]
I'm glad you found the workaround. Unfortunately, I could not find information about this error. Judging by the method of fixing, the error may lie in the new linker in XCode 15 beta. If you come across any additional insights or details about this error, we would greatly appreciate your sharing them with us. I think that we will wait for this fix in the next versions of XCode.

**Comment by iudovenko** [comment]
Linker issue fixed in xcode 15 beta 5
