### ISSUE TITLE
Support for visionOS

### ISSUE THREAD

**Issue by daniele-pizziconi** [microsoft/appcenter-sdk-apple#2490]
**Is your feature request related to a problem? Please describe.**
With the new Xcode 15 beta 2 and with the new visionOS/xrOS platform, due to the usage of unavailable APIs, the current project fails to build.

**Describe the solution you'd like**
Adding support for the new platform.

**Describe alternatives you've considered**
N/A

**Additional context**
<img width="1184" alt="image" src="https://github.com/microsoft/appcenter-sdk-apple/assets/927841/42c97440-c890-4407-8fdc-86ad72af872d">

**Comment by MikhailSuendukov** [comment]
Thank you for reaching out to us, and thank you very much for your feature request.

**Comment by gklka** [comment]
We would really appreciate if you'd add support for visionOS too.

**Comment by gongzhang** [comment]
Same request here. 🙏

I have a port for visionOS based on version 4.4.3, but I don't have the time to update it to the latest version or open a PR. I hope this helps with the issue.

https://github.com/gongzhang/appcenter-sdk-apple/compare/4.4.3-xcode15rc...gongzhang:appcenter-sdk-apple:xros
