### ISSUE TITLE
Package does not build for ARM architecture

### ISSUE THREAD

**Issue by wendellli99** [microsoft/appcenter-sdk-apple#2491]
### **Description**

The package does not support ARM architecture. I'm encountering build errors seen here.

<img width="628" alt="Screenshot 2023-07-14 at 16 51 42" src="https://github.com/microsoft/appcenter-sdk-apple/assets/34215792/b8e9bc11-0426-41c5-9967-bf528c05ba86">
<img width="838" alt="Screenshot 2023-07-20 at 13 23 08" src="https://github.com/microsoft/appcenter-sdk-apple/assets/34215792/4ad31148-2e18-4136-91c9-be2dd7bf9c0e">

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create an Xcode project.
2. Add the library https://github.com/microsoft/appcenter-sdk-apple.git as a SPM dependency.
3. Add `AppCenter.start(withAppSecret: appCenterSecret, services: [Analytics.self, Crashes.self])` in AppDelegate.
4. Build the project on an ARM-based Mac or set 'Build Active Architecture Only' to 'NO' in the project's build settings. 

### **Details**

1. Which SDK version are you using?
    5.0.3
2. Which OS version did you experience the issue on?
    macOS 13.4.1
5. Which Xcode version did you build the app with?
    Xcode 14.3.1 (14E300c)
6. Which Cocoapods version are you using (run `pod --version`)?
    I'm using SPM.
7. What device version did you see this error on?  Were you using an emulator or a physical device?
    Both Intel and ARM-based Macs.
8. What language are you using?
    - [ ] Objective C
    - [x] Swift
9. What third party libraries are you using? Not using any other packages.
10. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here: The issue is with xcodebuild not the runtime so N/A here.

**Comment by AnatolyPristensky** [comment]
Hello @wendellli99, unfortunately we unable to reproduce your issue on empty project. arm64 architecture works as expected. Also, Apple Silicon support has been added since version 4.0.0: [Support Apple Silicon](https://github.com/microsoft/appcenter/issues/1927#issuecomment-725596464). 

Could you please try to follow [this migration guide ](https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/migration/apple-sdk-update)and report results?

**Comment by wendellli99** [comment]
Thank you for the info. The error went away after choosing 'Build for any Mac'.
