### ISSUE TITLE
Update App Center SDK to include privacy manifest

### ISSUE THREAD

**Issue by CloudosaurusRex** [microsoft/appcenter-sdk-apple#2494]
At WWDC23 Apple announced that apps and SDKs that make use of certain "required reason" APIs will need to provide a privacy manifest.

It looks like the App Center SDKs will need to do this because, amongst others, they make use of `UserDefaults`, which is now considered a "required reason" API.

Is this update on the roadmap for the team? I appreciate that enforcement won't happen until Spring 2024 but I wanted to make contact so that we can plan our own app releases to take this into account.

For more info, see:

- [Describing data use in privacy manifests | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)
- [Describing use of required reason API | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)
- [Get started with privacy manifests - WWDC23 - Videos - Apple Developer](https://developer.apple.com/videos/play/wwdc2023/10060/)

Thanks!

**Comment by AnatolyPristensky** [comment]
Hello @CloudosaurusRex, thank you for your feature request. We will discuss it with a team and get back to you with an update.

**Comment by DmitriyKirakosyan** [comment]
Hi @CloudosaurusRex,

Apologies for the wait in getting back to you. This is certainly on our radar. We've added an entry to our task board and will be prioritizing its resolution. Thanks for your patience!

**Comment by jamidheeraj** [comment]
@DmitriyKirakosyan @AnatolyPristensky Thank you for fixing the privacy manifest for the AppCenter SDK
May I know when the new version v5.0.5 would be released? Also a timeline would be great.
Thank you

**Comment by CraigAtCochlear** [comment]
@DmitriyKirakosyan not wanting to pile on here but for Regulatory reasons we can only use official releases and with the 1 May deadline being just two weeks away it is causing some concern for us. Any indications of a when a release could be expected would help guide us.

**Comment by akhilvswoodplc** [comment]
Any update on this

**Comment by zafrkaya** [comment]
Hello, is there any progress on this topic?

**Comment by moeenyousafi** [comment]
Now it's 5 days from deadline, i could not understand why app center is not releasing new versions.

**Comment by aalivp** [comment]
Any Update on this?

**Comment by taqiraza** [comment]
Any update on this please?

**Comment by DmitriyKirakosyan** [comment]
We're currently in the process of finalizing the release. To ensure you're not blocked by our timeline, please add these fields into your `PrivacyInfo` file:

[App Center PrivacyInfo.xcprivacy](https://github.com/microsoft/appcenter-sdk-apple/blob/develop/AppCenter/PrivacyInfo.xcprivacy)
[App Center Crashes PrivacyInfo.xcprivacy](https://github.com/microsoft/appcenter-sdk-apple/blob/develop/AppCenterCrashes/PrivacyInfo.xcprivacy)

**Comment by twilightDD** [comment]
[Landrix alpha-PrivacyReport 2024-05-10 13-07-17.pdf](https://github.com/microsoft/appcenter-sdk-apple/files/15274333/Landrix.alpha-PrivacyReport.2024-05-10.13-07-17.pdf)

**Comment by DmitriyKirakosyan** [comment]
Version 5.0.5, which includes the fix, has been released.
