### ISSUE TITLE
Add documentation for dataResidencyRegion

### ISSUE THREAD

**Issue by goetzf** [microsoft/appcenter-sdk-apple#2509]
**Is your feature request related to a problem? Please describe.**
AppCenter 5.0.4 added support for specifying a data residency region. However, I wasn't able to find any documentation which regions are available. 

**Describe the solution you'd like**
Could you please add documentation for possible values of `dataResidencyRegion`? Or did I just miss it?

**Comment by DmitriyKirakosyan** [comment]
@goetzf This is an internal API, and as such, there is no documentation available for it.

**Comment by goetzf** [comment]
It's a public property in `MSACAppCenter.h`, so it didn't look like internal API to me.

**Comment by DmitriyKirakosyan** [comment]
@goetzf , I'm sorry for the confusion, I meant that this public API for internal usage only.
