### ISSUE TITLE
Protobuf: could not find object file symbol for symbol

### ISSUE THREAD

**Issue by eaigner** [microsoft/appcenter-sdk-apple#2514]
### **Description**

Since macOS 14.0 Xcode 15 always spits out those warnings on compile

```
warning: (arm64)  could not find object file symbol for symbol _protobuf_c_version
warning: (arm64)  could not find object file symbol for symbol _protobuf_c_empty_string
warning: (arm64)  could not find object file symbol for symbol _plcrash_async_byteorder_swapped
warning: (arm64)  could not find object file symbol for symbol _protobuf_c__allocator
warning: (arm64)  could not find object file symbol for symbol _shared_image_list
```

Protobuf seems to be a dependency of `PLCrashReporter`

### **Repro Steps**

1. Compile a project with AppCenter included on macOS 14 / Xcode 15

### **Details**

1. Which SDK version are you using?
    - 5.0.4
2. Which OS version did you experience the issue on?
    - macOS 14.0 and 14.1
3. Which Xcode version did you build the app with?
    - Xcode 15.0.1 (15A507)
5. Which Cocoapods version are you using (run `pod --version`)?
    - NONE
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Mac mini Pro M2
7. What language are you using?
    - [ ] Objective C
    - [x] Swift
8. What third party libraries are you using?
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by art-ghub** [comment]
Hi, I'm observing same issue, absolutely same conditions except 1. SDK is 5.0.3. 
Using SPM.

**Comment by DmitriyKirakosyan** [comment]
@art-ghub , apart from the warnings, does the SDK work correctly? Have you tried integrating it via cocoapods or binaries instead of SPM and check if it helps?

**Comment by art-ghub** [comment]
No, I haven't tried. It's not a linker warning, it's fired on .dSYM generation stage:

`GenerateDSYMFile /Users/<skipped>.app.dSYM <skipped>.app/<skipped> (in target '<skipped>' from project '<skipped>')`

**Comment by DmitriyKirakosyan** [comment]
@art-ghub thanks for the clarification. Do these warnings cause any actual problems? Any issues spotted with the SDK in action?

@eaigner, are you also encountering the dSYM issue on your end?

**Comment by DmitriyKirakosyan** [comment]
This issue will be closed due to inactivity. If the problem continues, please feel free to reopen it or let me know.

**Comment by francosolerio** [comment]
The issue is still present.

```
warning: (arm64)  could not find object file symbol for symbol _protobuf_c_version
warning: (arm64)  could not find object file symbol for symbol _protobuf_c_empty_string
warning: (arm64)  could not find object file symbol for symbol _plcrash_async_byteorder_swapped
warning: (arm64)  could not find object file symbol for symbol _protobuf_c__allocator
warning: (arm64)  could not find object file symbol for symbol _shared_image_list

```

**Comment by eaigner** [comment]
I use SPM. And the issue is still present Dec 23 - Xcode Version 15.1 (15C65), macOS 14.2.1 (23C71), AppCenter 5.0.4

**Comment by francosolerio** [comment]
No specific issues observed, but keeping our compilation results clean is always good code hygiene. When you let warnings accumulate, sooner or later you will not catch the one that will put you in trouble. For this reason some dev teams turn on "treat compiler warnings as errors" as company policy, in this case AppCenter becomes unusable.

**Comment by MikhailSuendukov** [comment]
I tried to reproduce this error on an empty project, but when building the application, such warnings did not occur. Therefore, it would be very useful to further investigation of this error to get a small demo application on which this error will be reproduced.

**Comment by francosolerio** [comment]
Create a new project in XCode (iOS app, SwiftUI). Add package App Center. Instead of simple Build issue an Archive command (menu: Product -> Archive). Look in the issue navigator.

If you enable DWARF with DSYM File in the build options for debug builds, you will see the same warnings issuing a simple build command too.

You can download a sample project here: https://digitalia-media.s3-eu-west-1.amazonaws.com/temp/AppCenterTest.zip

**Comment by patrickhartling** [comment]
We see the very same warnings from the linker when building our app using Xcode 15.0 through the current 15.3 beta. Our use of PLCrashReporter via SPM comes in from a different Swift package entirely. In other words, we do not use the AppCenter SDK, but PLCrashReporter and its use of protobuf leads to the same warnings when linking the application binary.

**Comment by MikhailSuendukov** [comment]
Hi everyone, and sorry for the long delay, and thanks for your demo application, I was able to reproduce this behavior. Indeed, these warnings come from the PLCrashReporter package.
Hi @patrickhartling, could you please confirm what this warning is reproducible on version 14 of xCode?

**Comment by patrickhartling** [comment]
@MikhailSuendukov The app I work on no requires Swift 5.9 and will not build with Xcode 14. Hence, I cannot get to the point where the linker would be run. I am quite confident, though, that these warnings from the linker started with Xcode 15.0.

**Comment by lksoft** [comment]
I am seeing the same warnings for a macOS app that has only PLCrashReporter added/linked into it. I am not seeing any visible issues, however, as @francosolerio mentioned we like to keep the project clean to identifier real errors easier.

The app is a mix of Obj-C & Swift. The code is being called from Obj-C, though i doubt that has an impact. Building in Xcode 15.2 on Sonoma 14.2.1. PLCrashReporter was added via SPM.

Hope that helps.

BTW, I am adding here, since this was literally the only hit for the error message I got and seemed appropriate, despite it obviously being an issue with PLCrashReporter instead of the AppCenter SDK. 

Sorry if that is inappropriate.

**Comment by patrickhartling** [comment]
@lksoft 

>  this was literally the only hit for the error message I got and seemed appropriate

That was my experience as well. I was relieved to find this issue because it seemed like no one else was experiencing the reported behavior.

> despite it obviously being an issue with PLCrashReporter instead of the AppCenter SDK.

I have tried to create a standalone project that just has PLCrashReporter as a dependency but have yet to be able to reproduce the warnings that way. I wonder if the combination of Objective-C and Swift is somehow a factor. It sounds like we're in a similar arrangement to you in terms of languages and tools, though in our case, it's Swift code that called into the PLCrashReporter package.

**Comment by Ginluck** [comment]
These types of warnings are as high as 70000 in my XCode, causing me to experience abnormal lag every time I compile a project. Please let me know the solution. Thank you
![Uploading 123.png…]()

**Comment by patrickhartling** [comment]
FWIW, we aren't seeing the warning from the linker related to PLCrashReporter when using Xcode 15.3.

**Comment by Ginluck** [comment]
> FWIW，在使用 Xcode 15.3 时，我们没有看到来自与 PLCrashReporter 相关的链接器的警告。
My warning is not related to PLCrashReporter. Please pay attention to the image I provided and inform me of how to address the issue. Thank you for the trouble you are going through.
![123](https://github.com/microsoft/appcenter-sdk-apple/assets/22724309/6d248b8f-f253-442f-b07c-91c852313ae4)

**Comment by Ginluck** [comment]
> 值得一提的是，当使用 Xcode 15.3 时，我们没有看到与 PLCrashReporter 相关的链接器的警告。

![331421290-6d248b8f-f253-442f-b07c-91c852313ae4](https://github.com/microsoft/appcenter-sdk-apple/assets/22724309/5ccd5d7e-a702-405c-bac3-316a5f80881e)
can you help me what can i do ;i feel so sad with xcode

**Comment by xxyu98** [comment]
![image](https://github.com/user-attachments/assets/e6dd206c-22d6-477b-99db-d457707e21fc)
Flutter encountered similar issues after using the Gaode SDK, accompanied by XCode editing lag and frequent 100% cuping

**Comment by lyf571321556** [comment]
> ![image](https://github.com/user-attachments/assets/e6dd206c-22d6-477b-99db-d457707e21fc) Flutter encountered similar issues after using the Gaode SDK, accompanied by XCode editing lag and frequent 100% cuping

same issue.
