### ISSUE TITLE
Freeze on iOS Platform When App Crashes in KMM Project

### ISSUE THREAD

**Issue by bahmanShahveisi** [microsoft/appcenter-sdk-apple#2519]
### **Description**

I'm using the following code to add Microsoft AppCenter to a KMM project to register crash and event logs. However, since Microsoft AppCenter is not a Kotlin Multiplatform library and is specifically developed for Android, iOS, etc., I cannot add it to commonMain.dependencies, androidMain.dependencies, or iosMain.dependencies. Instead, I need to add it separately for Android and iOS.

I followed the documentation provided for Android [here](https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/android) and for iOS [here](https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/ios).

Currently, the code works correctly for Android, registering both crash reports and events. However, for iOS, when the app crashes, instead of reporting the crash, the application completely freezes. However, events are still successfully registered and sent. The documentation is implemented correctly, but I don't know why this issue is occurring.

I've followed the same process and similar code for a standalone iOS project, and crash reports and events are successfully registered. However, in the KMM project, crash reports are not working for iOS, and the app freezes instead. Can you tell me if this issue is related to AppCenter itself?

### **Details**
// shared/build.gradle.kts

plugins {
    ...
}

kotlin {
    androidTarget {
        ...
    }
    iosX64()
    iosArm64()
    iosSimulatorArm64()

    cocoapods {
        ....
        version = "1.0"
        ios.deploymentTarget = "17.0"
        podfile = project.file("../iosApp/Podfile")
        framework {
            baseName = "shared"
            isStatic = true
            ...
        }
        ...
        pod("AppCenter")
    }

    sourceSets {
     ...
    }
}

android {
    namespace = libs.versions.bundle.get()
    compileSdk = libs.versions.compileSDK.get().toInt()
    defaultConfig {
        minSdk = libs.versions.minSDK.get().toInt()
    }
}

sqldelight {
    ....
}

// Application.swift
class Application: NSObject, UIApplicationDelegate {
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
        initAppCenter()
        return true
    }
    
    fileprivate func initAppCenter() {
        AppCenter.start(withAppSecret: "...", services:[
        Analytics.self,
        Crashes.self
       ])
        Analytics.trackEvent("init:ios", withProperties: [
            "name" : "..."
        ])
    }
}

**Comment by alilyinooma** [comment]
+1

The same issue. If KMM throws an exception (for example, throw NotImplementedError()) - AppCenter hangs the app. IOS kills the app after about a minute.

App crashes naturally if AppCenter is not initialized.

@bahmanShahveisi did you find any workaround?

**Comment by alilyinooma** [comment]
I think we need to file a ticket against the PLCrashreporter. 

![Screenshot 2023-12-14 at 12 12 44 PM](https://github.com/microsoft/appcenter-sdk-apple/assets/111453493/bad569d9-958d-4479-a3b7-6b305c8fc69f)

**Comment by MikhailSuendukov** [comment]
Hello and thank you for reaching out to us, since the problem relates to the PLCrashReporter, then we will work on it in[ this issue](https://github.com/microsoft/plcrashreporter/issues/293). So I'm closing this issue as a duplicate.
