### ISSUE TITLE
AppCenter metrics and crash report errors.

### ISSUE THREAD

**Issue by javiersmo** [microsoft/appcenter-sdk-apple#2520]
### **Description**

Using AppCenter 5.0.4 in my project with CocoaPods I'm seeing multiple [AppCenter] ERROR (log attached below) when Calling:
AppCenter.start(withAppSecret: xxx, services: [Analytics.self, Crashes.self])

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. AppCenter.start(withAppSecret: xxx, services: [Analytics.self, Crashes.self])

### **Details**

1. Which SDK version are you using?
    - 5.0.4
2. Which OS version did you experience the issue on?
    - iOS 17.1.1
3. Which Xcode version did you build the app with?
    - Xcode 14.3.1
5. Which Cocoapods version are you using (run `pod --version`)?
    - 1.13.0
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone XR physical device
7. What language are you using?
    - [ ] Objective C
    - [ x] Swift
8. What third party libraries are you using?
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

2023-11-23 12:39:26.585233+0100 Development[1900:866631] [AppCenter] ERROR: +[MSACUtility unarchiveKeyedData:]/72 Unarchiving NSData failed with error: (null)
2023-11-23 12:39:26.585518+0100 Development[1900:866631] [AppCenter] ERROR: -[MSACLogDBStorage logsWithCondition:andValues:]/304 Deserialization failed for log with Id 31

**Comment by MikhailSuendukov** [comment]
Hi @javiersmo and sorry for long delay. Apparently your problem is similar to the issue described [here](https://github.com/microsoft/appcenter-sdk-apple/issues/2468). And it would be very useful for us to get a small demo application that reproduces your error so that we can investigate the root of the problem.

**Comment by MikhailSuendukov** [comment]
Closing it due to inactivity, if you still face this issue, feel free to reopen it.
