### ISSUE TITLE
Callbacks for PLCrashReporter are not exposed, resulting in an inability to flush logs 

### ISSUE THREAD

**Issue by dalemyers** [microsoft/appcenter-sdk-apple#2523]
### **Description**

PLCrashReporter has functionality to add a callback when a crash is detected. This functionality was also added to the Hockey SDK. However, it is not exposed in the App Center SDK. The result is that if a crash happens, we can't take any final steps, such as flushing logs to disk. This is a vital piece of functionality that our app needs.

**Comment by DmitriyKirakosyan** [comment]
Hi @dalemyers , thank you for reaching out!

I'm sorry for late reply, but we do not have plans to add support for this feature in the next year. I'm closing the issue.

Related:
https://github.com/microsoft/appcenter-sdk-apple/issues/1719
https://github.com/microsoft/appcenter-sdk-apple/issues/1982
