### ISSUE TITLE
Need a way to push log immediately

### ISSUE THREAD

**Issue by gbreen12** [microsoft/appcenter-sdk-apple#2525]
**Is your feature request related to a problem? Please describe.**
I am trying to debug some background task issues and the logs don't push when the app is going into the background nor will it send the last few messages when the background task is ending

**Describe the solution you'd like**
A method that synchronously sends the logs on demand with a timeout to make sure when going into the background it doesn't take too long

**Describe alternatives you've considered**
Wait on the main thread myself

**Comment by lucen-ms** [comment]
Thanks for your suggestion but we don't plan to implement it in the next year so I'm closing this ticket.
