### ISSUE TITLE
Missing NSPrivacyAccessedAPITypeReasons in App Privacy Manifest.

### ISSUE THREAD

**Issue by Muesly** [microsoft/appcenter-sdk-apple#2526]
### **Description**

For the new App Privacy Manifest files, in the Privacy API section it lists UserDefaults and File timestamps as relevant APIs, but there is no `NSPrivacyAccessedAPITypeReasons` listed for either.

See https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api, where is mentions that the reasons are required too.

```
<key>NSPrivacyAccessedAPITypes</key>
	<array>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategoryUserDefaults</string>
		</dict>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategoryFileTimestamp</string>
		</dict>
	</array>
```

**Comment by MikhailSuendukov** [comment]
Hello and thanks for reaching out to us, we'll take a look on it.

**Comment by DmitriyKirakosyan** [comment]
Version 5.0.5, which includes the fix, has been released.
