### ISSUE TITLE
AppCenter Podspec doesn't include the xcprivacy files

### ISSUE THREAD

**Issue by jdheerajcoding** [microsoft/appcenter-sdk-apple#2531]
### **Description**

AppCenter's podspec doesn't include the new file type - *.xcprivacy and due to which the privacy report doesn't include the addition of these new privacy files.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Add AppCenter pods such as Analytics, Crashes, Distribute to a demo app
2. Archive the project, right click on archive and generate privacy report
3. Privacy report should contain all the privacy info of all the three pods in one report.
4. Right now, it is empty

### **Details**

1. Which SDK version are you using?
    - 5.0.4
2. Which OS version did you experience the issue on?
    - iOS 17
5. Which Xcode version did you build the app with?
    - Xcode 15.2
6. Which Cocoapods version are you using (run `pod --version`)?
    - 1.15.2
7. What device version did you see this error on?  Were you using an emulator or a physical device?
    - NA
8. What language are you using?
    - [ ] Objective C
    - [x] Swift
9. What third party libraries are you using? NA
10. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
NA

**Comment by DmitriyKirakosyan** [comment]
Hi @jdheerajcoding , thank you for reaching out! We are distributing SDK as binaries via cocoapods. So the issue should be resolved once we ensure our binaries include the privacy manifest. Here is a PR in progress: https://github.com/microsoft/appcenter-sdk-apple/pull/2528

**Comment by jdheerajcoding** [comment]
> Hi @jdheerajcoding , thank you for reaching out! We are distributing SDK as binaries via cocoapods. So the issue should be resolved once we ensure our binaries include the privacy manifest. Here is a PR in progress: #2528

@DmitriyKirakosyan Do we currently have an issue with 5.0.4 because I see that privacy report doesnt mention anything about the app center usage.

**Comment by DmitriyKirakosyan** [comment]
@jdheerajcoding , the privacy manifest fix was not merged and released yet.

**Comment by hieu9102002** [comment]
Hi @DmitriyKirakosyan, the privacy manifest fix has been merged. Can we generate a new release with the fix? Thank you very much.

**Comment by jdheerajcoding** [comment]
@DmitriyKirakosyan Can we have a timeline of when the new version will be released?

**Comment by herreraemanuel** [comment]
Hi @DmitriyKirakosyan how are you doing? You have a timeline for the release of the new version with the privacy manifest? Thanks.

**Comment by jamidheeraj** [comment]
Hi @DmitriyKirakosyan @AnatolyPristensky the deadline for updates to app center guidelines involving Privacy manifests is May 1st 2024, which is around the corner. A new release version 5.0.5 would help us greatly by becoming compliant with Apple. Is there a timeline when the new appcenter version would be released?
Thanks

**Comment by DmitriyKirakosyan** [comment]
Version 5.0.5, which includes the fix, has been released.
