### ISSUE TITLE
Build failed due to AppCenter not found error

### ISSUE THREAD

**Issue by TungVuDuc2805** [microsoft/appcenter-sdk-apple#2532]
### **Description**
Hi guys, I got a problem with AppCenter's building process.
Looking at the debug logs I see that the error messages are:
```
Task         : Command Line
Description  : Run a command line with arguments
Version      : 1.1.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
##[error]Failed which: Not found appcenter: null
##[error]undefined failed with error: Failed which: Not found appcenter: null
```
### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Setting up AppCenter and iOS project from this [tutorial](https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/ios)
2. Run build on main branch

### **Details**

1. Which SDK version are you using?
    - e.g. 5.0.4
2. Which OS version did you experience the issue on?
    - e.g. iOS 16 +
3. Which Xcode version did you build the app with?
    - e.g. Xcode 15.2
5. Which Cocoapods version are you using (run `pod --version`)?
    - I'm using SMP
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - N/A
7. What language are you using?
    - Swift
8. What third party libraries are you using? AppCenter (Crashes, Analytics, Distribute)
10. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by MikhailSuendukov** [comment]
Hello @TungVuDuc2805, thank you for reaching out! For assistance, please contact support by clicking on the "?" icon on the App Center portal. Our support team will be happy to assist you.
Closing as not an SDK issue. If you have any questions for us, feel free to reopen the issue.
