### ISSUE TITLE
Any Crash Report/Analytics Alternatives?

### ISSUE THREAD

**Issue by gongzhang** [microsoft/appcenter-sdk-apple#2535]
Hey App Center Team,

Just heard about the retirement news, and it's been quite a journey! 🚀 **Big thanks for all the awesome work you've done.**

As heading towards the retirement date, I'm on the lookout for something as simple as App Center for crash logs and analytics. Checked out the Azure Native ISV Services, but they didn't quite hit the mark for me.

Got any recommendations for lightweight alternatives that play nice with iOS, macOS, visionOS and even watchOS?

Cheers and thanks a ton for everything!

**Comment by lucen-ms** [comment]
Hi @gongzhang we don't have any other recommendations besides what we posted to our announcement on https://aka.ms/appcenter/retire

**Comment by gongzhang** [comment]
@lucen-ms I understand. Thanks!
