### ISSUE TITLE
Invalid API Reason Declaration in Privacy Manifest for API Type NSPrivacyAccessedAPICategoryFileTimestamp

### ISSUE THREAD

**Issue by E-Rockalanche** [microsoft/appcenter-sdk-apple#2543]
### **Description**

The privacy manifest includes an invalid reason code for NSPrivacyAccessedAPICategoryFileTimestamp. Please see the following email snippet received from App Store Connect:

> Please correct the following issues and upload a new binary to App Store Connect.
> 
> ITMS-91055: Invalid API reason declaration - The PrivacyInfo.xcprivacy for the “Frameworks/AppCenterAnalytics.framework/AppCenterAnalytics” file contains “35F9.1” as the value for a NSPrivacyAccessedAPITypeReasons key instead of a valid reason code for using an API in the NSPrivacyAccessedAPICategoryFileTimestamp category. Values for NSPrivacyAccessedAPITypeReasons keys in any privacy manifest must be valid reason codes for the corresponding API category. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.
> 
> ITMS-91055: Invalid API reason declaration - The PrivacyInfo.xcprivacy for the “Frameworks/AppCenterCrashes.framework/AppCenterCrashes” file contains “35F9.1” as the value for a NSPrivacyAccessedAPITypeReasons key instead of a valid reason code for using an API in the NSPrivacyAccessedAPICategoryFileTimestamp category. Values for NSPrivacyAccessedAPITypeReasons keys in any privacy manifest must be valid reason codes for the corresponding API category. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.
> 
> ITMS-91055: Invalid API reason declaration - The PrivacyInfo.xcprivacy for the “Frameworks/AppCenter.framework/AppCenter” file contains “35F9.1” as the value for a NSPrivacyAccessedAPITypeReasons key instead of a valid reason code for using an API in the NSPrivacyAccessedAPICategoryFileTimestamp category. Values for NSPrivacyAccessedAPITypeReasons keys in any privacy manifest must be valid reason codes for the corresponding API category. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

### **Repro Steps**

Upload a build which embeds any of the AppCenter frameworks to Test Flight/App Store. Receive email from App Store Connect detailing issues with App Center privacy manifests.

### **Details**

1. Which SDK version are you using?
    - 5.0.4
2. Which OS version did you experience the issue on?
    - 12
3. Which Xcode version did you build the app with?
    - 15.2
5. Which Cocoapods version are you using (run `pod --version`)?
    - N/A. Frameworks are manually integrated

**Comment by E-Rockalanche** [comment]
Perhaps the reason should be C617.1? See https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393

**Comment by DmitriyKirakosyan** [comment]
@E-Rockalanche, thanks for the report! Have you tried changing the reason code to see if that resolves the issue? Additionally, consider removing this entry as it might not be necessary. See https://github.com/microsoft/appcenter-sdk-apple/issues/2538#issuecomment-2077709075.

**Comment by DmitriyKirakosyan** [comment]
Version 5.0.5, which includes the fix, has been released.
