### ISSUE TITLE
Does AppCenterCrashes has depedency on Firebase 

### ISSUE THREAD

**Issue by swasti29** [microsoft/appcenter-sdk-apple#2545]
### **Description**

MSAL SDK has been using App Center for Crash reporting, We received a security vulnerbility from [firebase-ios-sdk/Crashlytics/Crashlytics/Models/FIRCLSFileManager.m at eea09ef52a1762614e2e2805fb5749e32d8c96bc · wilg/firebase-ios-sdk (github.com)](https://github.com/wilg/firebase-ios-sdk/blob/eea09ef52a1762614e2e2805fb5749e32d8c96bc/Crashlytics/Crashlytics/Models/FIRCLSFileManager.m#L58)related to method createFileAtPath:contents:attributes:() on line 64 of FIRCLSFileManager.m writes data to a file lacking sufficient encryption settings.The identified method writes data to a file lacking sufficient encryption settings.

Is AppCenterCrashes has dependency on Firebase Crash SDK?

### **Details**

1. Which SDK version are you using?
   4.2.0
2. Which OS version did you experience the issue on?
   Idenpendent of the issue. 
3. Which Xcode version did you build the app with?
  Idenpendent of the issue
5. Which Cocoapods version are you using (run `pod --version`)?
    Using statically. 
6. What device version did you see this error on?  Were you using an emulator or a physical device?
     Idenpendent of the issue
7. What language are you using?
    - [x] Objective C
    - [ ] Swift

**Comment by DmitriyKirakosyan** [comment]
Hi @swasti29,

The App Center SDK is not dependent on Firebase SDK.
Please check your project dependencies to see if you are directly referencing the Firebase SDK or if any of your dependencies are using it.
