### ISSUE TITLE
MSACDistributionGroup.h & MSACDistributeIngestion.h File not found error in Xcode 16.0

### ISSUE THREAD

**Issue by Atamanam** [microsoft/appcenter-sdk-apple#2550]
### **Description**

Please describe the issue you are facing using the SDK.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Build the App 
2. seeing this error 
3. /Users/AmruthaTamanam/Library/Developer/Xcode/DerivedData/SCH-iOS-App-awcbczpojicsqcbwetteeiuitzco/SourcePackages/checkouts/appcenter-sdk-apple/AppCenterDistribute/AppCenterDistribute/Internals/MSACDistributeInternal.h:7:9 'MSACDistributeIngestion.h' file not found
/Users/AmruthaTamanam/Library/Developer/Xcode/DerivedData/SCH-iOS-App-awcbczpojicsqcbwetteeiuitzco/SourcePackages/checkouts/appcenter-sdk-apple/AppCenterDistribute/AppCenterDistribute/Model/MSACReleaseDetails.m:5:9 'MSACDistributionGroup.h' file not found

### **Details**

1. Which SDK version are you using?
    - e.g. 4.4.3
2. Which OS version did you experience the issue on?
    - e.g. iOS 17.0.1 & iOS 16.0
3. Which Xcode version did you build the app with?
    - e.g. Xcode 16.0

6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. iPhone 15 Pro Simulator, iPhone 16 Simulator 
7. What language are you using?
    - [ ] Swift
8. What third party libraries are you using?
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:

**Comment by MikhailSuendukov** [comment]
Hello, and thank you for reaching out! Could you please let us know if this issue persists with the latest version of Apple's AppCenter SDK (5.0.5)?

**Comment by DordeDimitrijev** [comment]
Closing due inactivity.

**Comment by MikhailSuendukov** [comment]
Hello and thanks for reaching out to us! Could you please clarify whether your error is reproducible on the latest version of the AppCenter Apple SDK (5.0.5)?

**Comment by MikhailSuendukov** [comment]
Hello and thanks for reaching out to us! I will close this issue as a duplicate of https://github.com/microsoft/appcenter-sdk-apple/issues/2554/.
