### ISSUE TITLE
The flag -exportOptionsPlist is required when specifying -exportArchive.

### ISSUE THREAD

**Issue by mennolaan** [Microsoft/AppCenter-SDK-Apple#860]
Im experiencing difficulties with a Embedded framework I'm using (https://github.com/LeoNatan/LNPopupController), the build stops in AppCenter. This is LNPopupController. This was added in my project to Embedded Binaries and Linked Frameworks and Libraries. The error mentions the exportOptionsPlist flag, where should this flag be added? The root project or in the project of LNPopupController.?

I'm using xcode 9.1, swift 3, iOs target  >= 10.3

** ARCHIVE SUCCEEDED **

[command]/usr/bin/xcodebuild -exportArchive -archivePath /Users/vsts/agent/2.124.0/work/1/output/build/archive/LNPopupController.xcarchive -exportPath /Users/vsts/agent/2.124.0/work/1/output/build/export/_XcodeTaskExport_LNPopupController
xcodebuild: error: The flag -exportOptionsPlist is required when specifying -exportArchive.
##[error]Error: /usr/bin/xcodebuild failed with return code: 64
##[section]Finishing: Xcode build (signed)
##[section]Starting: Analyze build log

**Comment by TroubleMakerBen** [comment]
Hey @mennolaan,

thx for getting in touch. I'm not sure if I understand your issue correctly. It sounds like you're running into an issue with the App Center Build feature?

Can you please contact us through intercom? It's the blue button with the plus sign on it at the right bottom corner in [appcenter.ms](https://appcenter.ms).

Best,
Benjamin

**Comment by TroubleMakerBen** [comment]
I'm closing this issue as it is not an SDK issue.
