### ISSUE TITLE
Use standard framework file hierarchy

### ISSUE THREAD

**Issue by ianbytchek** [Microsoft/AppCenter-SDK-Apple#863]
Hello friends! Taking the opportunity to express my excitement about the project! 🤓

While playing around with macOS SDK frameworks I got a signing error `AppCenterPush.framework/Versions/A: No such file or directory`. Looking closer at them and how they are built it seems you are not following the [convention](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html#//apple_ref/doc/uid/20002253-100202) Xcode uses, hence the error – this must be the standard way for organising framework contents and probably needed for versioning mostly. 

I assume you build static libs then convert them into dynamic and package into framework for the sake of not duplicating target logic. Nice approach!

**Comment by TroubleMakerBen** [comment]
Hey @ianbytchek,

thx for getting in touch.
Can you share a little bit more about how you are integrating the SDK (if you don't want to do so publicly, please send me an email to bereimol at my employer dot com, or get in touch through intercom – the blue button at the bottom right corner in the portal)?

You are right that we don't follow the Xcode convention as we haven't done that for HockeyApp for a while and it's not uncommon to simplify the structure within fake frameworks.
This leads me to why you are seeing the error. The App Center SDK is actually a static library and not a dynamic framework (HockeyApp is a dynamic framework). My guess is that you added the AppCenterPush.framework under "embed framework". Please make sure you this is not the case – the AppCenter*.frameworks need to be linked but not embedded (they need to appear in "Link Binary with Libraries").

Please let me know if this solves the issue for you and don't hesitate to get in touch!

Benjamin

**Comment by ianbytchek** [comment]
Hey @TroubleMakerBen! I've created a Cocoa app in Xcode for testing purposes, I don't use CocoaPods and simply downloaded the [release](https://github.com/Microsoft/AppCenter-SDK-Apple/releases/download/1.0.1/AppCenter-SDK-Apple-1.0.1.zip). Integrated `AppCenter.framework`, `AppCenterAnalytics.framework` and `AppCenterCrashes.framework` by linking and embedding. Yes, `AppCenterPush.framework` had some issues – I think it requires entitlements and additional provisioning, so I dumped it from the beginning. The app builds fine without signing, but fails with aforementioned error when signing is enabled:

![2017-12-01 11 19 32](https://user-images.githubusercontent.com/1086845/33472019-a9889832-d689-11e7-9652-b6d8b9ea65c6.gif)

> My guess is that you added the AppCenterPush.framework under "embed framework". Please make sure you this is not the case – the AppCenter*.frameworks need to be linked but not embedded (they need to appear in "Link Binary with Libraries").

I think we're referring to different things. Unless I embed all linked frameworks the distributed app won't run – loader won't find them will… 💥 

I've seen similar Xcode behaviour in the past when it expects certain file structure of bundle / framework, which didn't make a lot of sense to me personally, but it is how it is. So, it does look like for something to be a conventional framework it must follow the hierarchy, otherwise it's just a dylib with headers, which would need to me linked and embedded accordingly. 🙄

**Comment by TroubleMakerBen** [comment]
Hey, 

First, thx for making the gif above. This makes the conversation so much easier. I really appreciate you taking the time. That said, we are definitely talking about the same thing.
 You are copying/embedding the frameworks in a phase in the "Build Phases" tab, which can't work for static libraries. Please simply link the libraries and don't embed them.

I've recorded a quick [video](https://www.dropbox.com/s/te5imbhbjee2e23/Integrate_mac_sdk_smaller.mov?dl=0).

Best,
Benjamin

**Comment by ianbytchek** [comment]
Hey Ben, ok, I finally got what's going on. Apparently you're creating [static frameworks](https://developer.apple.com/library/content/technotes/tn2435/_index.html#//apple_ref/doc/uid/DTS40017543-CH1-TROUBLESHOOTING_BUNDLE_ERRORS-EMBEDDED_STATIC_LIBRARIES) I've never seen that in the wild before! 😃 Makes perfect sense now, thanks! Working on and using @gifox for gifs, emailed you a present.

**Comment by TroubleMakerBen** [comment]
Hey @ianbytchek,
Thx for the present, I was wondering what that one was about ^^

I'm sorry that I didn't explicitly say that App Center is a static framework, I've taken a note to be explicit about this and not assume people read that much between the lines.

Take care and let me know if there's anything else we can do for you. Oh, and thx for trying out App Center. =)

Benjamin
