### ISSUE TITLE
tvos support?

### ISSUE THREAD

**Issue by Konrad77** [microsoft/appcenter-sdk-apple#884]
Is there any reason why tvOS is not supported?

**Comment by TroubleMakerBen** [comment]
Hey @Konrad77,

Thx for getting in touch. tvOS support will arrive very soon (in fact, the SDK's code is already ready for tvOS hiere on GH). There are a few more things we need to do to enable us to ship this, stay tuned!

Best,
Benjamin

**Comment by ElektrojungeMS** [comment]
Hey guys,

We don't have any update to share regarding tvOS support. We will update our roadmap and this issue as soon as we have anything to share!

Thanks for being your patience and for using HockeyApp!

**Comment by derpixeldan** [comment]
It's now manifested in our [public roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap#diagnostics).

**Comment by jaelim-ms** [comment]
Hello all.
We are pleased to announce that App Center now supports tvOS.
Documentation can be found [here](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/tvos) and integration would be the same way as iOS and macOS.
