### ISSUE TITLE
Device Request.

### ISSUE THREAD

**Issue by sShrek1** [microsoft/appcenter-sdk-apple#921]
Add support for requesting UDID from a user. 

Some of our users sometimes press "already registered" before reading all content, meaning AppCenter doesn't add this user-device to the "Devices"-tab. 

Something like selecting a user without device and ask for request. AppCenter then sends email with "register" and when user press it, the magic is done (just repeating the whole "REGISTER" thing but with text different than "register").

The problem is "REGISTER" may seem like "SIGN UP" or "Register account" which is a bit confusing for our testers.

**Comment by JoshuaWeber** [comment]
Hi. Thanks for this feature request. I want to make sure I understand you perfectly. You are stating that sometimes your users are skipping the device registration steps. You would like a way to re-notify them that the registration step is needed and help them be successful in registering their device.

**Comment by sShrek1** [comment]
@JoshuaWeber 
Exactly, they sometimes thinks the "register" is the "sign up for AppCenter"-thing.

An example:
* User navigate to "https://install.appcenter.ms/apps" after sign up. They press "Already registered".
* On the Groups-tab for administration i see there is a user without a device registered, i should be able to select the user and press "Request device registration".  (a nice feature would be customized message).

* The user gets an email with my customized message and press something like "Add device" which navigates to custom "/Register-devices/register".

**Comment by tsafrir** [comment]
+1 
I not able to help users who skip the device registration.
Any workaround I can use?

**Comment by sShrek1** [comment]
@tsafrir if the user skip the device registration send them this link "https://install.appcenter.ms/register-device". That solved the problem for our users.

**Comment by TroubleMakerBen** [comment]
@sShrek1 that's the right link, yes. In addition, if you are using our app "HockeyApp for AppCenter", it has a button to re-register. Our [blogpost](https://blogs.msdn.microsoft.com/vsappcenter/how-and-why-we-built-our-new-visual-studio-app-center-tester-apps-preview-now-available/) contains links to our testflight signup page as well as a link to join the distribution group for the Android version.

**Comment by DmitriyKirakosyan** [comment]
This issue should be fixed now, so I'm closing it but feel free to reopen if you feel the problem still persists.
